// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require ../chunks/tslib.es6 ../Basemap ../Viewpoint ../core/asyncUtils ../core/Collection ../core/collectionUtils ../core/JSONSupport ../core/Logger ../core/mathUtils ../core/maybe ../core/promiseUtils ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ../core/accessorSupport/ensureType ../chunks/vec3 ../chunks/vec3f64 ../layers/Layer ../support/basemapUtils ../views/support/Scheduler ../webdoc/support/SlideThumbnail ./SunLighting ./VirtualLighting ./support/Description ./support/SlideEnvironment ./support/SlideGround ./support/SlideVisibleLayer ./support/Title".split(" "),
function(M,f,N,O,P,z,Q,d,R,S,A,B,T,h,n,da,ea,U,u,C,v,V,D,W,m,X,Y,r,E,F,G,p){function H(a){if("building-scene"===a.type||"map-image"===a.type)return a.allSublayers.toArray()}function I(a){if(a=H(a))return a.filter(b=>b.visible).map(b=>b.id)}function Z(a,b){a=b-a;43200<a&&(a-=86400);-43200>a&&(a+=86400);return a}let aa=0;const w=z.ofType(G.SlideVisibleLayer);d=class extends d.JSONSupport{constructor(a){super(a);this.id=Date.now().toString(16)+"-slide-"+aa++;this.title=new p;this.description=new r;this.hidden=
!1;this.thumbnail=new m.SlideThumbnail;this.ground=this.basemap=this.viewpoint=null;this.environment=new E.SlideEnvironment;this.visibleLayers=new w}destroy(){this.visibleLayers.removeAll();this.basemap=null;this.thumbnail=A.destroyMaybe(this.thumbnail);this.thumbnail=this.title=this.description=null}castTitle(a){return"string"===typeof a?new p({text:a}):u.ensureType(p,a)}castDescription(a){return"string"===typeof a?new r({text:a}):u.ensureType(r,a)}castThumbnail(a){return"string"===typeof a?new m.SlideThumbnail({url:a}):
u.ensureType(m.SlideThumbnail,a)}castBasemap(a){return D.ensureType(a)}set visibleLayers(a){this._set("visibleLayers",Q.referenceSetter(a,this._get("visibleLayers"),w))}castVisibleLayers(a){return a&&"function"===typeof a.map?a.map(b=>{if("string"===typeof b)return{id:b};if(b instanceof V){const c=I(b);return{id:b.id,sublayerIds:c}}if(b.id)return{id:b.id,sublayerIds:"sublayerIds"in b?b.sublayerIds:void 0};R.getLogger(this).warn('Invalid visible layer, expected { id }, Layer or "id"');return b}):null}clone(){return new this.constructor({id:this.id,
title:this.title.clone(),thumbnail:this.thumbnail.clone(),description:this.description&&this.description.clone()||null,viewpoint:this.viewpoint&&this.viewpoint.clone()||null,basemap:this.basemap?.clone()||null,ground:this.ground?.clone()||null,visibleLayers:this.visibleLayers.clone(),environment:this.environment&&this.environment.clone()||null,hidden:this.hidden})}async _updateVisibleLayersFrom(a){const b=[];await Promise.allSettled(this._getLayers(a.map).map(c=>a.whenLayerView(c).then(g=>{if(g.visible){const e=
I(c);b.push(new G.SlideVisibleLayer({id:g.layer.id,sublayerIds:e}))}})).toArray());this.visibleLayers.removeAll();this.visibleLayers.addMany(b)}updateFrom(a,b){const c={format:"png",quality:80,width:120,height:75,disableDecorations:!0,...b?.screenshot};return a.when(()=>{this.viewpoint=a.viewpoint.clone();this.environment.lighting="virtual"===a.environment.lighting.type?Y.prototype.clone.apply(a.environment.lighting):X.prototype.clone.apply(a.environment.lighting);this.environment.weather=a.environment.weather.clone();
this.basemap=a.map.basemap&&a.map.basemap.clone()||null;this.ground=a.map.ground?F.fromGround(a.map.ground):null;return this._updateVisibleLayersFrom(a)}).then(()=>a.takeScreenshot(c)).then(g=>{this.thumbnail=new m.SlideThumbnail({url:g.dataUrl});return this})}async applyTo(a,b){null!=this._applyToController&&this._applyToController.abort();let c=new AbortController;this._applyToController=c;const g=B.onAbortOrThrow(b,()=>c?.abort()),e=a.resourceController.scheduler.registerTask(W.TaskPriority.SLIDE);
let t=!1;const k={animate:!0,...b,signal:this._applyToController.signal};b=await P.result(a.addUpdatingPromise((async()=>{await Promise.all([e.schedule(async()=>t=await this._setViewpointOfInterest(a,k)),e.schedule(()=>this._applyBasemap(a,k),k.signal)]);await this._loadLayersWithSublayerVisibility(a);await Promise.all([e.schedule(()=>this._applyLayerVisibility(a),k.signal),e.schedule(()=>this._applyGround(a),k.signal),e.schedule(()=>this._applyViewpoint(a,k),k.signal)]);await e.schedule(()=>a.environment.weather=
this.environment.weather.clone())})()));t&&(a.contentCamera=null);e.remove();this._applyToController===c&&(this._applyToController=null);c=null;g?.remove();if(!1===b.ok)throw b.error;return this}async _applyBasemap(a,b){if(this.basemap){try{await this.basemap.load(b)}catch(c){if(B.isAbortError(c))throw c;}a.map.basemap=D.clonePreservingTiledLayers(this.basemap,a.map.basemap)}}_applyGround(a){this.ground&&(a.map.ground=this.ground.cloneAndApplyTo(a.map.ground))}_getLayers(a){const b=new z;this._collectLayers(a,
b);this._collectLayers(a.ground,b);return b}_collectLayers(a,b){a.layers.forEach(c=>{c.persistenceEnabled&&(b.add(c),"layers"in c&&this._collectLayers(c,b))})}async _loadLayersWithSublayerVisibility(a){this.visibleLayers&&await Promise.allSettled(this._getLayers(a.map).items.map(b=>this.visibleLayers.find(c=>c.id===b.id)?.sublayerIds?b.load():null))}_applyLayerVisibility(a){this.visibleLayers&&this._getLayers(a.map).forEach(b=>{var c=this.visibleLayers.find(e=>e.id===b.id);b.visible=null!=c;const g=
c?.sublayerIds;c=H(b);g&&c&&c.forEach(e=>e.visible=g.includes(e.id))})}async _setViewpointOfInterest(a,b){if(a.state.fixedContentCamera||!this.viewpoint||b?.ignoreViewpoint||!b?.useDestinationCamera)return!1;({toCameraAsync:b}=await new Promise((c,g)=>M(["../views/3d/support/viewpointUtils"],c,g)));b=await b(a,this.viewpoint);a.contentCamera=b;return null!=b}async _applyViewpoint(a,b){this._applyCachedCameraTrackingEnabled(a);if(this.viewpoint&&!b.ignoreViewpoint){null!=this.viewpoint.camera&&(this.viewpoint.camera.fov=
a.camera.fov);const c=this.environment.lighting;if(b.animate&&"sun"===c.type&&c.date)return this._animateToLighting(a,b);b.animate&&(a.environment.applyLighting(c.clone()),await a.goTo(this.viewpoint,b));a.viewpoint=this.viewpoint}a.environment.applyLighting(this.environment.lighting.clone())}async _animateToLighting(a,b){let c=null;"virtual"!==a.environment.lighting.type&&"virtual"!==this.environment.lighting.type&&("global"===a.viewingMode&&(c=this._animateLightingWithCamera(a,a.environment.lighting,
this.environment.lighting)),a.environment.cachedCameraTrackingEnabled=a.environment.lighting.cameraTrackingEnabled,a.environment.lighting.cameraTrackingEnabled=!1);a.environment.lighting.directShadowsEnabled=this.environment.lighting.directShadowsEnabled;"virtual"===this.environment.lighting.type||"virtual"===a.environment.lighting.type?(a.environment.applyLighting(this.environment.lighting.clone()),"virtual"!==a.environment.lighting.type&&(a.environment.cachedCameraTrackingEnabled=a.environment.lighting.cameraTrackingEnabled,
a.environment.lighting.cameraTrackingEnabled=!1)):null!=this.environment.lighting.displayUTCOffset&&(a.environment.lighting.displayUTCOffset=this.environment.lighting.displayUTCOffset);return a.goTo(this.viewpoint,b).then(()=>{this._applyCachedCameraTrackingEnabled(a);a.environment.applyLighting(this.environment.lighting.clone())}).catch(g=>{null==a.animation&&this._applyCachedCameraTrackingEnabled(a);throw g;}).finally(()=>{A.removeMaybe(c)})}_applyCachedCameraTrackingEnabled(a){null!=a.environment.cachedCameraTrackingEnabled&&
(a.environment.lighting.cameraTrackingEnabled=a.environment.cachedCameraTrackingEnabled,a.environment.cachedCameraTrackingEnabled=null)}_getTime(a){const b=a.getTime();a=3600*a.getUTCHours()+60*a.getUTCMinutes()+a.getUTCSeconds();return[b,a]}_setTime(a,b,c){a.setTime(b);a.setUTCHours(c/3600);a.setUTCMinutes(c%3600/60);a.setUTCSeconds(c%3600%60);return a}_animateLightingWithCamera(a,b,c){const [g,e]=this._getTime(new Date(b.date.toString())),[t,k]=this._getTime(c.date),ba=Z(e,k),x=a.renderCoordsHelper,
J=v.create();x.toRenderCoords(a.camera.position,J);const K=v.create(),y=v.create();null!=this.viewpoint.camera&&x.toRenderCoords(this.viewpoint.camera.position,K);const ca=new Date;return T.when(()=>a.camera,l=>{x.toRenderCoords(l.position,y);var q=C.squaredDistance(J,y);const L=C.squaredDistance(K,y);l=0;0!==q+L&&(l=q/(q+L));q=g+(t-g)*l;l=S.moduloPositive(e+ba*l,86400);b.date=this._setTime(ca,q,l)})}static createFrom(a,b){return(new this).updateFrom(a,b)}};f.__decorate([h.property({type:String,json:{write:{isRequired:!0}}})],
d.prototype,"id",void 0);f.__decorate([h.property({type:p,json:{default:()=>new p({text:""}),write:{isRequired:!0}}})],d.prototype,"title",void 0);f.__decorate([n.cast("title")],d.prototype,"castTitle",null);f.__decorate([h.property({type:r,json:{write:{overridePolicy(a){return{enabled:!(!a||!a.text)}}}}})],d.prototype,"description",void 0);f.__decorate([n.cast("description")],d.prototype,"castDescription",null);f.__decorate([h.property({type:Boolean,nonNullable:!0,json:{write:!0,default:!1}})],d.prototype,
"hidden",void 0);f.__decorate([h.property({type:m.SlideThumbnail,json:{default:()=>new m.SlideThumbnail({url:""}),write:{isRequired:!0}}})],d.prototype,"thumbnail",void 0);f.__decorate([n.cast("thumbnail")],d.prototype,"castThumbnail",null);f.__decorate([h.property({type:O,nonNullable:!0,json:{write:{isRequired:!0}}})],d.prototype,"viewpoint",void 0);f.__decorate([h.property({type:N,json:{read:{source:"baseMap"},write:{target:"baseMap"}}})],d.prototype,"basemap",void 0);f.__decorate([n.cast("basemap")],
d.prototype,"castBasemap",null);f.__decorate([h.property({type:F,json:{write:!0}})],d.prototype,"ground",void 0);f.__decorate([h.property({type:w,json:{write:{isRequired:!0}}})],d.prototype,"visibleLayers",null);f.__decorate([n.cast("visibleLayers")],d.prototype,"castVisibleLayers",null);f.__decorate([h.property({type:E.SlideEnvironment,json:{write:!0}})],d.prototype,"environment",void 0);return d=f.__decorate([U.subclass("esri.webscene.Slide")],d)});