// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../intl ../../core/arrayUtils ../../core/compilerUtils ../../core/string ../../layers/support/domainUtils ../../layers/support/fieldUtils ../../smartMapping/support/utils ../support/dateUtils ../../intl/substitute".split(" "),function(c,L,H,I,k,r,n,J,t,u){function v(a){const {fields:b,values:e}=a,f=a.timeZone??void 0;a=b.map((d,h)=>{let g=e[h];d.domain&&"coded-value"===d.domain.type&&(h=d.domain.codedValues.find(p=>p.code===g),h?.name&&(g=h.name));if(J.isAnyDateField(d)||n.isTimeOnlyField(d))g=
t.getLabelForDateFieldValue(d,g,{timeZone:f,...t.getIntlOptionsForField(d)});return[d.name,g]});return Object.fromEntries(a)}function w(a,b){return k.replace(k.replace(a,e=>`{${e.toLowerCase()}}`),Object.fromEntries(Object.entries(b).map(([e,f])=>[e.toLowerCase(),f])))}function x(a){return 1E7<=a||-1E7>=a}const y=a=>"field"===a?.type,z=a=>"relationship"===a?.type,A=a=>"field"===a.type,q=a=>a.reduce((b,e)=>"group"===e?.type?[...b,...e.inputs]:[...b,e],[]),l=(a,b)=>null!=a&&a.input?.type===b,B={typeFieldName:null,
types:[]};c.LengthValidationError=void 0;(c.LengthValidationError||(c.LengthValidationError={})).TOO_SHORT="length-validation-error::too-short";const C={type:"number"},D={type:"number",intlOptions:{notation:"scientific"}},E={day:"2-digit",month:"2-digit",year:"numeric"},F={hour:"numeric",minute:"numeric",second:"numeric"},K={...E,...F};c.capabilitiesAllowEditType=(a,b)=>{if(!a)return!0;({operations:a}=a);switch(b){case "INSERT":return a.supportsAdd;case "UPDATE":case "DELETE":return a.supportsUpdate;
default:return!0}};c.flattenFieldInputs=a=>q(a).filter(y);c.flattenInputs=q;c.flattenRelationshipInputs=a=>q(a).filter(z);c.formTemplateHasInvalidFields=function(a){return"formTemplate"in a&&a.formTemplate?(a.formTemplate.elements?.filter(A)??[]).some(({fieldName:b})=>!a.fieldsIndex.get(b)):!1};c.getComputedAttributes=v;c.getErrorMessageForFieldInput=(a,b,e)=>{const {dataType:f,error:d,minLength:h,value:g,required:p}=a;if(!b||!d)return null;if(p&&null===g)return b.validationErrors.cannotBeNull;if(d===
r.DomainValidationError.VALUE_OUT_OF_RANGE||d===n.NumericRangeValidationError.OUT_OF_RANGE){const {field:G,range:m}=a;a={type:"date",intlOptions:{...("time-only"===G.type?F:"date-only"===G.type?E:K),timeZone:e??void 0}};return u.substitute(b.validationErrors.outsideRange,m,{format:{max:"date"===f?a:null!=m.max&&x(m.max)?D:C,min:"date"===f?a:null!=m.min&&x(m.min)?D:C}})}return d===r.DomainValidationError.INVALID_CODED_VALUE?b.validationErrors.invalidCodedValue:d===n.TypeValidationError.INVALID_TYPE?
b.validationErrors.invalidType:d===c.LengthValidationError.TOO_SHORT?u.substitute(b.validationErrors.tooShort,{min:h}):null};c.getFieldsInTitleAndDesc=a=>{const b=[];if(a.formTemplate){const {description:e,title:f}=a.formTemplate;a.fields?.forEach(d=>{const h=f&&k.templateHasKey(f,d.name),g=e&&k.templateHasKey(e,d.name);(h||g)&&b.push(d.name)})}return b};c.getIconForFeature=a=>{if(a){var b=a.layer;b=b&&"geometryType"in b?b.geometryType:void 0;a=a.geometry?.type;return"polyline"===a||"polyline"===
b?"line":a||b||"table"}};c.getNormalizedFeatureTypeInfo=a=>a?"subtype-sublayer"===a.type?{typeFieldName:a.parent?.subtypeField,types:a.parent?.subtypes??[]}:"types"in a&&a.types?{typeFieldName:a.typeIdField,types:a.types.map(({id:b,name:e,domains:f})=>({code:b,name:e,domains:f}))}:B:B;c.isFieldElement=A;c.isFieldElementWithInputType=l;c.isFieldElementWithShowNoValueOptionInput=a=>null!=a&&(l(a,"combo-box")||l(a,"radio-buttons"));c.isFieldElementWithTextInput=a=>null!=a&&(l(a,"text-box")||l(a,"text-area"));
c.isFieldInput=y;c.isGroupElement=a=>"group"===a.type;c.isGroupInput=a=>"group"===a?.type;c.isInputInGroupInput=a=>"group"!==a?.type&&null!=a.group;c.isNumberFieldInput=({domain:a,inputType:b="text-box",dataType:e})=>"number"===e&&"text-box"===b&&(!a||"coded-value"!==a.type);c.isRelationshipElement=a=>"relationship"===a.type;c.isRelationshipInput=z;c.isTemplateItemGroup=a=>"items"in a;c.parseFormTemplateString=function(a){const {attributes:b,fieldsIndex:e,label:f,timeZone:d}=a;if(!b||"object"!==typeof b)return f;
var h=Object.keys(b).filter(g=>k.templateHasKey(f,g));a=h.map(g=>b[g]);h=h.map(g=>e.get(g)).filter(H.isSome);return w(f,v({values:a,fields:h,timeZone:d}))};c.substituteFieldTemplatesInString=w;c.valueIsInvalidSwitchValue=function(a,b){return null==a||b.onValue!==a&&b.offValue!==a};c.valueIsValidContingentValue=function(a,b){switch(b.objectType){case "any":return!0;case "null":return null==a;case "code":return a===b.codedValue?.code;case "range":return null!=a&&null!=b.minValue&&null!=b.maxValue&&
+a>=b.minValue&&+a<=b.maxValue;default:return I.neverReached(b.objectType),!1}};Object.defineProperty(c,Symbol.toStringTag,{value:"Module"})});