// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/tslib.es6 ../../core/Error ../../core/handleUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/subclass ../../views/support/layerViewUtils ./UpdateFeatureWorkflowData ./UpdateRecordWorkflow ./workflowUtils".split(" "),function(e,r,x,y,v,C,D,E,z,A,B,w,g){var t;const h={...w.handleKeys,highlights:Symbol(),sketch:Symbol()};e.UpdateFeatureWorkflow=t=class extends w.UpdateRecordWorkflow{constructor(a){super(a);
this.type="update-feature";this._sketchGraphicClone=this._layerViewEditSession=null;this._webStyleCache=new Map}initialize(){const {edits:{feature:a},layerView:b}=this.data;g.canCreateInteractiveEditSession(b)&&(this._layerViewEditSession=b.createInteractiveEditSession(a))}destroy(){this._layerViewEditSession?.rollback()}async commit(){this.removeHandles(h.sketch);try{const a=this.data.edits.stagedForDelete;await super.commit();const b=this._layerViewEditSession;a?b?.rollback():b?.commit()}catch(a){throw await this._configureSketchViewModel(),
new x("editor-workflow:failed-to-commit","An error occurred when sending the updates to the service",{error:a});}}async start(){await super.start();return this._initializeSketchViewModel()}_configureFeatureFormViewModel(){super._configureFeatureFormViewModel();const {_layerViewEditSession:a}=this,{viewModel:b}=this.data;this.addHandles(b.featureFormViewModel.on("value-change",c=>{a?.setAttribute(c.fieldName,c.value)}),h.exit)}_configureHighlight(){const {edits:a,layerView:b}=this.data;A.highlightsSupported(b)&&
this.addHandles(b.highlight(a.feature),h.highlights)}async _configureSketchViewModel(){const {data:a,_sketchGraphicClone:b}=this,{edits:c,viewModel:k}=a;var f=c.feature;const {featureFormViewModel:l,sketchViewModel:m,view:q}=k;m.allowDeleteKey=!1;const n=g.getVisualVariableAttributes(f);f=await g.setUpGeometryUpdate({feature:f,featureClone:b,visualVariableAttributes:n,sketchViewModel:m,view:q,onUpdate:({geometry:d,attributes:u},p)=>{c.updateAttributes(u);c.updateGeometry(d);l.feature.geometry=d;null!=
n.rotation&&({field:d}=n.rotation,l.setValue(d,u[d]));null!=n.size&&({field:d}=n.size,l.setValue(d,u[d]));("undo"===p.type||"redo"===p.type||"update"===p.type&&null!=p.toolEventInfo&&g.isTerminalUpdateEventType(p.toolEventInfo.type))&&l.notifyFeatureGeometryChanged()},webStyleCache:this._webStyleCache});this.addHandles(f,h.sketch)}async _initializeSketchViewModel(){const {data:a,_sketchGraphicClone:b}=this,c=a.edits.feature,{sketchViewModel:k}=a.viewModel,{geometryUpdatesEnabled:f}=a.editableItem,
l=k.updateOnGraphicClick;k.updateOnGraphicClick=!1;this.addHandles([y.makeHandle(()=>{k.updateOnGraphicClick=l})]);f&&this.addHandles([await g.swapForEditingSession(k,c,b)]);const {highlights:m,sketch:q}=h;return{enter:async()=>{!this.hasHandles(q)&&f?await this._configureSketchViewModel():this.hasHandles(m)||this._configureHighlight()},exit:()=>this.removeHandles([q,m])}}_onFullFeatureLoaded(a){super._onFullFeatureLoaded(a);this._sketchGraphicClone=g.cloneGraphicExceptMesh(a);const {edits:b}=this.data;
b.updateGeometry(a.geometry);b.trackChanges()}static async create(a){a=new t({data:await B.create(a),onCommit:this._onCommitFactory(a.applyEdits)});a._set("steps",this._createWorkflowSteps(a));return a}};r.__decorate([v.property()],e.UpdateFeatureWorkflow.prototype,"_layerViewEditSession",void 0);r.__decorate([v.property()],e.UpdateFeatureWorkflow.prototype,"_sketchGraphicClone",void 0);e.UpdateFeatureWorkflow=t=r.__decorate([z.subclass("esri.widgets.Editor.UpdateFeatureWorkflow")],e.UpdateFeatureWorkflow);
e.handleKeys=h;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});