// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../request ../../../core/arrayUtils ../../../core/Error ../../../core/Logger ../../../core/promiseUtils ../../../layers/support/fieldUtils ../../../core/has ../../../layers/support/source/DataLayerSource ../../../rest/query/executeQueryJSON ../../../config ../../../kernel ../../../core/urlUtils ../../../core/unitUtils ../../../geometry/ellipsoidUtils ../../../geometry/support/spatialReferenceUtils ../../../layers/graphics/featureConversionUtils ../../../geometry/Extent ../../../geometry/Geometry ../../../geometry/Multipoint ../../../geometry/Point ../../../geometry/Polygon ../../../geometry/Polyline ../../../geometry/support/normalizeUtils ../../../core/pbf ../../../rest/support/FeatureSet ../../../rest/support/Query ../../../rest/query/support/AttachmentInfo ../../../rest/support/AttachmentQuery ../../../geometry ../../../rest/support/RelationshipQuery ../../../rest/support/TopFeaturesQuery ../../../rest/support/StatisticDefinition ./featureUtils".split(" "),
function(g,A,t,u,B,k,C,P,Q,n,R,S,T,U,V,W,X,Y,Z,aa,ba,ca,da,ea,fa,ha,p,ia,ja,ka,D,la,E,F){function G(b,a){if(!a.relationships)return null;let c=null;({relationships:a}=a);a.some(d=>d.id===parseInt(b,10)?(c=d,!0):!1);return c}function v({originRelationship:b,relationships:a,layerId:c}){let d=null;a&&a.some(e=>{`${e.relatedTableId}`===c&&e.id===b?.id&&(d=e);return!!d});return d}function H(b,a){a=a.toLowerCase();for(const c in b)if(c.toLowerCase()===a)return b[c];return null}function I(b,a,c,d){const e=
new D;e.outFields=["*"];e.relationshipId="number"===typeof a.id?a.id:parseInt(a.id,10);e.objectIds=[b.attributes[c.objectIdField]];return c.queryRelatedFeatures?.(e,d)??Promise.resolve({})}function J(b,a,c){let d=0;const e=[];for(;d<a.length;)e.push(`${b} IN (${a.slice(d,c+d)})`),d+=c;return e.join(" OR ")}function w(b){return b?t.unique(b):void 0}function x(b){return b?t.unique(b,(a,c)=>JSON.stringify(a.toJSON())===JSON.stringify(c.toJSON())):void 0}async function K(b,a,c,d){var e=c.layerId.toString();
const {layerInfo:f,relation:h,relatedFields:l,outStatistics:L,url:q,sourceSpatialReference:r}=a;a=w(l);const m=x(L);if(!f||!h)return null;e=v({originRelationship:h,relationships:f.relationships,layerId:e});if(e?.relationshipTableId&&e.keyFieldInRelationshipTable){c=(await I(b,e,c,d))[b.attributes[c.objectIdField]];if(!c)return null;const N=c.features.map(M=>M.attributes[f.objectIdField]);if(m?.length&&f.supportsStatistics)return d=new p,d.where=J(f.objectIdField,N,1E3),d.outFields=a,d.outStatistics=
m,d.sourceSpatialReference=r,d={features:Promise.resolve(c),statsFeatures:n.executeQueryJSON(q,d)},k.eachAlways(d)}return(c=e?.keyField)?(e=C.isNumericField(O(f.fields,c)),b=H(b.attributes,h.keyField),c=e?`${c}=${b}`:`${c}='${b}'`,b=n.executeQueryJSON(q,new p({where:c,outFields:a,sourceSpatialReference:r}),d),d=m?.length&&f.supportsStatistics?n.executeQueryJSON(q,new p({where:c,outFields:a,outStatistics:m,sourceSpatialReference:r}),d):null,a={features:b},d&&(a.statsFeatures=d),k.eachAlways(a)):null}
function O(b,a){if(null!=b){a=a.toLowerCase();for(const c of b)if(c&&c.name.toLowerCase()===a)return c}return null}const y=B.getLogger("esri.widgets.Feature.support.relatedFeatureUtils"),z=new Map;g.createRelatedInfo=function(b,a){if(b=G(b,a))return{url:`${a.url}/${b.relatedTableId}`,sourceSpatialReference:a.spatialReference,relation:b,relatedFields:[],outStatistics:[]}};g.getDestinationRelation=v;g.getRelatedFieldInfo=function(b){if(!F.isRelatedField(b))return null;const [a,c]=b.split("/").slice(1);
return{layerId:a,fieldName:c}};g.getUniqueOutFields=w;g.getUniqueOutStatistics=x;g.queryLayerInfos=function({relatedInfos:b,layer:a},c){const d={};b.forEach((e,f)=>{({relation:e}=e);if(!e)throw f=new u("relation-required","A relation is required on a layer to retrieve related records."),y.error(f),f;({relatedTableId:e}=e);if("number"!==typeof e)throw f=new u("A related table ID is required on a layer to retrieve related records."),y.error(f),f;e=`${a.url}/${e}`;const h=z.get(e),l=h??A(e,{query:{f:"json"},
signal:(void 0)?.signal});h||z.set(e,l);d[f]=l});return k.whenOrAbort(k.eachAlways(d),c)};g.queryRelatedFeatures=function({graphic:b,relatedInfos:a,layer:c},d){const e={};a.forEach((f,h)=>{f.layerInfo&&(e[h]=K(b,f,c,d))});return k.eachAlways(e)};g.setRelatedFeatures=function(b,a){if(a&&b){var {features:c,statsFeatures:d}=b;b=c?.value;a.relatedFeatures=b?b.features:[];b=d?.value;a.relatedStatsFeatures=b?b.features:[]}};g.updateRelatedInfo=function({relatedInfo:b,fieldName:a,fieldInfo:c}){b.relatedFields?.push(a);
c.statisticType&&(a=new E({statisticType:c.statisticType,onStatisticField:a,outStatisticFieldName:a}),b.outStatistics?.push(a))};Object.defineProperty(g,Symbol.toStringTag,{value:"Module"})});