// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/tslib.es6 ../../../../intl ../../../../core/memoize ../../../../core/quantityFormatUtils ../../../../core/reactiveUtils ../../../../core/unitFormatUtils ../../../../core/unitUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/decorators/subclass ../../../../support/getDefaultUnitForView ../../keybindings ../../../../widgets/Widget ../../../../widgets/support/componentsUtils ../../../../widgets/support/widgetUtils ../../../../widgets/support/decorators/messageBundle ../../../../intl/number".split(" "),
function(l,e,f,A,u,h,p,v,m,g,B,C,D,w,q,x,y,z,E,r,n){e.TooltipContent=class extends y{constructor(){super(...arguments);this._getFormatters=u.memoize((a,b)=>({angle:c=>h.formatAngle(c,c.rotationType),area:(c,d)=>h.formatArea(a,c,d??b.area),length:(c,d,k)=>h.formatLength(a,c,d??b.length,k),relativeLength:(c,d)=>h.formatRelativeLength(a,c,d??b.length),totalLength:(c,d)=>h.formatLength(a,c,d??b.length),verticalLength:(c,d)=>h.formatVerticalLength(a,c,d??b.length),relativeVerticalLength:(c,d)=>h.formatRelativeVerticalLength(a,
c,d??b.verticalLength),relativeOrientation:c=>n.formatNumber(c,{maximumFractionDigits:2,minimumFractionDigits:2,signDisplay:"exceptZero"}),percentage:c=>n.formatNumber(c.value,{style:"percent"}),scale:c=>n.formatNumber(c,{style:"percent",maximumFractionDigits:0})}));this._formatScale=a=>this._formatters.scale(a);this._formatRelativeOrientation=a=>this._formatters.relativeOrientation(a);this._formatLength=(a,b,c)=>this._formatters.length(a,b,c);this._formatRelativeLength=(a,b)=>this._formatters.relativeLength(a,
b);this._formatVerticalLength=(a,b)=>this._formatters.verticalLength(a,b);this._formatRelativeVerticalLength=(a,b)=>this._formatters.relativeVerticalLength(a,b);this._formatArea=(a,b)=>this._formatters.area(a,b);this._formatPercentage=a=>this._formatters.percentage(a);this._onDiscard=()=>{this._exitInputMode()};this._onCommit=(a,b)=>{if("commit-and-exit"===b)return this._exitInputMode();const c=this._getFocusableInputs(),d=c.length;a=c.indexOf(a);if(-1===a)return this._exitInputMode();c.at(((a+("commit-and-next"===
b?1:-1))%d+d)%d)?.focus()};this._handleTab=a=>{if(a.code===x.tooltipKeys.next){var b=this._getFocusableInputs();if(0!==b.length){var c=b.at(0);b=b.at(-1);c&&b&&(a.shiftKey?document.activeElement===c&&(a.preventDefault(),b.focus()):document.activeElement===b&&(a.preventDefault(),c.focus()))}}}}get _displayUnits(){const a=q.getDefaultUnitForView(this.tooltip.view);return{length:a,verticalLength:a,area:a,angle:"degrees"}}get _inputUnitInfos(){const a=this._messagesUnits,b=t=>({unit:t,abbreviation:v.unitName(a,
t,"abbr")});var c=q.getDefaultUnitForView(this.tooltip.view);const d=m.defaultLengthUnit(c),k=m.defaultVerticalLengthUnit(c);c=m.defaultAreaUnit(c);return{length:b(d),relativeLength:b(d),verticalLength:b(k),relativeVerticalLength:b(k),area:b(c),orientation:b("degrees"),rotation:b("degrees")}}get _formatters(){return this._getFormatters(this._messagesUnits,this._displayUnits)}get fieldContext(){return{formatters:this._formatters,inputUnitInfos:this._inputUnitInfos,messages:this._messagesTooltip,onCommit:this._onCommit,
onDiscard:this._onDiscard}}initialize(){let a=new AbortController;this.addHandles([p.watch(()=>this.info.mode,b=>{this.tooltip.positionMode="input"===b?"fixed":"follow-cursor"}),p.on(()=>this.info,"focus",()=>{a?.abort();const {signal:b}=a=new AbortController;requestAnimationFrame(()=>{b.aborted||this._getFocusableInputs().at(0)?.focus()})})])}loadDependencies(){return z.loadCalciteComponents({button:()=>new Promise((a,b)=>l(["../../../../chunks/calcite-button"],a,b)),icon:()=>new Promise((a,b)=>
l(["../../../../chunks/calcite-icon"],a,b)),input:()=>new Promise((a,b)=>l(["../../../../chunks/calcite-input"],a,b))})}_getHelpMessage(a){const {info:b}=this,{tooltipOptions:c,helpMessage:d,viewType:k}=b;a=a??d;return c?.visibleElements?.helpMessage&&a?this._messagesTooltip?.sketch?.["3d"===k?"helpMessages3d":"helpMessages2d"]?.[a]:void 0}_exitInputMode(){this.info.exitInputMode();document.querySelector(".esri-view-surface").focus()}_getFocusableInputs(){return Array.from(this.domNode?.querySelectorAll("input:not([disabled])")??
[])}};f.__decorate([r.messageBundle("esri/core/t9n/Units"),g.property()],e.TooltipContent.prototype,"_messagesUnits",void 0);f.__decorate([r.messageBundle("esri/views/interactive/tooltip/t9n/Tooltip"),g.property()],e.TooltipContent.prototype,"_messagesTooltip",void 0);f.__decorate([g.property()],e.TooltipContent.prototype,"info",void 0);f.__decorate([g.property()],e.TooltipContent.prototype,"tooltip",void 0);f.__decorate([g.property()],e.TooltipContent.prototype,"_displayUnits",null);f.__decorate([g.property()],
e.TooltipContent.prototype,"_inputUnitInfos",null);f.__decorate([g.property()],e.TooltipContent.prototype,"_formatters",null);f.__decorate([g.property()],e.TooltipContent.prototype,"fieldContext",null);e.TooltipContent=f.__decorate([w.subclass("esri.views.interactive.tooltip.content.TooltipContent")],e.TooltipContent);Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});