// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../geometry ../../../Graphic ../../../symbols ../../../core/handleUtils ../../../core/screenUtils ../../../chunks/vec2 ../../../chunks/vec2f64 ../../../chunks/vec3f64 ../../../symbols/cim/enums ../../interactive/snapping/Settings ../../interactive/snapping/SnappingVisualizer ../../../geometry/Point ../../../geometry/Polyline ../../../symbols/CIMSymbol ../../../symbols/SimpleMarkerSymbol ../../../symbols/SimpleLineSymbol".split(" "),function(k,A,t,B,u,d,e,l,v,m,f,w,n,g,h,p,x){function y(a,
b){const c=[...b.toRgb(),255*b.a];switch(a){case "point":return new p({outline:{width:.5,color:[0,0,0,1]},size:10,color:b});case "intersectionPoint":return new p({outline:new x({width:1.5,color:b}),size:15,color:[0,0,0,0]});case "line":return new h({data:{type:"CIMSymbolReference",symbol:{type:"CIMLineSymbol",symbolLayers:[{type:"CIMSolidStroke",enable:!0,capStyle:m.LineCapStyle.Butt,joinStyle:m.LineJoinStyle.Round,miterLimit:10,width:d.px2pt(f.defaults.lineHintWidthTarget),color:c}]}}});case "parallelSign":return new h({data:{type:"CIMSymbolReference",
symbol:{type:"CIMLineSymbol",symbolLayers:[{type:"CIMVectorMarker",enable:!0,anchorPoint:{x:0,y:-1,z:0},anchorPointUnits:"Relative",size:5,markerPlacement:{type:"CIMMarkerPlacementOnLine",placePerPart:!0,angleToLine:!0,relativeTo:"LineMiddle"},frame:{xmin:-5,ymin:-1.5,xmax:5,ymax:1.5},markerGraphics:[{type:"CIMMarkerGraphic",geometry:{rings:[[[7,0],[-7,0],[-7,1.5],[7,1.5]]]},symbol:{type:"CIMPolygonSymbol",symbolLayers:[{type:"CIMSolidFill",enable:!0,color:c}]}}],scaleSymbolsProportionally:!0,respectFrame:!0},
{type:"CIMVectorMarker",enable:!0,anchorPoint:{x:0,y:1,z:0},anchorPointUnits:"Relative",size:5,markerPlacement:{type:"CIMMarkerPlacementOnLine",placePerPart:!0,angleToLine:!0,relativeTo:"LineMiddle"},frame:{xmin:-5,ymin:-1.5,xmax:5,ymax:1.5},markerGraphics:[{type:"CIMMarkerGraphic",geometry:{rings:[[[7,0],[-7,0],[-7,-1.5],[7,-1.5]]]},symbol:{type:"CIMPolygonSymbol",symbolLayers:[{type:"CIMSolidFill",enable:!0,color:c}]}}],scaleSymbolsProportionally:!0,respectFrame:!0}]}}});case "rightAngleQuad45":case "rightAngleQuad225":return a=
"rightAngleQuad45"===a?45:225,new h({data:{type:"CIMSymbolReference",symbol:{type:"CIMLineSymbol",symbolLayers:[{type:"CIMVectorMarker",enable:!0,anchorPoint:{x:.5,y:.5,z:0},anchorPointUnits:"Relative",size:d.px2pt(f.defaults.rightAngleHintSize),rotation:a,markerPlacement:{type:"CIMMarkerPlacementOnVertices",placePerPart:!0,angleToLine:!0,placeOnEndPoints:!1},frame:{xmin:-5,ymin:-5,xmax:5,ymax:5},markerGraphics:[{type:"CIMMarkerGraphic",geometry:{paths:[[[5,-5],[-5,-5],[-5,5],[5,5],[5,-5]]]},symbol:{type:"CIMLineSymbol",
symbolLayers:[{type:"CIMSolidStroke",enable:!0,capStyle:"Butt",joinStyle:"Round",miterLimit:10,width:d.px2pt(f.defaults.rightAngleHintOutlineSize),color:c},{type:"CIMSolidFill",enable:!0,color:[...b.toRgb(),102*b.a]}]}}],scaleSymbolsProportionally:!0,respectFrame:!0}]}}})}}class z extends w.SnappingVisualizer{constructor(a){super();this._graphicsLayer=a;this._symbolPairingsByType=new Map}visualizeIntersectionPoint(a,b){return this._visualizeSnappingIndicator(new n({x:a.intersectionPoint[0],y:a.intersectionPoint[1],
spatialReference:b.spatialReference}),this._getOrCreateSymbol("intersectionPoint",b.view.effectiveTheme.accentColor))}visualizePoint(a,b){return this._visualizeSnappingIndicator(new n({x:a.point[0],y:a.point[1],spatialReference:b.spatialReference}),this._getOrCreateSymbol("point",b.view.effectiveTheme.accentColor))}visualizeLine(a,b){return this._visualizeSnappingIndicator(new g({paths:[[a.lineStart,a.lineEnd]],spatialReference:b.spatialReference}),this._getOrCreateSymbol("line",b.view.effectiveTheme.accentColor))}visualizeParallelSign(a,
b){return this._visualizeSnappingIndicator(new g({paths:[[a.lineStart,a.lineEnd]],spatialReference:b.spatialReference}),this._getOrCreateSymbol("parallelSign",b.view.effectiveTheme.accentColor))}visualizeRightAngleQuad(a,b){var c=l.create();const q=l.create(),r=v.create();e.subtract(c,a.centerVertex,a.previousVertex);e.subtract(q,a.nextVertex,a.previousVertex);e.cross(r,c,q);c=`rightAngleQuad${0>r[2]?45:225}`;return this._visualizeSnappingIndicator(new g({paths:[[a.previousVertex,a.centerVertex,a.nextVertex]],
spatialReference:b.spatialReference}),this._getOrCreateSymbol(c,b.view.effectiveTheme.accentColor))}_visualizeSnappingIndicator(a,b){const c=new t({geometry:a,symbol:b});this._graphicsLayer.add(c);return u.makeHandle(()=>{this._graphicsLayer.remove(c)})}_getOrCreateSymbol(a,b){const c=this._symbolPairingsByType;c.get(a)?.color!==b&&c.set(a,{color:b,symbol:y(a,b)});return c.get(a).symbol}}k.SnappingVisualizer2D=z;Object.defineProperty(k,Symbol.toStringTag,{value:"Module"})});