// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define(["../../../../core/has","./FreeList","./Utils"],function(v,q,r){const p=["FILL","LINE","MARKER","TEXT","LABEL"];class t{constructor(a,b,g,c){this._strides=a;this._displayList=b;this._freeListsAndStorage={};this._dirtyMap=null;this._dirtyMap=g;for(const e in a){this._freeListsAndStorage[e]={vtxFreeList:c?new q.FreeList(c):null,idxFreeList:c?new q.FreeList(c):null,vertexBuffers:{},indexBuffer:c?new Uint32Array(c):null};for(const f in a[e])this._freeListsAndStorage[e].vertexBuffers[f]={data:c?
r.allocateTypedArrayBuffer(c,a[e][f]):null,stride:a[e][f]}}}static fromTileData(a,b){var g=a.getStrides(),c={};for(var e=0;e<g.length;e++)c[p[e]]=g[e];g=[0,0,0,0,0];e=[0,0,0,0,0];for(var f of a.tileDisplayData.displayObjects)for(var d of f.displayRecords)g[d.geometryType]=Math.max(g[d.geometryType],d.vertexFrom+d.vertexCount),e[d.geometryType]=Math.max(e[d.geometryType],d.indexFrom+d.indexCount);b=new t(c,a.tileDisplayData.displayList,b,void 0);a=a.tileBufferData?.geometries??[];for(c=0;c<a.length;++c){f=
g[c];var h=e[c],l=a[c];d=b._storageFor(p[c]);var m=a[c].indexBuffer;d.indexBuffer=m;d.idxFreeList=new q.FreeList(m.length);d.idxFreeList.allocate(h);h=0;for(const k in l.vertexBuffer)l=a[c].vertexBuffer[k],d.vertexBuffers[k].data=l.data,d.vertexBuffers[k].stride=l.stride,m=r.strideToPackingFactor(l.stride),l=l.data.length*m/l.stride,h||(h=l);d.vtxFreeList=new q.FreeList(h);d.vtxFreeList.allocate(f)}return b}delete(a){const b=p[a.geometryType];this._freeVertices(b,a.vertexFrom,a.vertexCount);this._freeIndices(b,
a.indexFrom,a.indexCount);this._displayList.removeFromList(a);a.vertexFrom=void 0;a.indexFrom=void 0}setMeshData(a,b,g,c,e){const f=p[a.geometryType];a.meshData=null;let d=void 0,h=void 0;void 0===a.vertexFrom?(h=b.vertexCount,d=this._allocateVertices(f,h)):b.vertexCount>a.vertexCount?(this._freeVertices(f,a.vertexFrom,a.vertexCount),h=b.vertexCount,d=this._allocateVertices(f,h)):b.vertexCount===a.vertexCount?(d=a.vertexFrom,h=a.vertexCount):(this._freeVertices(f,a.vertexFrom+b.vertexCount,a.vertexCount-
b.vertexCount),d=a.vertexFrom,h=b.vertexCount);let l=!0,m=void 0,k=void 0,n=void 0;void 0===a.indexFrom?(m=e,n=b.indexCount,k=this._allocateIndices(f,n)):b.indexCount>a.indexCount?(m=this._displayList.removeFromList(a),this._freeIndices(f,a.indexFrom,a.indexCount),n=b.indexCount,k=this._allocateIndices(f,n)):b.indexCount===a.indexCount?(l=!1,k=a.indexFrom,n=a.indexCount):(m=this._displayList.removeFromList(a),this._freeIndices(f,a.indexFrom+b.indexCount,a.indexCount-b.indexCount),k=a.indexFrom,n=
b.indexCount);if(-1!==d&&-1!==k){e=this._storageFor(f);r.copyMeshData(d,k,e.vertexBuffers,e.indexBuffer,b,g,c);a.vertexFrom=d;a.indexFrom=k;a.vertexCount=b.vertexCount;a.indexCount=b.indexCount;if(this._dirtyMap){this._dirtyMap.markDirtyIndices(a.geometryType,a.indexFrom,a.indexCount);for(const u in g)this._dirtyMap.markDirtyVertices(a.geometryType,u,a.vertexFrom,a.vertexCount)}l&&this._displayList.addToList(a,m);return!0}-1!==d&&this._freeVertices(f,d,h);-1!==k&&this._freeIndices(f,k,n);a.setMeshDataFromBuffers(b,
g,c);a.vertexFrom=void 0;a.vertexCount=0;a.indexFrom=void 0;a.indexCount=0;return!1}tryAddMeshData(a,b){const g=b.vertexBuffer;b=b.indexBuffer;var c=p[a.geometryType];const e=this._allocateVertices(c,a.vertexCount);if(-1===e)return this._freeVertices(c,e,a.vertexCount),!1;const f=this._allocateIndices(c,a.indexCount);if(-1===f)return this._freeVertices(c,e,a.vertexCount),this._freeIndices(c,f,a.indexCount),!1;c=this._storageFor(c);r.copyMeshData(e,f,c.vertexBuffers,c.indexBuffer,a,g,b);a.vertexFrom=
e;a.indexFrom=f;if(this._dirtyMap){this._dirtyMap.markDirtyIndices(a.geometryType,a.indexFrom,a.indexCount);for(const d in g)this._dirtyMap.markDirtyVertices(a.geometryType,d,e,a.vertexCount)}this._displayList.addToList(a);return!0}_allocateVertices(a,b){a=this._storageFor(a);b=a.vtxFreeList?.allocate(b);if(null==b||-1===b)return-1;a=a.vtxFreeList?.fragmentation;return null==a||.5<a?-1:b}_freeVertices(a,b,g){this._storageFor(a).vtxFreeList?.free(b,g)}_freeIndices(a,b,g){this._storageFor(a).idxFreeList?.free(b,
g)}_allocateIndices(a,b){a=this._storageFor(a);b=a.idxFreeList?.allocate(b);if(null==b||-1===b)return-1;a=a.idxFreeList?.fragmentation;return null==a||.5<a?-1:b}_storageFor(a){return this._freeListsAndStorage[a]}_stridesFor(a,b){return this._strides[a][b]}}return t});