// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../../../../core/Error ../../../../core/has ./definitions ./GeometryUtils ./Rect ./RectangleBinPack ../../../webgl/enums ../../../webgl/Texture ../../../webgl/TextureDescriptor".split(" "),function(x,r,l,t,u,v,y,z,A){function m(a){return a&&"static"===a.type}class w{constructor(a,b,c=0){this._mosaicPages=[];this._pageHeight=this._pageWidth=this._currentPage=this._maxItemSize=0;this._mosaicRects=new Map;this._spriteCopyQueue=[];this.pixelRatio=1;(0>=a||0>=b)&&console.error("Sprites mosaic defaultWidth and defaultHeight must be greater than zero!");
this._pageWidth=a;this._pageHeight=b;0<c&&(this._maxItemSize=c);this.pixelRatio=window.devicePixelRatio||1;this._binPack=new v(this._pageWidth,this._pageHeight);this._mosaicPages.push({mosaicsData:{type:"static",data:new Uint32Array(Math.floor(this._pageWidth)*Math.floor(this._pageHeight))},size:[this._pageWidth,this._pageHeight],dirty:!0,texture:void 0})}getWidth(a){return a>=this._mosaicPages.length?-1:this._mosaicPages[a].size[0]}getHeight(a){return a>=this._mosaicPages.length?-1:this._mosaicPages[a].size[1]}getPageTexture(a){return a<
this._mosaicPages.length?this._mosaicPages[a].texture:null}has(a){return this._mosaicRects.has(a)}get itemCount(){return this._mosaicRects.size}getSpriteItem(a){return this._mosaicRects.get(a)}addSpriteItem(a,b,c,d,f,g,e=1){if(this._mosaicRects.has(a))return this._mosaicRects.get(a);let h,k,n;m(c)?[h,k,n]=this._allocateImage(b[0],b[1]):(h=new u(0,0,b[0],b[1]),k=this._mosaicPages.length,this._mosaicPages.push({mosaicsData:c,size:[b[0]+2*l.spritePadding,b[1]+2*l.spritePadding],dirty:!0,texture:void 0}));
if(0>=h.width||0>=h.height)return null;g={rect:h,width:b[0],height:b[1],sdf:f,simplePattern:g,pixelRatio:e,page:k};this._mosaicRects.set(a,g);m(c)&&(r("esri-mosaic-debug")&&this._showDebugSprite(b,c.data),this._copy({rect:h,spriteSize:b,spriteData:c.data,page:k,pageSize:n,repeat:d,sdf:f}));return g}hasItemsToProcess(){return 0!==this._spriteCopyQueue.length}processNextItem(){const a=this._spriteCopyQueue.pop();a&&this._copy(a)}getSpriteItems(a){const b={};for(const c of a)b[c]=this.getSpriteItem(c);
return b}getMosaicItemPosition(a){a=this.getSpriteItem(a);const b=a?.rect;if(!b)return null;b.width=a.width;b.height=a.height;const c=l.spritePadding,d=this._mosaicPages[a.page].size;return{size:[a.width,a.height],tl:[(b.x+c)/d[0],(b.y+c)/d[1]],br:[(b.x+c+a.width)/d[0],(b.y+c+a.height)/d[1]],page:a.page}}bind(a,b,c=0,d=0){const f=this._mosaicPages[c],g=f.mosaicsData;var e=f.texture;if(!e){e=f.size;const h=new A.TextureDescriptor;h.width=e[0];h.height=e[1];h.wrapMode=y.TextureWrapMode.CLAMP_TO_EDGE;
e=new z.Texture(a,h,null);f.texture=e}e.setSamplingMode(b);m(g)?(a.bindTexture(e,d),f.dirty&&(e.setData(new Uint8Array(g.data.buffer)),e.generateMipmap(),r("esri-mosaic-debug")&&this._showDebugPage(c))):(g.data.bindFrame(a,e,d),e.generateMipmap());f.dirty=!1}dispose(){this._binPack=null;for(const b of this._mosaicPages){var a=b.texture;a&&a.dispose();a=b.mosaicsData;m(a)||a.data.destroy()}this._mosaicPages=null;this._mosaicRects.clear()}static _copyBits(a,b,c,d,f,g,e,h,k,n,p){let q=d*b+c;e=h*g+e;
if(p)for(e-=g,p=-1;p<=n;p++,q=((p+n)%n+d)*b+c,e+=g)for(h=-1;h<=k;h++)f[e+h]=a[q+(h+k)%k];else for(c=0;c<n;c++){for(d=0;d<k;d++)f[e+d]=a[q+d];q+=b;e+=g}}_copy(a){if(!(a.page>=this._mosaicPages.length)){var b=this._mosaicPages[a.page],c=b.mosaicsData;if(!m(b.mosaicsData))throw new x("mapview-invalid-resource","unsuitable data type!");var d=a.spriteData;(c=c.data)&&d||console.error("Source or target images are uninitialized!");w._copyBits(d,a.spriteSize[0],0,0,c,a.pageSize[0],a.rect.x+l.spritePadding,
a.rect.y+l.spritePadding,a.spriteSize[0],a.spriteSize[1],a.repeat);b.dirty=!0}}_allocateImage(a,b){a+=2*l.spritePadding;b+=2*l.spritePadding;var c=Math.max(a,b);if(this._maxItemSize&&this._maxItemSize<c){c=2**Math.ceil(t.log2(a));const d=2**Math.ceil(t.log2(b));a=new u(0,0,a,b);this._mosaicPages.push({mosaicsData:{type:"static",data:new Uint32Array(c*d)},size:[c,d],dirty:!0,texture:void 0});return[a,this._mosaicPages.length-1,[c,d]]}c=this._binPack.allocate(a,b);return 0>=c.width?(c=this._mosaicPages[this._currentPage],
!c.dirty&&m(c.mosaicsData)&&(c.mosaicsData.data=null),this._currentPage=this._mosaicPages.length,this._mosaicPages.push({mosaicsData:{type:"static",data:new Uint32Array(this._pageWidth*this._pageHeight)},size:[this._pageWidth,this._pageHeight],dirty:!0,texture:void 0}),this._binPack=new v(this._pageWidth,this._pageHeight),this._allocateImage(a,b)):[c,this._currentPage,[this._pageWidth,this._pageHeight]]}_showDebugSprite([a,b],c){const d=document.createElement("canvas");d.width=a;d.height=b;d.setAttribute("style",
`position: absolute; top: ${4+204*B++}px; right: 208px; width: 200px; height: 200px; border: 1px solid black;`);const f=d.getContext("2d");a=new ImageData(a,b);a.data.set(new Uint8Array(c.buffer));f.putImageData(a,0,0);document.body.appendChild(d)}_showDebugPage(a){const {size:[b,c],mosaicsData:d}=this._mosaicPages[a];if(m(d)){var f=`mosaicDebugPage${a}`,g=document.getElementById(f)??document.createElement("canvas");g.id=f;g.width=b;g.height=c;g.setAttribute("style",`position: absolute; top: ${4+
204*a}px; right: 4px; width: 200px; height: 200px; border: 1px solid black;`);a=g.getContext("2d");f=new ImageData(b,c);f.data.set(new Uint8Array(d.data.buffer));a.putImageData(f,0,0);document.body.appendChild(g)}else console.error("Could not show sprite mosaic debug for non-static resource")}}let B=0;return w});