// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../../core/Error ../../../../../core/Logger ../../../../../core/maybe ../../../../../core/pbf ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/OptimizedFeature ../../../../../layers/graphics/OptimizedGeometry ./FeatureSetReader ./FeatureSetReaderPBFHeader".split(" "),function(D,K,L,E,M,F,N,v,G,O){function H(a){if(a<=r.small.delta.length)return r.small;if(a<=r.large.delta.length)return r.large;r.large.delta=new Int32Array(Math.round(1.25*
a));r.large.decoded=new Int32Array(Math.round(1.25*a));return r.large}function P(a){var b=a.getLength();for(b=a.pos()+b;a.pos()<b&&a.next();)switch(a.tag()){case 1:return a.getString();case 2:return a.getFloat();case 3:return a.getDouble();case 4:return a.getSInt32();case 5:return a.getUInt32();case 6:return a.getInt64();case 7:return a.getUInt64();case 8:return a.getSInt64();case 9:return a.getBool();default:return a.skip(),null}return null}function B(a,b,e,f){return 0===a*f-e*b&&0<a*e+b*f}const r=
{small:{delta:new Int32Array(128),decoded:new Int32Array(128)},large:{delta:new Int32Array(128E3),decoded:new Int32Array(128E3)}};class C extends G.FeatureSetReader{static fromBuffer(a,b,e=!1){var f=b.geometryType;a:{try{const c=new M(new Uint8Array(a),new DataView(a));for(;c.next();)switch(c.tag()){case 2:b:{for(var g=c.getMessage();g.next();)switch(g.tag()){case 1:var d=g.getMessage();break b;default:g.skip()}d=null}break a;default:c.skip()}}catch(c){a=new K("query:parsing-pbf","Error while parsing FeatureSet PBF payload",
{error:c}),L.getLogger("esri.view.2d.layers.features.support.FeatureSetReaderPBF").error(a)}d=null}a=d;e=O.parseHeader(a,"esriGeometryPoint"===f,e);f=G.FeatureSetReader.createInstance();return new C(f,a,e,b)}constructor(a,b,e,f){super(a,f);this._isPoints=this._hasNext=!1;this._featureIndex=-1;this._featureOffset=0;this._cache={area:0,unquantGeometry:void 0,geometry:void 0,centroid:void 0,legacyFeature:void 0,optFeature:void 0};this._geometryType=f.geometryType;this._reader=b;this._header=e;this._hasNext=
e.hasFeatures;this._isPoints="esriGeometryPoint"===f.geometryType}get fields(){return this._header.fields}get geometryType(){return this._geometryType}get _size(){return this._header.featureCount}get hasZ(){return!1}get hasM(){return!1}get stride(){return 2+(this.hasZ?1:0)+(this.hasM?1:0)}get hasFeatures(){return this._header.hasFeatures}get hasNext(){return this._hasNext}get exceededTransferLimit(){return this._header.exceededTransferLimit}getSize(){return this._size}getQuantizationTransform(){return this._header.transform}getCursor(){return this.copy()}getIndex(){return this._featureIndex}setIndex(a){this._cache.area=
0;this._cache.unquantGeometry=void 0;this._cache.geometry=void 0;this._cache.centroid=void 0;this._cache.legacyFeature=void 0;this._cache.optFeature=void 0;this._featureIndex=a}getAttributeHash(){let a="";for(const b of this._header.fields.fields)a+=this._readAttributeAtIndex(b.index)+".";return a}getObjectId(){return this._readAttributeAtIndex(this._header.objectIdFieldIndex)}getDisplayId(){return this._header.displayIds[this._featureIndex]}setDisplayId(a){this._header.displayIds[this._featureIndex]=
a}getGroupId(){return this._header.groupIds[this._featureIndex]}setGroupId(a){this._header.groupIds[this._featureIndex]=a}readLegacyFeature(){if(void 0===this._cache.legacyFeature){var a=this.readCentroid();a={attributes:this.readAttributes(),geometry:this._isPoints?this.readLegacyPointGeometry():this.readLegacyGeometry(),centroid:(a&&{x:a.coords[0],y:a.coords[1]})??null};return this._cache.legacyFeature=a}return this._cache.legacyFeature}readOptimizedFeature(){if(void 0===this._cache.optFeature){const a=
new N.OptimizedFeature(this.readGeometry(),this.readAttributes(),this.readCentroid());a.objectId=this.getObjectId();a.displayId=this.getDisplayId();return this._cache.optFeature=a}return this._cache.optFeature}getXHydrated(){const a=this._header.centroid[2*this._featureIndex],b=this.getQuantizationTransform();return null==b?a:a*b.scale[0]+b.translate[0]}getYHydrated(){const a=this._header.centroid[2*this._featureIndex+1],b=this.getQuantizationTransform();return null==b?a:b.translate[1]-a*b.scale[1]}getX(){return this._header.centroid[2*
this._featureIndex]*this._sx+this._tx}getY(){return this._header.centroid[2*this._featureIndex+1]*this._sy+this._ty}readLegacyPointGeometry(){const a=this.getX(),b=this.getY();return{x:a,y:b}}readLegacyGeometry(a){a=this.readUnquantizedGeometry(a);return F.convertToGeometry(a,this.geometryType,!1,!1)}readLegacyCentroid(){const a=this.readCentroid();if(!a)return null;const [b,e]=a.coords;return{x:b,y:e}}readGeometryArea(){this._cache.area||this.readGeometry(!0);return this._cache.area}readUnquantizedGeometry(a=
!1){if(void 0===this._cache.unquantGeometry){a=this.readGeometry(a);if(!a)return this._cache.unquantGeometry=void 0,null;var b=H(a.coords.length).decoded;a=a.clone(b);b=a.coords;let e=0;for(const f of a.lengths){for(let g=1;g<f;g++){const d=2*(e+g),c=2*(e+g-1);b[d]+=b[c];b[d+1]+=b[c+1]}e+=f}return this._cache.unquantGeometry=a}return this._cache.unquantGeometry}readHydratedGeometry(){if(this._isPoints){if(268435455===this._header.centroid[2*this._featureIndex])return null;var a=this.getXHydrated(),
b=this.getYHydrated();return new v([],[a,b])}a=this.readGeometry();if(!a)return null;a=a.clone();b=this.getQuantizationTransform();null!=b&&F.unquantizeOptimizedGeometry(a,a,this.hasZ,this.hasM,b);return a}readGeometry(a=!1){if(void 0===this._cache.geometry){var b=null;if(this._isPoints){if(268435455===this._header.centroid[2*this._featureIndex])return null;a=this.getX();b=this.getY();b=new v([],[a,b])}else{const e=this._header.offsets.geometry[this._featureIndex],f=this._reader;if(0===e){a=this._readServerCentroid();
if(!a)return null;const [g,d]=a.coords;return this.createQuantizedExtrudedGeometry(g,d)}f.move(e);try{if(b=a?this._parseGeometryForDisplay(f):this._parseGeometry(f),!b){const g=this._readServerCentroid();if(!g)return null;const [d,c]=g.coords;return this.createQuantizedExtrudedGeometry(d,c)}}catch(g){return console.error("Failed to parse geometry!",g),null}}return this._cache.geometry=b}return this._cache.geometry}readCentroid(){if(void 0===this._cache.centroid){let a=void 0;(a=this._computeCentroid())||
(a=this._readServerCentroid());this._cache.centroid=a??void 0;return a??null}return this._cache.centroid}copy(){var a=this._reader.clone();a=new C(this.instance,a,this._header,this.fullSchema());this.copyInto(a);return a}next(){this._cache.area=0;this._cache.unquantGeometry=void 0;this._cache.geometry=void 0;this._cache.centroid=void 0;this._cache.legacyFeature=void 0;for(this._cache.optFeature=void 0;++this._featureIndex<this._size&&!this._getExists(););return this._featureIndex<this._size}_readAttribute(a,
b){const e=this._header.fields.get(a);if(null!=e){var f=this._readAttributeAtIndex(e.index);"esriFieldTypeTimestampOffset"===this.fields.get(a)?.type&&(f=this.parseTimestampOffset(f));a=this._header.fields.isDateField(e.name);return b&&null!=f?a?new Date(f):f:f}}_readAttributes(){const a={};for(const b of this._header.fields.fields)a[b.name]=this._readAttributeAtIndex(b.index);return a}copyInto(a){super.copyInto(a);a._featureIndex=this._featureIndex;a._featureOffset=this._featureOffset;a._hasNext=
this._hasNext}_readAttributeAtIndex(a){const b=this._reader;b.move(this._header.offsets.attributes[this._featureIndex*this._header.fieldCount+a]);return P(b)}_readServerCentroid(){const a=this._header.centroid[2*this._featureIndex]+this._tx;return 268435455===a?null:new v([],[a,this._header.centroid[2*this._featureIndex+1]+this._ty])}_parseGeometry(a){a=a.asUnsafe();var b=a.getLength();b=a.pos()+b;const e=[],f=[];for(;a.pos()<b&&a.next();)switch(a.tag()){case 2:var g=a.getUInt32();for(g=a.pos()+g;a.pos()<
g;)f.push(a.getUInt32());break;case 3:g=a.getUInt32();g=a.pos()+g;e.push(a.getSInt32()+this._tx);e.push(a.getSInt32()+this._ty);this.hasZ&&a.getSInt32();for(this.hasM&&a.getSInt32();a.pos()<g;)e.push(a.getSInt32()),e.push(a.getSInt32()),this.hasZ&&a.getSInt32(),this.hasM&&a.getSInt32();break;default:a.skip()}return e.length?new v(f,e):null}_parseGeometryForDisplay(a){a=a.asUnsafe();var b=a.getLength();const e=a.pos()+b,f=[];b=[];let g=0,d=0;var c=null;let z=0;const Q="esriGeometryPolygon"===this.geometryType;
for(;a.pos()<e&&a.next();)switch(a.tag()){case 2:c=a.getUInt32();for(c=a.pos()+c;a.pos()<c;){var A=a.getUInt32();f.push(A);g+=A}c=H(2*g).delta;break;case 3:a.getUInt32();A=2+(this.hasZ?1:0)+(this.hasM?1:0);E.assertIsSome(c);for(var n of f)if(d+A*n>c.length)for(var q=0;q<n;q++)a.getSInt32(),a.getSInt32(),this.hasZ&&a.getSInt32(),this.hasM&&a.getSInt32();else if(Q){q=this.getAreaSimplificationThreshold(n,this._header.vertexCount);var t=2,p=1,m=a.getSInt32(),k=a.getSInt32();c[d++]=m;c[d++]=k;this.hasZ&&
a.getSInt32();this.hasM&&a.getSInt32();var h=a.getSInt32(),l=a.getSInt32();this.hasZ&&a.getSInt32();for(this.hasM&&a.getSInt32();t<n;){var u=a.getSInt32();let w=a.getSInt32();this.hasZ&&a.getSInt32();this.hasM&&a.getSInt32();const x=m+h,y=k+l,I=x+u,J=y+w;.5*Math.abs(m*y+x*J+I*k-m*J-x*k-I*y)>=q?(z+=-.5*(x-m)*(y+k),1<p&&B(c[d-2],c[d-1],h,l)?(c[d-2]+=h,c[d-1]+=l):(c[d++]=h,c[d++]=l,p++),m=x,k=y):(u+=h,w+=l);h=u;l=w;t++}3>p?d-=2*p:(z+=-.5*(m+h-m)*(k+l+k),B(c[d-2],c[d-1],h,l)?(c[d-2]+=h,c[d-1]+=l,b.push(p)):
(c[d++]=h,c[d++]=l,b.push(++p)))}else{q=0;t=a.getSInt32();p=a.getSInt32();this.hasZ&&a.getSInt32();this.hasM&&a.getSInt32();c[d++]=t;c[d++]=p;q+=1;for(m=1;m<n;m++)k=a.getSInt32(),h=a.getSInt32(),l=t+k,u=p+h,z+=-.5*(l-t)*(u+p),this.hasZ&&a.getSInt32(),this.hasM&&a.getSInt32(),2<m&&B(c[d-2],c[d-1],k,h)?(c[d-2]+=k,c[d-1]+=h):(c[d++]=k,c[d++]=h,q+=1),t=l,p=u;b.push(q)}break;default:a.skip()}this._cache.area=z;if(!b.length)return null;if(this._tx||this._ty){n=0;E.assertIsSome(c);for(const w of b)c[2*n]+=
this._tx,c[2*n+1]+=this._ty,n+=w}return new v(b,c)}}D.FeatureSetReaderPBF=C;Object.defineProperty(D,Symbol.toStringTag,{value:"Module"})});