// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/promiseUtils ../../../layers/support/fieldUtils ../../../layers/support/layerUtils ../../../renderers/support/clickToleranceUtils ../../../views/support/drapedUtils ../../../views/support/layerViewUtils".split(" "),function(B,h,q,C,t,D,E,F){async function v(){return new Promise((b,a)=>B(["../../../geometry/geometryEngineJSON"],b,a))}async function w(){return v().then(({contains:b,intersects:a,overlaps:e,simplify:d})=>({contains:b,intersects:a,overlaps:e,simplify:d}))}
function G(b){const a=[],e=[],d=[];b.forEach(c=>{t.isFeatureLayer(c)?a.push(c):t.isKnowledgeGraphLayer(c)&&c.layers?.length?a.push(...c.layers.toArray()):t.isMapNotesLayer(c)&&c.sublayers?.length?d.push(...c.sublayers.toArray()):t.isGraphicsLayer(c)?d.push(c):F.isSelectableLayerView2D(c)&&e.push(c)});return{layers:a,layerViews:e,graphicsLayers:d}}function x(b,a){const e=b.includes(a),d=a.getObjectId(),c=null!=d;b=b.some(f=>{const g=a.layer===f.layer,l=c&&f.getObjectId()===d;f=a.uid===f.uid;return g&&
(l||f)});return!e&&!b}async function y(b){const {layerViews:a,selector:e,signal:d,view:c}=b;return q.whenOrAbort(Promise.allSettled(a.map(async f=>{const g=f.createQuery(),{outFields:l,geometry:m}=u(e,f.layer,c);g.outFields=l;g.geometry=m;g.returnGeometry=!0;g.outSpatialReference=c.spatialReference;return f.queryFeatures(g,{signal:d}).then(({features:n})=>n)})),d)}async function z(b){const {layers:a,selector:e,signal:d,view:c}=b;return q.whenOrAbort(Promise.allSettled(a.map(async f=>f.queryFeatures(H(f.createQuery(),
e,f,c),{signal:d}).then(({features:g})=>g))),d)}function u(b,a,e){const d=C.getDisplayFieldName({displayField:"displayField"in a?a.displayField:null,fields:a.fields}),c=[a.objectIdField];null!=d&&a.fieldsIndex.has(d)&&c.push(d);a="renderer"in a?D.calculateTolerance({renderer:a.renderer}):0;return{geometry:"point"===b.type?E.createQueryGeometry(b,a,e):b,outFields:c}}function H(b,a,e,d){const {outFields:c,geometry:f}=u(a,e,d);b.outFields=c;b.geometry=f;b.returnGeometry=!0;b.outSpatialReference=d.spatialReference;
return b}async function A(b){const {selector:a,candidates:e,options:d,view:c}=b;if(!e?.length||!a||!d)return[];const {overlaps:f,intersects:g,contains:l}=d,{spatialReference:m}=c,n=await w();return e.filter(p=>{var k=p.geometry;p=f&&n.overlaps(m,a,k);const r=g&&n.intersects(m,a,k);k=l&&n.contains(m,a,k);return p||r||k})}const I=async(b,a,e,d)=>{a=a.flatMap(c=>c.graphics.toArray())??[];return A({candidates:a,selector:b,options:e,view:d})},J=async(b,a,e,d)=>(b=await q.ignoreAbortErrors(z({selector:b,
signal:d,layers:a,view:e})))?b.filter(c=>"fulfilled"===c.status).flatMap(c=>c.value):[],K=async(b,a,e,d)=>(b=await q.ignoreAbortErrors(y({selector:b,signal:d,layerViews:a,view:e})))?b.filter(c=>"fulfilled"===c.status).flatMap(c=>c.value):[];h.getGeometryEngineOperations=w;h.getQueryOptionsFromLayer=u;h.getSelectionFromFeatureLayerViews=y;h.getSelectionFromFeatureLayers=z;h.getSelectionFromGeometry=async function(b){const {currentSelection:a,options:e,selector:d,signal:c,sources:f,view:g}=b;if(!f?.length)return{added:[],
removed:[]};const {layers:l,layerViews:m,graphicsLayers:n}=G(f),p=(await q.whenOrAbort(Promise.all([J(d,l,g,c),K(d,m,g,c),I(d,n,e,g)]),c)).flat();if(!a)return{added:p,removed:[]};b=p.filter(r=>x(a.toArray(),r));const k=a.filter(r=>x(p,r)).toArray();a.removeMany(k);a.addMany(b);return{added:b,removed:k}};h.getSelectionFromGeometryEngine=A;h.importGeometryEngine=v;Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});