/*
All material copyright ESRI, All Rights Reserved, unless otherwise specified.
See https://js.arcgis.com/4.28/esri/copyright.txt for details.
*/
import{i as e,q as t,b as n}from"./dom.js";
/*!
 * All material copyright ESRI, All Rights Reserved, unless otherwise specified.
 * See https://github.com/Esri/calcite-design-system/blob/main/LICENSE.md for details.
 * v1.9.2
 */const l="calciteInternalLabelClick",s="calciteInternalLabelConnected",a="calciteInternalLabelDisconnected",i="calcite-label",o=new WeakMap,c=new WeakMap,r=new WeakMap,d=new WeakMap,u=new WeakSet,b=e=>{const{id:l}=e,s=l&&t(e,{selector:`${i}[for="${l}"]`});if(s)return s;const a=n(e,i);return!a||function(e,t){let n;const l="custom-element-ancestor-check",s=l=>{l.stopImmediatePropagation();const s=l.composedPath();n=s.slice(s.indexOf(t),s.indexOf(e))};return e.addEventListener(l,s,{once:!0}),t.dispatchEvent(new CustomEvent(l,{composed:!0,bubbles:!0})),e.removeEventListener(l,s),n.filter((n=>n!==t&&n!==e)).filter((e=>e.tagName?.includes("-"))).length>0}(a,e)?null:a};function E(e){const t=b(e.el);if(c.has(t)&&t===e.labelEl||!t&&u.has(e))return;const n=L.bind(e);if(t){e.labelEl=t;const i=o.get(t)||[];i.push(e),o.set(t,i.sort(f)),c.has(e.labelEl)||(c.set(e.labelEl,h),e.labelEl.addEventListener(l,h)),u.delete(e),document.removeEventListener(s,r.get(e)),d.set(e,n),document.addEventListener(a,n)}else u.has(e)||(n(),document.removeEventListener(a,d.get(e)))}function m(e){if(u.delete(e),document.removeEventListener(s,r.get(e)),document.removeEventListener(a,d.get(e)),r.delete(e),d.delete(e),!e.labelEl)return;const t=o.get(e.labelEl);1===t.length&&(e.labelEl.removeEventListener(l,c.get(e.labelEl)),c.delete(e.labelEl)),o.set(e.labelEl,t.filter((t=>t!==e)).sort(f)),e.labelEl=null}function f(t,n){return e(t.el,n.el)?-1:1}function v(e){return e.label||e.labelEl?.textContent?.trim()||""}function h(e){const t=e.detail.sourceEvent.target,n=o.get(this),l=n.find((e=>e.el===t));if(n.includes(l))return;const s=n[0];s.disabled||s.onLabelClick(e)}function g(){u.has(this)&&E(this)}function L(){u.add(this);const e=r.get(this)||g.bind(this);r.set(this,e),document.addEventListener(s,e)}export{a,E as c,m as d,v as g,s as l};
