/*
All material copyright ESRI, All Rights Reserved, unless otherwise specified.
See https://js.arcgis.com/4.28/esri/copyright.txt for details.
*/
import{d as e}from"./calcite-input-time-picker.js";import"./index.js";import"./form.js";import"./dom.js";import"./guid.js";import"./interactive.js";import"./key.js";import"./label2.js";import"./loadable.js";import"./locale2.js";import"./observers.js";import"./Heading2.js";import"./t9n.js";import"./math.js";import"./icon.js";import"./openCloseComponent.js";import"./action.js";import"./loader.js";import"./input.js";import"./progress.js";import"./popover2.js";import"./floating-ui.js";import"./debounce.js";import"./FloatingArrow.js";
/*!
 * All material copyright ESRI, All Rights Reserved, unless otherwise specified.
 * See https://github.com/Esri/calcite-design-system/blob/main/LICENSE.md for details.
 * v1.9.2
 */
function t(e){return e%100==2}function r(e){return e%100==3||e%100==4}function m(e,m,i,n){var s=e+" ";switch(i){case"s":return m||n?"nekaj sekund":"nekaj sekundami";case"m":return m?"ena minuta":"eno minuto";case"mm":return t(e)?s+(m||n?"minuti":"minutama"):r(e)?s+(m||n?"minute":"minutami"):s+(m||n?"minut":"minutami");case"h":return m?"ena ura":"eno uro";case"hh":return t(e)?s+(m||n?"uri":"urama"):r(e)?s+(m||n?"ure":"urami"):s+(m||n?"ur":"urami");case"d":return m||n?"en dan":"enim dnem";case"dd":return t(e)?s+(m||n?"dneva":"dnevoma"):s+(m||n?"dni":"dnevi");case"M":return m||n?"en mesec":"enim mesecem";case"MM":return t(e)?s+(m||n?"meseca":"mesecema"):r(e)?s+(m||n?"mesece":"meseci"):s+(m||n?"mesecev":"meseci");case"y":return m||n?"eno leto":"enim letom";case"yy":return t(e)?s+(m||n?"leti":"letoma"):r(e)?s+(m||n?"leta":"leti"):s+(m||n?"let":"leti")}}var i={name:"sl",weekdays:"nedelja_ponedeljek_torek_sreda_četrtek_petek_sobota".split("_"),months:"januar_februar_marec_april_maj_junij_julij_avgust_september_oktober_november_december".split("_"),weekStart:1,weekdaysShort:"ned._pon._tor._sre._čet._pet._sob.".split("_"),monthsShort:"jan._feb._mar._apr._maj._jun._jul._avg._sep._okt._nov._dec.".split("_"),weekdaysMin:"ne_po_to_sr_če_pe_so".split("_"),ordinal:function(e){return e+"."},formats:{LT:"H:mm",LTS:"H:mm:ss",L:"DD.MM.YYYY",LL:"D. MMMM YYYY",LLL:"D. MMMM YYYY H:mm",LLLL:"dddd, D. MMMM YYYY H:mm",l:"D. M. YYYY"},relativeTime:{future:"čez %s",past:"pred %s",s:m,m,mm:m,h:m,hh:m,d:m,dd:m,M:m,MM:m,y:m,yy:m}};e.locale(i,null,!0);export{i as default};
