// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../core/Error ../../core/accessorSupport/originUtils ../../portal/Portal ../../portal/PortalItem ../../portal/support/jsonContext ../../portal/support/portalItemUtils ../../webdoc/saveAPIKeyUtils".split(" "),function(g,h,r,B,C,t,u,D){function v(a,b,c){c=c(a);if(!c.isValid)throw new h(`${b}:invalid-parameters`,c.errorMessage,{layer:a});}async function w(a){const {layer:b,errorNamePrefix:c,validateLayer:d}=a;await b.load();v(b,c,d)}function l(a,b){return`Layer (title: ${a.title}, id: ${a.id}) of type '${a.declaredClass}' ${b}`}
function x(a){const {item:b,itemType:c,errorNamePrefix:d,layer:f,validateItem:e}=a;D.validateSaveAPIKey(b);if(b.type!==c)throw new h(`${d}:portal-item-wrong-type`,`Portal item type should be "${c}"`,{item:b,layer:f});if(e&&(a=e(b),!a.isValid))throw new h(`${d}:invalid-parameters`,a.errorMessage,{layer:f});}function y(a){const {layer:b,errorNamePrefix:c}=a,{portalItem:d}=b;if(!d)throw new h(`${c}:portal-item-not-set`,l(b,"requires the portalItem property to be set"));if(!d.loaded)throw new h(`${c}:portal-item-not-loaded`,
l(b,"cannot be saved to a portal item that does not exist or is inaccessible"));x({...a,item:d})}function z(a){var b,c;const {newItem:d,itemType:f}=a;let e=C.from(d);e.id&&(e=e.clone(),e.id=null);(b=e).type??(b.type=f);(c=e).portal??(c.portal=B.getDefault());x({...a,item:e});return e}function E(a,b){let c=(a.messages??[]).filter(({type:d})=>"error"===d).map(({name:d,message:f,details:e})=>new h(d,f,e));a.blockedRelativeUrls&&(c=c.concat(a.blockedRelativeUrls.map(d=>new h("url:unsupported",`Relative url '${d}' is not supported`))));
b?.ignoreUnsupported&&(c=c.filter(({name:d})=>"layer:unsupported"!==d&&"symbol:unsupported"!==d&&"symbol-layer:unsupported"!==d&&"property:unsupported"!==d&&"url:unsupported"!==d));if(0<c.length)throw new h("layer-write:unsupported","Failed to save layer due to unsupported or invalid content. See 'details.errors' for more detailed information",{errors:c});}async function m(a,b,c){"beforeSave"in a&&"function"===typeof a.beforeSave&&await a.beforeSave();a=a.write({},b);await Promise.all(b.resources?.pendingOperations??
[]);E(b,c);return a}function n(a){u.addTypeKeyword(a,u.TypeKeyword.JSAPI);a.typeKeywords&&(a.typeKeywords=a.typeKeywords.filter((b,c,d)=>d.indexOf(b)===c))}async function A(a,b,c){const d=a.portal;await d.signIn();await d.user?.addItem({item:a,data:b,folder:c?.folder})}g.addItem=A;g.createErrorMessage=l;g.ensureItemConfig=y;g.ensureLayerConfig=v;g.getLayerJSON=m;g.getPortalItem=z;g.save=async function(a,b){const {layer:c,createItemData:d,createJSONContext:f,saveResources:e}=a;await w(a);y(a);a=c.portalItem;
const k=f?f(a):t.createForItemWrite(a);b=await m(c,k,b);b=await d({layer:c,layerJSON:b},a);n(a);await a.update({data:b});r.updateOrigins(k);await e?.(a,k);return a};g.saveAs=async function(a,b){const {layer:c,createItemData:d,createJSONContext:f,setItemProperties:e,saveResources:k}=a;await w(a);a=z(a);const p=f?f(a):t.createForItemWrite(a);var q=await m(c,p,b);q=await d({layer:c,layerJSON:q},a);await e(c,a);n(a);await A(a,q,b);c.portalItem=a;r.updateOrigins(p);await k?.(a,p);return a};g.setCommonItemProperties=
n;Object.defineProperty(g,Symbol.toStringTag,{value:"Module"})});