// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define(["exports"],function(e){class f{constructor(a){this._savedOffset=this._savedCursor=null;this._cursor=this._head=a}static from(a){a=d.from(new Float32Array(a));return new f(a)}get id(){return this._cursor.id}get baseZoom(){return this._cursor.baseZoom}get anchorX(){return this._cursor.anchorX}get anchorY(){return this._cursor.anchorY}get directionX(){return this._cursor.directionX}get directionY(){return this._cursor.directionY}get size(){return this._cursor.size}get materialKey(){return this._cursor.materialKey}get boundsCount(){return this._cursor.boundsCount}computedMinZoom(){return this._cursor.computedMinZoom()}setComputedMinZoom(a){return this._cursor.setComputedMinZoom(a)}boundsComputedAnchorX(a){return this._cursor.boundsComputedAnchorX(a)}boundsComputedAnchorY(a){return this._cursor.boundsComputedAnchorY(a)}setBoundsComputedAnchorX(a,
b){return this._cursor.setBoundsComputedAnchorX(a,b)}setBoundsComputedAnchorY(a,b){return this._cursor.setBoundsComputedAnchorY(a,b)}boundsX(a){return this._cursor.boundsX(a)}boundsY(a){return this._cursor.boundsY(a)}boundsWidth(a){return this._cursor.boundsWidth(a)}boundsHeight(a){return this._cursor.boundsHeight(a)}link(a){if(null!=a._head)return this._cursor.link(a._head)}getCursor(){return this.copy()}copy(){const a=new f(this._head?.copy());if(!a._head)return a;let b=a._head,c=a._head._link;
for(;c;)b._link=c.copy(),b=c,c=b._link;return a}peekId(){return this._cursor.peekId()??this._cursor._link.peekId()}nextId(){const a=this.id;for(;a===this.id;)if(!this.next())return!1;return!0}save(){this._savedCursor=this._cursor;this._savedOffset=this._cursor._offset}restore(){this._savedCursor&&(this._cursor=this._savedCursor);null!=this._savedOffset&&(this._cursor._offset=this._savedOffset)}next(){if(!this._cursor)return!1;if(!this._cursor.next()){if(!this._cursor._link)return!1;this._cursor=this._cursor._link;
this._cursor._offset=0}return!0}lookup(a){for(this._cursor=this._head;this._cursor&&!this._cursor.lookup(a);){if(!this._cursor._link)return!1;this._cursor=this._cursor._link}return!!this._cursor}delete(a){let b=this._head,c=null;for(;b;){if(b.delete(a))return b.isEmpty()&&null!=c&&(c._link=b._link),!0;c=b;b=b._link}return!1}}class d{constructor(a){this._offset=-1;this._link=null;this._deletedCount=this._count=0;this._offsets={instance:null};this._buffer=a}static from(a){return new d(new Float32Array(a))}isEmpty(){return this._deletedCount===
this.count}get count(){this._count||(this._count=this._computeCount());return this._count}get id(){return this._buffer[this._offset]}set id(a){this._buffer[this._offset]=a}get baseZoom(){return this._buffer[this._offset+1]}get anchorX(){return this._buffer[this._offset+2]}get anchorY(){return this._buffer[this._offset+3]}get directionX(){return this._buffer[this._offset+4]}get directionY(){return this._buffer[this._offset+5]}get size(){return this._buffer[this._offset+6]}get materialKey(){return this._buffer[this._offset+
7]}computedMinZoom(){return this._buffer[this._offset+8]}setComputedMinZoom(a){this._buffer[this._offset+8]=a}get boundsCount(){return this._buffer[this._offset+9]}boundsComputedAnchorX(a){return this._buffer[this._offset+10+6*a]}boundsComputedAnchorY(a){return this._buffer[this._offset+10+6*a+1]}setBoundsComputedAnchorX(a,b){this._buffer[this._offset+10+6*a]=b}setBoundsComputedAnchorY(a,b){this._buffer[this._offset+10+6*a+1]=b}boundsX(a){return this._buffer[this._offset+10+6*a+2]}boundsY(a){return this._buffer[this._offset+
10+6*a+3]}boundsWidth(a){return this._buffer[this._offset+10+6*a+4]}boundsHeight(a){return this._buffer[this._offset+10+6*a+5]}link(a){let b=this;for(;b._link;)b=b._link;b._link=a}getCursor(){return this.copy()}copy(){const a=new d(this._buffer);a._link=this._link;a._offset=this._offset;a._deletedCount=this._deletedCount;a._offsets=this._offsets;a._count=this._count;return a}peekId(){const a=this._offset+10+6*this.boundsCount+0;return a>=this._buffer.length?0:this._buffer[a]}next(){let a=0;for(;this._offset<
this._buffer.length&&100>a++&&(this._offset=-1===this._offset?0:this._offset+(10+6*this.boundsCount),4294967296===this.id););return 4294967296!==this.id&&this._offset<this._buffer.length}delete(a){const b=this._offset,c=this.lookup(a);if(c)for(this.id=4294967295,++this._deletedCount;this.next()&&this.id===a;)this.id=4294967295,++this._deletedCount;this._offset=b;return c}lookup(a){const b=this._offset;if(null==this._offsets.instance){this._offsets.instance=new Map;const c=this.copy();c._offset=-1;
let g=0;for(;c.next();)c.id!==g&&(this._offsets.instance.set(c.id,c._offset),g=c.id)}if(!this._offsets.instance.has(a))return!1;this._offset=this._offsets.instance.get(a);return 4294967296===this.id?(this._offset=b,!1):!0}_computeCount(){const a=this._offset;let b=0;for(this._offset=-1;this.next();)b++;this._offset=a;return b}}e.MetricReader=f;e.MetricReaderNode=d;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});