// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/promiseUtils ../../../../geometry/support/aaBoundingRect ./decluttering/SymbolFader ./style/StyleDefinition ../webgl/enums ../webgl/RenderableTile ../webgl/TileContainer ../../tiling/TileCoverage ../../tiling/TileKey ../../../webgl/enums".split(" "),function(y,C,z,D,l,n,E,F,G,H,f){function A(a,b){if(a){const c=a.getLayoutProperty("visibility");if(!c||c.getValue()!==l.Visibility.NONE&&(void 0===a.minzoom||a.minzoom<b+1E-6)&&(void 0===a.maxzoom||a.maxzoom>=b-1E-6))return!0}return!1}
class I extends F{constructor(a){super(a);this._backgroundTiles=[];this._pointToCallbacks=new Map}destroy(){this.removeAllChildren();this._spriteMosaic?.dispose();this._spriteMosaic=null;this._glyphMosaic?.dispose();this._glyphMosaic=null;null!=this._symbolFader&&(this._symbolFader.clear(),this._symbolFader=null);this._styleRepository=null;this._backgroundTiles=[];this._pointToCallbacks.clear()}get fading(){return this._symbolFader?.fading??!1}setStyleResources(a,b,c){this._spriteMosaic=a;this._glyphMosaic=
b;this._styleRepository=c;null==this._symbolFader&&(this._symbolFader=new D.SymbolFader(this._styleRepository,this.children));this._symbolFader.styleRepository=c}setSpriteMosaic(a){this._spriteMosaic?.dispose();this._spriteMosaic=a}deleteStyleLayers(a){null!=this._symbolFader&&this._symbolFader.deleteStyleLayers(a)}async hitTest(a){const b=C.createResolver();this._pointToCallbacks.set(a,b);this.requestRender();return b.promise}createRenderParams(a){return{...super.createRenderParams(a),renderPass:null,
styleLayer:null,styleLayerUID:-1,glyphMosaic:this._glyphMosaic,spriteMosaic:this._spriteMosaic,hasClipping:!!this._clippingInfos}}doRender(a){!this.visible||a.drawPhase!==n.WGLDrawPhase.MAP&&a.drawPhase!==n.WGLDrawPhase.DEBUG||void 0===this._spriteMosaic||super.doRender(a)}addChild(a){super.addChild(a);null!=this._symbolFader?this._symbolFader.addTile(a):a.decluttered=!0;this.requestRender();return a}removeChild(a){null!=this._symbolFader&&this._symbolFader.removeTile(a);this.requestRender();return super.removeChild(a)}renderChildren(a){const {drawPhase:b}=
a;if(b===n.WGLDrawPhase.DEBUG)super.renderChildren(a);else if(this._doRender(a),0<this._pointToCallbacks.size){a.drawPhase=n.WGLDrawPhase.HITTEST;const c=a.painter.effects.hittestVTL;c.bind(a);this._doRender(a);c.draw(a,this._pointToCallbacks);c.unbind(a);a.drawPhase=b}}removeAllChildren(){for(let a=0;a<this.children.length;a++){const b=this.children[a];null!=this._symbolFader&&this._symbolFader.removeTile(b);b.dispose()}super.removeAllChildren()}getStencilTarget(){return this.children.filter(a=>
a.neededForCoverage&&a.hasData())}restartDeclutter(){null!=this._symbolFader&&this._symbolFader.restartDeclutter()}_doRender(a){const {context:b}=a;var c=this._styleRepository;if(c){var m=c.layers,e=!0;a.drawPhase===n.WGLDrawPhase.HITTEST&&(e=!1);0<c.backgroundBucketIds.length&&(a.renderPass="background",this._renderBackgroundLayers(a,c.backgroundBucketIds));super.renderChildren(a);a.drawPhase===n.WGLDrawPhase.MAP&&this._fade(a.displayLevel,a.state);if((c=this.children.filter(g=>g.visible&&g.hasData()))&&
0!==c.length){for(var d of c)d.triangleCount=0;b.setStencilWriteMask(0);b.setColorMask(!0,!0,!0,!0);b.setStencilOp(f.StencilOperation.KEEP,f.StencilOperation.KEEP,f.StencilOperation.REPLACE);b.setStencilTestEnabled(!0);b.setBlendingEnabled(!1);b.setDepthTestEnabled(!0);b.setDepthWriteEnabled(!0);b.setDepthFunction(f.CompareFunction.LEQUAL);b.setClearDepth(1);b.clear(b.gl.DEPTH_BUFFER_BIT);a.renderPass="opaque";for(d=m.length-1;0<=d;d--)this._renderStyleLayer(m[d],a,c);b.setDepthWriteEnabled(!1);b.setBlendingEnabled(e);
b.setBlendFunctionSeparate(f.BlendFactor.ONE,f.BlendFactor.ONE_MINUS_SRC_ALPHA,f.BlendFactor.ONE,f.BlendFactor.ONE_MINUS_SRC_ALPHA);a.renderPass="translucent";for(e=0;e<m.length;e++)this._renderStyleLayer(m[e],a,c)}b.bindVAO();b.setStencilTestEnabled(!0);b.setBlendingEnabled(!0)}}_fade(a,b){null!=this._symbolFader&&(this._symbolFader.update(a,b)||this.requestRender())}_renderStyleLayer(a,b,c){const {painter:m,renderPass:e}=b;if(void 0!==a){var d=a.getLayoutProperty("visibility");if(!d||d.getValue()!==
l.Visibility.NONE){switch(a.type){case l.StyleLayerType.BACKGROUND:return;case l.StyleLayerType.FILL:if("opaque"!==e&&"translucent"!==b.renderPass)return;var g="vtlFill";break;case l.StyleLayerType.LINE:if("translucent"!==e)return;g="vtlLine";break;case l.StyleLayerType.CIRCLE:if("translucent"!==e)return;g="vtlCircle";break;case l.StyleLayerType.SYMBOL:if("translucent"!==e)return;g="vtlSymbol"}c=a.type===l.StyleLayerType.SYMBOL?c.filter(k=>k.decluttered):c.filter(k=>k.neededForCoverage);if("vtlSymbol"!==
g&&(d=b.displayLevel,0===c.length||void 0!==a.minzoom&&a.minzoom>=d+1E-6||void 0!==a.maxzoom&&a.maxzoom<d-1E-6))return;d=a.uid;b.styleLayerUID=d;b.styleLayer=a;for(const k of c)if(k.layerData.has(d)){m.renderObjects(b,c,g);break}}}}_renderBackgroundLayers(a,b){const {context:c,displayLevel:m,painter:e,state:d}=a,g=this._styleRepository;var k=!1;for(var t of b)if(g.getLayerById(t).type===l.StyleLayerType.BACKGROUND&&A(g.getLayerById(t),m)){k=!0;break}if(k){k=this._tileInfoView.getTileCoverage(a.state,
0,!0,"smallest");var {spans:J,lodInfo:u}=k,{level:p}=u,w=z.create();t=[];if(this._renderPasses){var q=this._renderPasses[0];null!=this._clippingInfos&&(q.brushes[0].prepareState(a),q.brushes[0].drawMany(a,this._clippingInfos))}q=this._backgroundTiles;var x=0;for(const {row:v,colFrom:K,colTo:L}of J)for(let r=K;r<=L;r++){if(x<q.length){var h=q[x];h.key.set(p,v,u.normalizeCol(r),u.getWorldForColumn(r));this._tileInfoView.getTileBounds(w,h.key,!1);h.x=w[0];h.y=w[3];h.resolution=this._tileInfoView.getTileResolution(p)}else{h=
new H(p,v,u.normalizeCol(r),u.getWorldForColumn(r));const B=this._tileInfoView.getTileBounds(z.create(),h),M=this._tileInfoView.getTileResolution(p);h=new E.RenderableTile(h,M,B[0],B[3],512,512,4096,4096);q.push(h)}h.setTransform(d);t.push(h);x++}c.setStencilWriteMask(0);c.setColorMask(!0,!0,!0,!0);c.setStencilOp(f.StencilOperation.KEEP,f.StencilOperation.KEEP,f.StencilOperation.REPLACE);c.setStencilFunction(f.CompareFunction.EQUAL,0,255);p=!0;a.drawPhase===n.WGLDrawPhase.HITTEST&&(p=!1);c.setStencilTestEnabled(p);
for(const v of b)b=g.getLayerById(v),b.type===l.StyleLayerType.BACKGROUND&&A(b,m)&&(a.styleLayerUID=b.uid,a.styleLayer=b,e.renderObjects(a,t,"vtlBackground"));G.pool.release(k)}}}y.VectorTileContainer=I;Object.defineProperty(y,Symbol.toStringTag,{value:"Module"})});