// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require ../chunks/tslib.es6 ../core/Collection ../core/events ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ./Widget ./BasemapLayerList/BasemapLayerListViewModel ./LayerList/ListItem ./LayerList/support/layerListUtils ./support/componentsUtils ./support/globalCss ./support/Heading ./support/legacyIcon ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ./support/widgetUtils ../chunks/sortable.esm".split(" "),
function(E,l,h,J,t,p,K,S,T,L,M,F,N,C,O,u,z,r,y,G,P,f,U,H){function D(a){const {actionsOpen:b,children:c}=a;b&&(a.actionsOpen=!1);c.forEach(d=>D(d))}function x(a){return a["data-item"]}const Q=h.ofType(N);var R=r.legacyIcon.layers;const A={exclusive:"exclusive",inherited:"inherited",independent:"independent"},I={baseLayers:!0,referenceLayers:!0,statusIndicators:!0,errors:!1};h=class extends M{constructor(a,b){super(a,b);this._tooltipReferenceMap=new Map;this._editingTitle=!1;this.visibleItems=this._focusSortUid=
this._sortableReferenceLayersNode=this._sortableBaseLayersNode=this._sortableReferenceLayers=this._sortableBaseLayers=this._focusOnElement=this._editTitleButton=this._editTitleInput=null;this.editingEnabled=!1;this.headingLevel=2;this.iconClass=R;this.messagesCommon=this.messages=null;this.multipleSelectionEnabled=!1;this.selectedItems=new Q;this.style="classic";this.viewModel=new F;this.visibleElements={...I}}initialize(){const {baseItems:a,referenceItems:b}=this;this._setVisibleItems();this.addHandles([t.watch(()=>
this.visibleElements,()=>{this._itemsChanged(a,"base-items");this._itemsChanged(b,"reference-items")}),t.on(()=>this.baseItems,"change",()=>{this._itemsChanged(a,"base-items")}),t.on(()=>this.referenceItems,"change",()=>this._itemsChanged(b,"reference-items")),t.watch(()=>this.editingEnabled,()=>this._toggleSorting(),t.initial)])}loadDependencies(){return O.loadCalciteComponents({icon:()=>new Promise((a,b)=>E(["../chunks/calcite-icon"],a,b)),tooltip:()=>new Promise((a,b)=>E(["../chunks/calcite-tooltip"],
a,b))})}destroy(){this._destroyBaseSortable();this._destroyReferenceSortable();this._tooltipReferenceMap.clear()}get basemapTitle(){return this.viewModel.basemapTitle}set basemapTitle(a){this.viewModel.basemapTitle=a}get baseListItemCreatedFunction(){return this.viewModel.baseListItemCreatedFunction}set baseListItemCreatedFunction(a){this.viewModel.baseListItemCreatedFunction=a}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get referenceListItemCreatedFunction(){return this.viewModel.referenceListItemCreatedFunction}set referenceListItemCreatedFunction(a){this.viewModel.referenceListItemCreatedFunction=
a}get baseItems(){return this.viewModel.baseItems}get referenceItems(){return this.viewModel.referenceItems}get view(){return this.viewModel.view}set view(a){this.viewModel.view=a}castVisibleElements(a){return{...I,...a}}triggerAction(a,b){return this.viewModel.triggerAction(a,b)}render(){var {state:a}=this.viewModel;a={["esri-basemap-layer-list--new-ui"]:"modern"===this.style,[u.globalCss.hidden]:"loading"===a,[u.globalCss.disabled]:"disabled"===a};const b=this._renderItemTooltips();var c=this._renderReferenceSection();
const d=this._renderBaseSection(),e=c&&d?f.tsx("hr",{class:"esri-basemap-layer-list__hr"}):null;c=[this._renderTitleContainer(),c,e,d];return f.tsx("div",{class:this.classes("esri-basemap-layer-list",u.globalCss.widget,u.globalCss.panel,a)},[b,c])}_renderItemTooltip(a){const {_tooltipReferenceMap:b,messages:c}=this;return a?f.tsx("calcite-tooltip",{referenceElement:b.get(a.uid)},c.layerIncompatibleTooltip):null}_renderItemTooltipNodes(a){const {incompatible:b,children:c}=a;return[b?this._renderItemTooltip(a):
null,...(!b&&c?c.toArray().map(d=>this._renderItemTooltipNodes(d)):[])]}_renderItemTooltips(){return this.visibleItems?.toArray().map(a=>this._renderItemTooltipNodes(a))??[]}_renderEditingInput(){const {messages:a}=this,{basemapTitle:b}=this.viewModel;return f.tsx("label",{class:"esri-basemap-layer-list__editing-input"},a.basemapTitle,f.tsx("input",{afterCreate:this._storeEditTitleInput,afterUpdate:this._focusEditElement,"aria-label":a.basemapTitle,bind:this,class:u.globalCss.input,pattern:".*\\S+.*",
placeholder:a.basemapTitle,required:!0,role:"textbox",title:a.basemapTitle,type:"text",value:b??void 0}))}_renderCancelButton(){const {messagesCommon:a}=this;return f.tsx("button",{"aria-label":a.cancel,bind:this,class:this.classes(u.globalCss.button,u.globalCss.buttonTertiary),onclick:this._toggleEditingTitle,title:a.cancel,type:"button"},a.cancel)}_renderSubmitButton(){const {messagesCommon:a}=this;return f.tsx("button",{"aria-label":a.form.submit,bind:this,class:u.globalCss.button,title:a.form.submit,
type:"submit"},a.form.ok)}_renderEditingForm(){return f.tsx("div",{class:"esri-basemap-layer-list__editing-card"},f.tsx("form",{bind:this,onsubmit:this._formSubmit},this._renderEditingInput(),f.tsx("div",{class:"esri-basemap-layer-list__editing-actions"},this._renderCancelButton(),this._renderSubmitButton())))}_renderBasemapTitle(){const {basemapTitle:a}=this.viewModel;return f.tsx(z.Heading,{class:this.classes(u.globalCss.heading,"esri-basemap-layer-list__main-heading"),level:this.headingLevel},
a)}_renderEditTitleButton(){const {_editingTitle:a,editingEnabled:b,messagesCommon:c}=this;return b&&!a?f.tsx("button",{afterCreate:this._storeEditTitleButton,afterUpdate:this._focusEditElement,"aria-label":c.edit,bind:this,class:"esri-basemap-layer-list__edit-button","data-node-ref":"_editButtonNode",onclick:this._toggleEditingTitle,title:c.edit,type:"button"},f.tsx("span",{"aria-hidden":"true",class:this.classes(r.legacyIcon.edit,"esri-basemap-layer-list__edit-button-icon")})):null}_renderTitleContainer(){return f.tsx("div",
{class:"esri-basemap-layer-list__title-container"},this._editingTitle?this._renderEditingForm():this._renderBasemapTitle(),this._renderEditTitleButton())}_renderNoLayersInfo(a,b){return f.tsx("div",{class:"esri-basemap-layer-list__no-items",key:b},a)}_renderList(a,b){const {messages:c}=this;return f.tsx("ul",{afterCreate:this._sortNodeCreated,afterRemoved:"reference"===b?this._destroyReferenceSortable:this._destroyBaseSortable,"aria-label":c.widgetLabel,bind:this,class:this.classes("esri-basemap-layer-list__list",
"esri-basemap-layer-list__list--root","esri-basemap-layer-list__list--independent"),"data-node-ref":b,key:b,role:this.editingEnabled&&a.length?"listbox":void 0},a.map(d=>this._renderItem({item:d,parent:null,itemType:b,isOnlyChild:1===a.length})))}_renderBaseHeader(){return f.tsx(z.Heading,{class:this.classes(u.globalCss.heading,"esri-basemap-layer-list__list-heading"),key:"base-heading",level:z.incrementHeadingLevel(this.headingLevel)},this.messages.baseHeading)}_renderBaseSection(){const {baseItems:a,
messages:b,visibleElements:c}=this;if(!c.baseLayers)return null;const d=this._getItems(a);return[this._renderBaseHeader(),[0===d.length?this._renderNoLayersInfo(b.noBaseLayers,"base"):null,this._renderList(d,"base")]]}_renderReferenceHeader(){return f.tsx(z.Heading,{class:this.classes(u.globalCss.heading,"esri-basemap-layer-list__list-heading"),key:"reference-heading",level:z.incrementHeadingLevel(this.headingLevel)},this.messages.referenceHeading)}_renderReferenceSection(){const {referenceItems:a,
messages:b,visibleElements:c}=this;if(!c.referenceLayers)return null;const d=this._getItems(a);return[this._renderReferenceHeader(),[0===d.length?this._renderNoLayersInfo(b.noReferenceLayers,"reference"):null,this._renderList(d,"reference")]]}_renderChildrenToggle(a,b){var {messagesCommon:c}=this;const {children:d}=a,e=!!a.error,g={["esri-basemap-layer-list__child-toggle--open"]:a.open};c=a.open?c.collapse:c.expand;return d.length&&!e?f.tsx("span",{"aria-controls":b,"aria-label":c,class:this.classes("esri-basemap-layer-list__child-toggle",
g),"data-item":a,key:"toggle-children",onclick:this._toggleChildrenClick,onkeydown:this._toggleChildrenClick,role:"button",tabIndex:0,title:c},f.tsx("span",{"aria-hidden":"true",class:this.classes("esri-basemap-layer-list__child-toggle-icon--closed",r.legacyIcon.rightTriangleArrow)}),f.tsx("span",{"aria-hidden":"true",class:this.classes("esri-basemap-layer-list__child-toggle-icon--opened",r.legacyIcon.downArrow)}),f.tsx("span",{"aria-hidden":"true",class:this.classes("esri-basemap-layer-list__child-toggle-icon--closed-rtl",
r.legacyIcon.leftTriangleArrow)})):null}_renderItemMessage(a){return a.error?f.tsx("div",{class:"esri-basemap-layer-list__item-message",key:"esri-basemap-layer-list__error",role:"alert"},f.tsx("span",{"aria-hidden":"true",class:r.legacyIcon.noticeTriangle}),this.messages.layerError):a.incompatible?f.tsx("div",{class:"esri-basemap-layer-list__item-message",key:"esri-basemap-layer-list__incompatible",role:"alert"},f.tsx("span",{afterCreate:b=>this._setTooltipReference(b,a),"aria-hidden":"true",bind:this,
class:r.legacyIcon.noticeTriangle,tabIndex:0}),this.messages.layerIncompatible):null}_renderActionsMenuIcon(a,b){const {messagesCommon:c}=this;return f.tsx("div",{"aria-controls":b,"aria-label":c.options,bind:this,class:this.classes("esri-basemap-layer-list__item-actions-menu-item",{["esri-basemap-layer-list__item-actions-menu-item--active"]:a.actionsOpen}),"data-item":a,key:"actions-menu-toggle",onclick:this._toggleActionsOpen,onkeydown:this._toggleActionsOpen,role:"button",tabIndex:0,title:c.options},
f.tsx("span",{"aria-hidden":"true",class:r.legacyIcon.handleHorizontal}))}_renderActionsMenu(a,b,c,d){var {panel:e}=a;e=e&&e.visible?this._renderPanelButton(e):null;const g=(b=1===c&&this._getSingleActionButton(b))?this._renderAction({item:a,action:b,singleAction:!0}):null;return(a=!b&&c?this._renderActionsMenuIcon(a,d):null)||e||b?f.tsx("div",{class:"esri-basemap-layer-list__item-actions-menu",key:"actions-menu"},e,g,a):null}_renderChildList(a,b){const {editingEnabled:c}=this,{visibilityMode:d,children:e}=
a,g=this._hasChildren(a),k=!g&&c&&"group"===a.layer?.type,{exclusive:m,inherited:q}=A,n={["esri-basemap-layer-list__list--empty"]:!g,["esri-basemap-layer-list__list--exclusive"]:d===m,["esri-basemap-layer-list__list--inherited"]:d===q,["esri-basemap-layer-list__list--independent"]:d!==q&&d!==m};return g||k?g?f.tsx("ul",{afterCreate:this._sortNodeCreated,afterUpdate:this._sortNodeCreated,"aria-expanded":a.open?"true":"false",bind:this,class:this.classes("esri-basemap-layer-list__list",n),"data-group":a.uid,
"data-item":a,hidden:a.open?null:!0,id:b,key:"list-items",role:c?"listbox":d===m?"radiogroup":"group"},e?.map(v=>this._renderItem({item:v,parent:a})).toArray()):f.tsx("div",{bind:this,class:"esri-basemap-layer-list__list-empty-state",id:b,key:"list-items"},this.messages.noItemsToDisplay):null}_renderItemContent(a,b,c){var {id:d}=this,e=`${d}_${a.uid}`;d=`${e}_actions`;e=`${e}__list`;const {panel:g}=a,k=this._filterActions(a.actionsSections),m=this._countActions(k);return[f.tsx("div",{class:"esri-basemap-layer-list__item-container",
key:"list-item-container"},this._renderChildrenToggle(a,e),this._renderLabel(a,b,c),this._renderActionsMenu(a,k,m,d)),this._renderItemMessage(a),m?this._renderActionsSections(a,k,d):null,g&&g.open&&!g.disabled?g.render():null,this._renderChildList(a,e)]}_renderItem({item:a,parent:b,itemType:c,isOnlyChild:d}){const {style:e,id:g,editingEnabled:k,selectedItems:m}=this,q=`${`${g}_${a.uid}`}__title`;var n=this._hasMessage(a);n={["esri-basemap-layer-list__item--has-children"]:this._hasChildren(a),["esri-basemap-layer-list__item--has-message"]:!!n,
["esri-basemap-layer-list__item--invisible"]:"modern"===e&&!a.visible,["esri-basemap-layer-list__item--invisible-at-scale"]:!a.visibleAtCurrentScale,["esri-basemap-layer-list__item--selectable"]:k};if(k){const v={["data-layer-uid"]:a.layer?.uid};return f.tsx("li",{afterCreate:this._focusListItem,afterUpdate:this._focusListItem,"aria-labelledby":q,"aria-selected":C.findSelectedItem(a,m)?"true":"false",bind:this,class:this.classes("esri-basemap-layer-list__item",n,{["esri-basemap-layer-list__item--only-child"]:!!d}),
"data-item":a,"data-item-type":c,key:`item-with-selection-${a.uid}`,onclick:this._toggleSelection,onkeydown:this._selectionKeydown,role:"option",tabIndex:0,...v},this._renderItemContent(a,b,q))}return f.tsx("li",{afterCreate:this._focusListItem,afterUpdate:this._focusListItem,"aria-labelledby":q,bind:this,class:this.classes("esri-basemap-layer-list__item",n),key:`item-no-selection-${a.uid}`},this._renderItemContent(a,b,q))}_renderConnectionIcon(a){({connectionStatus:a}=a);return null!=a?f.tsx("calcite-icon",
{icon:"connected"===a?"check-circle":"offline",scale:"s"}):null}_renderItemStatus(a,b){var {visibleElements:c}=this;if(!c.statusIndicators)return null;const {connectionStatus:d,publishing:e,updating:g}=a;c=!!d;return f.tsx("span",{class:this.classes({["esri-basemap-layer-list__status-indicator"]:!0,["esri-basemap-layer-list__publishing"]:e,["esri-basemap-layer-list__updating"]:g&&!b,["esri-basemap-layer-list__connection-status"]:c,["esri-basemap-layer-list__connection-status--connected"]:c&&"connected"===
d}),key:"layer-item-status"},this._renderConnectionIcon(a))}_renderItemTitle(a,b){const {messages:c}=this,d=a.title||c.untitledLayer;a=a.visibleAtCurrentScale?d:`${d} (${c.layerInvisibleAtScale})`;return f.tsx("span",{"aria-label":a,class:"esri-basemap-layer-list__item-title",id:b,key:"layer-title-container",title:a},d)}_renderItemToggleIcon({visible:a},b){var {style:c}=this;const {exclusive:d}=A;c="modern"===c;b=b?.visibilityMode===d;return f.tsx("span",{"aria-hidden":"true",class:this.classes({["esri-basemap-layer-list__item-toggle-icon"]:c&&
!b,["esri-basemap-layer-list__item-radio-icon"]:c&&b,[r.legacyIcon.radioChecked]:b&&a,[r.legacyIcon.radioUnchecked]:b&&!a,[r.legacyIcon.visible]:!b&&a,[r.legacyIcon.nonVisible]:!b&&!a}),key:"item-toggle-icon"})}_renderItemToggle(a,b,c){const {editingEnabled:d,messages:e}=this,{exclusive:g}=A,k=b?.visibilityMode;return d?f.tsx("span",{"aria-checked":a.visible?"true":"false","aria-labelledby":c,bind:this,class:"esri-basemap-layer-list__item-toggle","data-item":a,"data-parent-visibility":k,key:"item-toggle-selection-enabled",
onclick:this._toggleVisibility,onkeydown:this._toggleVisibility,role:k===g?"radio":"switch",tabIndex:0,title:e.layerVisibility},this._renderItemToggleIcon(a,b)):f.tsx("span",{class:"esri-basemap-layer-list__item-toggle",key:"item-toggle"},this._renderItemToggleIcon(a,b))}_renderLabel(a,b,c){const {editingEnabled:d,style:e,messages:g}=this,{inherited:k,exclusive:m}=A,q=b?.visibilityMode;var n=q===m?"radio":"switch",v=this._renderItemTitle(a,c);const B=this._renderItemStatus(a,b),w=this._renderItemToggle(a,
b,c);v="modern"===e?[v,B,w]:[w,v,B];n=d?f.tsx("div",{class:"esri-basemap-layer-list__item-label",key:`item-label-no-selection-${a.uid}`},v):f.tsx("div",{"aria-checked":a.visible?"true":"false","aria-labelledby":c,bind:this,class:"esri-basemap-layer-list__item-label","data-item":a,"data-parent-visibility":q,key:`item-label-with-selection-${a.uid}`,onclick:this._toggleVisibility,onkeydown:this._toggleVisibility,role:n,tabIndex:0,title:g.layerVisibility},v);return q===k||a.error?f.tsx("div",{class:"esri-basemap-layer-list__item-label",
key:`item-label-container-${a.uid}`},this._renderItemTitle(a,c),this._renderItemStatus(a,b)):n}_renderPanelButton(a){const {className:b,open:c,title:d,image:e,disabled:g}=a,k=e||b?b:r.legacyIcon.defaultAction,m=this._getIconImageStyles(a),q={["esri-basemap-layer-list__item-actions-menu-item--active"]:c&&!g},n={["esri-basemap-layer-list__item-action-image"]:!!m["background-image"],[u.globalCss.disabledElement]:a.disabled};k&&(n[k]=!!k);return f.tsx("div",{"aria-disabled":a.disabled.toString(),"aria-label":d,
bind:this,class:this.classes("esri-basemap-layer-list__item-actions-menu-item",q),"data-panel":a,key:`panel-${a.uid}`,onclick:this._triggerPanel,onkeydown:this._triggerPanel,role:"button",tabIndex:a.disabled?void 0:0,title:d},f.tsx("span",{class:this.classes(n),styles:m}))}_renderActionsSections(a,b,c){b=b.toArray().map((d,e)=>f.tsx("ul",{class:"esri-basemap-layer-list__item-actions-list",key:`${a}-action-section-${e}`},this._renderActionSection(a,d)));return f.tsx("div",{"aria-expanded":a.actionsOpen?
"true":"false",class:"esri-basemap-layer-list__item-actions",hidden:a.actionsOpen?null:!0,id:c,key:"actions-section",role:"group"},b)}_renderActionSection(a,b){return(b&&b.toArray()).map(c=>this._renderAction({item:a,action:c}))}_renderActionIcon(a){const {active:b,className:c}=a,d=this._getIconImageStyles(a);a="button"!==a.type||a.image||c?c:r.legacyIcon.defaultAction;const e={["esri-basemap-layer-list__item-action-image"]:!b&&!!d["background-image"],[r.legacyIcon.loadingIndicator]:b,[u.globalCss.rotating]:b};
a&&!b&&(e[a]=!0);return f.tsx("span",{"aria-hidden":"true",class:this.classes("esri-basemap-layer-list__item-action-icon",e),key:"action-icon",styles:d})}_renderActionTitle(a,b){return b?null:f.tsx("span",{class:"esri-basemap-layer-list__item-action-title",key:"action-title"},a)}_renderAction(a){const {item:b,action:c,singleAction:d}=a,{active:e,disabled:g,title:k}=c;a={["esri-basemap-layer-list__item-actions-menu-item"]:d&&"button"===c.type,["esri-basemap-layer-list__item-action"]:e||!d&&"toggle"!==
c.type,["esri-basemap-layer-list__action-toggle"]:!e&&"toggle"===c.type,["esri-basemap-layer-list__action-toggle--on"]:!e&&"toggle"===c.type&&c.value,[u.globalCss.disabledElement]:g};const m=[this._renderActionIcon(c),this._renderActionTitle(k,d)];return d?f.tsx("div",{"aria-label":k,bind:this,classes:a,"data-action":c,"data-item":b,key:`single-action-${c.uid}`,onclick:this._triggerAction,onkeydown:this._triggerAction,role:"button",tabIndex:0,title:k??void 0},m):f.tsx("li",{"aria-label":k,bind:this,
classes:a,"data-action":c,"data-item":b,key:`action-${c.uid}`,onclick:this._triggerAction,onkeydown:this._triggerAction,role:"button",tabIndex:0,title:k??void 0},m)}_setVisibleItems(){const {referenceItems:a,baseItems:b,visibleElements:c}=this;this.visibleItems=a.concat(b)?.filter(d=>!d.hidden&&(c.errors||!d.error))}_setTooltipReference(a,b){this._tooltipReferenceMap.set(b.uid,a);this.scheduleRender()}_hasMessage(a){return!!a.error||a.incompatible}_hasChildren(a){return!!a.children.length&&!this._hasMessage(a)}_filterActions(a){return a.map(b=>
b.filter(c=>c.visible))}_destroyReferenceSortable(){const {_sortableReferenceLayers:a}=this;a?.el&&a.destroy();this._sortableReferenceLayersNode=null}_destroyBaseSortable(){const {_sortableBaseLayers:a}=this;a?.el&&a.destroy();this._sortableBaseLayersNode=null}_toggleEditingTitle(){var {_editingTitle:a}=this;this._focusOnElement=(this._editingTitle=a=!a)?"edit-input":"edit-button";this.scheduleRender()}_storeEditTitleInput(a){this._editTitleInput=a;this._focusEditElement()}_focusEditElement(){this._editTitleInput&&
"edit-input"===this._focusOnElement&&(this._focusOnElement=null,this._editTitleInput.focus());this._editTitleButton&&"edit-button"===this._focusOnElement&&(this._focusOnElement=null,this._editTitleButton.focus())}_storeEditTitleButton(a){this._editTitleButton=a;this._focusEditElement()}_formSubmit(a){a.preventDefault();a=this._editTitleInput?.value;a?.trim()&&(this.basemapTitle=a);this._toggleEditingTitle()}_itemMovedList(a){const b=x(a.item);b&&this.viewModel.transferListItem({listItem:b,from:a.from.dataset.nodeRef,
to:a.to.dataset.nodeRef,newIndex:a.newIndex})}_toggleSortingBaseLayers(){const {_sortableBaseLayers:a,_sortableBaseLayersNode:b,editingEnabled:c}=this;if(b){var d=!c;if(a)a.option("disabled",d);else{const e=H.Sortable.create(b,{dataIdAttr:"data-layer-uid",group:"root-layers",filter:".esri-basemap-layer-list__item--only-child",fallbackTolerance:4,disabled:d,onSort:()=>this._sortLayersToItems({type:"base",itemIds:e.toArray()}),onAdd:g=>this._itemMovedList(g),chosenClass:"esri-basemap-layer-list--chosen"});
this._sortableBaseLayers=e}}}_toggleSortingReferenceLayers(){const {_sortableReferenceLayers:a,_sortableReferenceLayersNode:b,editingEnabled:c}=this;if(b){var d=!c;if(a)a.option("disabled",d);else{const e=H.Sortable.create(b,{dataIdAttr:"data-layer-uid",group:"root-layers",disabled:d,fallbackTolerance:4,onSort:()=>this._sortLayersToItems({type:"reference",itemIds:e.toArray()}),onAdd:g=>this._itemMovedList(g),chosenClass:"esri-basemap-layer-list--chosen"});this._sortableReferenceLayers=e}}}_toggleSorting(){this._toggleSortingBaseLayers();
this._toggleSortingReferenceLayers()}_sortNodeCreated(a){const b=a.getAttribute("data-node-ref");"base"===b&&(this._sortableBaseLayersNode=a);"reference"===b&&(this._sortableReferenceLayersNode=a);this._toggleSorting()}_getItems(a){return a.toArray().filter(b=>!b.hidden&&(this.visibleElements.errors||!b.error))}_getSingleActionButton(a){return a.reduce(b=>b).filter(b=>b&&"button"===b.type).at(0)}_sortLayersToItems({type:a,itemIds:b}){(a="base"===a?this.view?.map?.basemap?.baseLayers:"reference"===
a?this.view?.map?.basemap?.referenceLayers:null)&&a.sort((c,d)=>{c=b.indexOf(c.uid);d=b.indexOf(d.uid);return c>d?-1:c<d?1:0})}_focusListItem(a){const {_focusSortUid:b}=this;a&&b&&x(a)?.layer?.uid===b&&(a.focus(),this._focusSortUid=null)}_selectionKeydown(a){var b=J.eventKey(a);if(["ArrowDown","ArrowUp"].includes(b)){a.stopPropagation();var c=a.currentTarget,d=x(c);c=c.dataset.itemType;var {_sortableBaseLayers:e,_sortableReferenceLayers:g,selectedItems:k}=this,m="base"===c?e:"reference"===c?g:null;
if(m&&d){var q=C.findSelectedItem(d,k),n=m.toArray();a=n.indexOf(a.target.dataset.layerUid);var {baseItems:v,referenceItems:B}=this.viewModel;if(-1!==a)if("ArrowDown"===b){b=a+1;var w=b>=n.length;w&&"reference"===c&&q?(this.viewModel.transferListItem({listItem:d,from:"reference",to:"base",newIndex:v.length}),this._focusSortUid=d.layer?.uid,this.scheduleRender()):w&&"reference"===c?(this._focusSortUid=v.at(0)?.layer?.uid,this.scheduleRender()):w||(q&&(n.splice(b,0,n.splice(a,1)[0]),m.sort(n),this._sortLayersToItems({type:c,
itemIds:m.toArray()})),this._focusSortUid=d.layer?.uid,this.scheduleRender())}else"ArrowUp"===b&&(b=a-1,(w=0>b)&&"base"===c&&q?1!==v.length&&(this.viewModel.transferListItem({listItem:d,from:"base",to:"reference",newIndex:0}),this._focusSortUid=d.layer?.uid,this.scheduleRender()):w&&"base"===c?(this._focusSortUid=B.at(-1)?.layer?.uid,this.scheduleRender()):w||(q&&(n.splice(b,0,n.splice(a,1)[0]),m.sort(n),this._sortLayersToItems({type:c,itemIds:m.toArray()})),this._focusSortUid=d.layer?.uid,this.scheduleRender()))}}else this._toggleSelection(a)}_watchActionSectionChanges(a,
b){this.addHandles(a.on("change",()=>this.scheduleRender()),b);a.forEach(c=>this._renderOnActionChanges(c,b))}_renderOnActionChanges(a,b){"toggle"===a.type?this.addHandles([t.watch(()=>[a.className,a.image,a.id,a.title,a.visible,a.value],()=>this.scheduleRender(),t.initial)],b):"slider"===a.type?this.addHandles([t.watch(()=>[a.className,a.id,a.title,a.visible,a.value,a.displayValueEnabled,a.max,a.min,a.step],()=>this.scheduleRender(),t.initial)],b):this.addHandles([t.watch(()=>[a.className,a.image,
a.id,a.title,a.visible],()=>this.scheduleRender(),t.initial)],b)}_renderOnItemChanges(a,b){this.addHandles([t.watch(()=>[a.actionsOpen,a.visible,a.open,a.updating,a.connectionStatus,a.publishing,a.title,a.visibleAtCurrentScale,a.error,a.visibilityMode,a.panel,a.panel?.title,a.panel?.content,a.panel?.className],()=>this.scheduleRender(),t.initial),t.watch(()=>[a.hidden,a.error],()=>this._setVisibleItems()),a.actionsSections.on("change",()=>this.scheduleRender()),a.children.on("change",()=>this.scheduleRender())],
b);a.children.forEach(c=>this._renderOnItemChanges(c,b));a.actionsSections.forEach(c=>this._watchActionSectionChanges(c,b))}_itemsChanged(a,b){this.removeHandles(b);this._tooltipReferenceMap.clear();this._setVisibleItems();a.forEach(c=>this._renderOnItemChanges(c,b));this.scheduleRender()}_countActions(a){return a.reduce((b,c)=>b+c.length,0)}_getIconImageStyles(a){a="esri.widgets.LayerList.ListItemPanel"===a.declaredClass||"esri.support.Action.ActionButton"===a.declaredClass||"esri.support.Action.ActionToggle"===
a.declaredClass?a.image:null;return{"background-image":a?`url("${a}")`:""}}_toggleActionsOpen(a){a.stopPropagation();if(a=x(a.currentTarget)){var {actionsOpen:b}=a;b=!b;var {baseItems:c,referenceItems:d}=this;b&&(c.forEach(e=>D(e)),d.forEach(e=>D(e)));a.actionsOpen=b}}_triggerPanel(a){a.stopPropagation();(a=a.currentTarget["data-panel"])&&!a.disabled&&(a.open=!a.open)}_triggerAction(a){a.stopPropagation();var b=a.currentTarget;a=b["data-action"];(b=x(b))&&a&&("toggle"===a.type&&(a.value=!a.value),
this.triggerAction(a,b))}_toggleVisibility(a){a.stopPropagation();var b=a.currentTarget;a=b.getAttribute("data-parent-visibility");!(b=x(b))||a===A.exclusive&&b.visible||(b.visible=!b.visible)}_toggleChildrenClick(a){a.stopPropagation();if(a=x(a.currentTarget))a.open=!a.open}_toggleSelection(a){a.stopPropagation();const {multipleSelectionEnabled:b,selectedItems:c}=this,d=b&&(a.metaKey||a.ctrlKey);if(a=x(a.currentTarget)){var e=C.findSelectedItem(a,c),{length:g}=c,k=e&&1===g;d?e?c.remove(e):c.add(a):
g&&!k?(c.removeAll(),c.add(a)):e?c.remove(e):c.add(a)}}get test(){return{visibleItems:this.visibleItems}}};l.__decorate([p.property()],h.prototype,"visibleItems",void 0);l.__decorate([p.property()],h.prototype,"basemapTitle",null);l.__decorate([p.property()],h.prototype,"baseListItemCreatedFunction",null);l.__decorate([p.property()],h.prototype,"editingEnabled",void 0);l.__decorate([p.property()],h.prototype,"headingLevel",void 0);l.__decorate([p.property()],h.prototype,"iconClass",void 0);l.__decorate([p.property()],
h.prototype,"label",null);l.__decorate([p.property(),G.messageBundle("esri/widgets/BasemapLayerList/t9n/BasemapLayerList")],h.prototype,"messages",void 0);l.__decorate([p.property(),G.messageBundle("esri/t9n/common")],h.prototype,"messagesCommon",void 0);l.__decorate([p.property()],h.prototype,"multipleSelectionEnabled",void 0);l.__decorate([p.property()],h.prototype,"referenceListItemCreatedFunction",null);l.__decorate([p.property({readOnly:!0})],h.prototype,"baseItems",null);l.__decorate([p.property({readOnly:!0})],
h.prototype,"referenceItems",null);l.__decorate([p.property()],h.prototype,"selectedItems",void 0);l.__decorate([p.property()],h.prototype,"style",void 0);l.__decorate([p.property()],h.prototype,"view",null);l.__decorate([P.vmEvent("trigger-action"),p.property({type:F})],h.prototype,"viewModel",void 0);l.__decorate([p.property()],h.prototype,"visibleElements",void 0);l.__decorate([K.cast("visibleElements")],h.prototype,"castVisibleElements",null);l.__decorate([y.accessibleHandler()],h.prototype,"_toggleActionsOpen",
null);l.__decorate([y.accessibleHandler()],h.prototype,"_triggerPanel",null);l.__decorate([y.accessibleHandler()],h.prototype,"_triggerAction",null);l.__decorate([y.accessibleHandler()],h.prototype,"_toggleVisibility",null);l.__decorate([y.accessibleHandler()],h.prototype,"_toggleChildrenClick",null);l.__decorate([y.accessibleHandler()],h.prototype,"_toggleSelection",null);return h=l.__decorate([L.subclass("esri.widgets.BasemapLayerList")],h)});