// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require ../chunks/tslib.es6 ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ../support/basemapUtils ./Widget ./BasemapToggle/BasemapToggleViewModel ./BasemapToggle/css ./support/componentsUtils ./support/globalCss ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/jsxFactory ./support/widgetUtils".split(" "),function(m,d,f,v,b,D,w,x,y,n,e,z,k,A,B,
c,E){function p(a){return(a=x.getBasemapThumbnailUrl(a))?{backgroundImage:"url("+a+")"}:{backgroundImage:""}}const q={title:!1};b=class extends y{constructor(a,g){super(a,g);this.messages=null;this.viewModel=new n;this.visibleElements={...q}}loadDependencies(){return z.loadCalciteComponents({icon:()=>new Promise((a,g)=>m(["../chunks/calcite-icon"],a,g)),scrim:()=>new Promise((a,g)=>m(["../chunks/calcite-scrim"],a,g))})}get activeBasemap(){return this.viewModel.activeBasemap}get label(){return this.messages?.widgetLabel??
""}set label(a){this._overrideIfSome("label",a)}get nextBasemap(){return this.viewModel.nextBasemap}set nextBasemap(a){this.viewModel.nextBasemap=a}get view(){return this.viewModel.view}set view(a){this.viewModel.view=a}castVisibleElements(a){return{...q,...a}}toggle(){return this.viewModel.toggle()}render(){var a=this.viewModel;const g="disabled"===a.state?null:a.activeBasemap,h="disabled"===a.state?null:a.nextBasemap,C="loading"===a.state;a="incompatible-next-basemap"===a.state;const l=h?.title??
"",r=h&&"loaded"!==h.loadStatus;let t;const u=this.visibleElements.title&&l;if(u||a)t=c.tsx("div",{class:e.css.overlay,key:"overlay"},u?c.tsx("span",{class:e.css.title,title:l},l):null,a?c.tsx("calcite-scrim",{class:e.css.overlayScrim,title:this.messages.incompatibleSpatialReference},c.tsx("calcite-icon",{icon:"exclamation-mark-triangle"})):null);return c.tsx("div",{bind:this,class:this.classes(e.css.base,k.globalCss.widget,a?k.globalCss.disabled:null),"data-basemap-id":h?h.id:"",onclick:this._toggle,
onkeydown:this._toggle,role:"button",tabIndex:a?-1:0,title:this.label},c.tsx("div",{class:this.classes(e.css.container,e.css.secondaryBasemapImage)},c.tsx("div",{class:e.css.image,styles:p(g)})),c.tsx("div",{class:e.css.container},c.tsx("div",{class:this.classes(e.css.image,r?e.css.imageLoading:null),styles:p(h)},r||C?c.tsx("calcite-scrim",null,c.tsx("span",{"aria-hidden":"true",class:k.globalCss.loaderAnimation,role:"presentation"})):null),t))}_toggle(){this.toggle()}};d.__decorate([f.property({readOnly:!0})],
b.prototype,"activeBasemap",null);d.__decorate([f.property()],b.prototype,"label",null);d.__decorate([f.property(),B.messageBundle("esri/widgets/BasemapToggle/t9n/BasemapToggle")],b.prototype,"messages",void 0);d.__decorate([f.property()],b.prototype,"nextBasemap",null);d.__decorate([f.property()],b.prototype,"view",null);d.__decorate([f.property({type:n})],b.prototype,"viewModel",void 0);d.__decorate([f.property()],b.prototype,"visibleElements",void 0);d.__decorate([v.cast("visibleElements")],b.prototype,
"castVisibleElements",null);d.__decorate([A.accessibleHandler()],b.prototype,"_toggle",null);return b=d.__decorate([w.subclass("esri.widgets.BasemapToggle")],b)});