// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require ../chunks/tslib.es6 ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ../layers/support/layerUtils ./Widget ./FeatureForm/featureFormUtils ./FeatureTemplates/FeatureTemplatesViewModel ./FeatureTemplates/ItemList ./FeatureTemplates/TemplateItem ./FeatureTemplates/VisibleElements ./support/componentsUtils ./support/globalCss ./support/widgetUtils ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory".split(" "),
function(n,d,r,f,b,J,K,x,y,z,t,u,A,B,v,C,D,L,E,F,l){function G(a){return a.id}b=class extends z{constructor(a,c){super(a,c);this.enableListScroll=!0;this.filterText="";this.headingLevel=4;this.messages=null;this.selectionMode="none";this.viewModel=new u;this.visibleElements=new v;this.renderCustomItem=e=>null;this.renderCustomGroupContent=e=>null;this.renderItemLabel=()=>null;this.renderItemDescription=()=>null;this.renderItemContent=e=>null;this.renderItemContentEnd=e=>null;this._iconIntersectionObserver=
new IntersectionObserver((e,p)=>{e.forEach(async g=>{if(g.isIntersecting){const h=g.target;if(h?.["data-has-icon"])p.unobserve(h);else{var {layer:m,template:q}=h?.["data-item"];h&&(h["data-has-icon"]=!0);g=await B.fetchThumbnail(m,q).catch(()=>{h&&(h["data-has-icon"]=!1);return null});null!=g&&h.appendChild(g)}}})});this._renderItemIcon=e=>y.isTable(e.layer)?l.tsx("span",{"data-has-icon":!0,"data-item":e,key:"icon"},l.tsx("calcite-icon",{icon:"table"})):l.tsx("span",{afterCreate:this._afterItemCreateOrUpdate,
afterRemoved:this._afterItemRemoved,afterUpdate:this._afterItemCreateOrUpdate,"data-has-icon":!1,"data-item":e,key:"icon"});this._afterItemCreateOrUpdate=e=>{this._iconIntersectionObserver?.observe(e)};this._afterItemRemoved=e=>{this._iconIntersectionObserver?.unobserve(e)}}initialize(){const a=({label:c})=>!this.filterText||!!c?.toLowerCase().includes(this.filterText.toLowerCase());this.addHandles(r.watch(()=>this.viewModel,(c,e)=>{c&&!c.filterFunction&&(this.filterFunction=a);e&&e!==c&&e.filterFunction===
a&&(e.filterFunction=null)},r.initial))}destroy(){this._iconIntersectionObserver?.disconnect();this._iconIntersectionObserver=null}loadDependencies(){return C.loadCalciteComponents({icon:()=>new Promise((a,c)=>n(["../chunks/calcite-icon"],a,c)),input:()=>new Promise((a,c)=>n(["../chunks/calcite-input"],a,c)),list:()=>new Promise((a,c)=>n(["../chunks/calcite-list"],a,c)),"list-item":()=>new Promise((a,c)=>n(["../chunks/calcite-list-item"],a,c)),notice:()=>new Promise((a,c)=>n(["../chunks/calcite-notice"],
a,c))})}get disabled(){return this.viewModel.disabled}set disabled(a){this.viewModel.disabled=a}get filterFunction(){return this.viewModel.filterFunction}set filterFunction(a){this.viewModel.filterFunction=a}get groupBy(){return this.viewModel.groupBy}set groupBy(a){this.viewModel.groupBy=a}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get layers(){return this.viewModel.layers}set layers(a){this.viewModel.layers=a}get selectedItem(){return this.viewModel.selectedItem}select(a,
c){return this.viewModel.select(a,c)}render(){const {disabled:a,enableListScroll:c,filterText:e,headingLevel:p,messages:g,viewModel:{items:m,numberOfFeatureTemplates:q,selectedItem:h,state:w}}=this,H=this.visibleElements.filter&&1<q;if(0<m.length&&t.isTemplateItemGroup(m[0])){const k=m.find(I=>I.label===u.nullGroupBy.label);k&&(k.label=g.other)}return l.tsx("div",{"aria-label":g.widgetLabel,class:this.classes("esri-feature-templates",D.globalCss.widget)},"loading"===w?this._renderLoader():"ready"===
w?l.tsx(A.ItemList,{disabled:a,enableListScroll:c,filterEnabled:H,filterText:e,headingLevel:p,id:this.id,identify:G,items:m,messages:{filterPlaceholder:g.filterPlaceholder,noItems:g.noItems,noMatches:g.noMatches},renderCustomGroupContent:this.renderCustomGroupContent,renderCustomItem:this.renderCustomItem,renderIcon:this._renderItemIcon,renderItemContent:this.renderItemContent,renderItemContentEnd:this.renderItemContentEnd,renderItemDescription:this.renderItemDescription,renderItemLabel:this.renderItemLabel,
selectedItem:h??void 0,selectionMode:this.selectionMode??void 0,onFilterChange:k=>{this.filterText=k;this.viewModel.refresh()},onItemSelect:k=>!t.isTemplateItemGroup(k)&&this.viewModel.select(k)}):null)}_renderLoader(){return l.tsx("div",{class:"esri-feature-templates__loader",key:"loader"})}};d.__decorate([f.property()],b.prototype,"disabled",null);d.__decorate([f.property()],b.prototype,"enableListScroll",void 0);d.__decorate([f.property()],b.prototype,"filterFunction",null);d.__decorate([f.property()],
b.prototype,"filterText",void 0);d.__decorate([f.property()],b.prototype,"groupBy",null);d.__decorate([f.property()],b.prototype,"headingLevel",void 0);d.__decorate([f.property()],b.prototype,"label",null);d.__decorate([f.property()],b.prototype,"layers",null);d.__decorate([f.property(),E.messageBundle("esri/widgets/FeatureTemplates/t9n/FeatureTemplates")],b.prototype,"messages",void 0);d.__decorate([f.property({readOnly:!0})],b.prototype,"selectedItem",null);d.__decorate([f.property()],b.prototype,
"selectionMode",void 0);d.__decorate([f.property(),F.vmEvent("select")],b.prototype,"viewModel",void 0);d.__decorate([f.property({type:v,nonNullable:!0})],b.prototype,"visibleElements",void 0);d.__decorate([f.property()],b.prototype,"renderCustomItem",void 0);d.__decorate([f.property()],b.prototype,"renderCustomGroupContent",void 0);d.__decorate([f.property()],b.prototype,"renderItemLabel",void 0);d.__decorate([f.property()],b.prototype,"renderItemDescription",void 0);d.__decorate([f.property()],
b.prototype,"renderItemContent",void 0);d.__decorate([f.property()],b.prototype,"renderItemContentEnd",void 0);return b=d.__decorate([x.subclass("esri.widgets.FeatureTemplates")],b)});