// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../chunks/tslib.es6 ../core/Collection ../core/events ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/cast ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ./Widget ./support/globalCss ./support/legacyIcon ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ./support/widgetUtils ./TableList/ListItem ./TableList/TableListViewModel ./TableList/support/tableListUtils ../chunks/sortable.esm".split(" "),
function(g,f,y,m,l,z,H,I,A,B,p,q,t,v,C,h,J,D,w,u,E){const F=f.ofType(D);var G=q.legacyIcon.table;const x={statusIndicators:!0,errors:!1};f=class extends B{constructor(a,b){super(a,b);this.visibleItems=this._focusSortUid=this._sortableNode=this._sortable=null;this.iconClass=G;this.messagesCommon=this.messages=this.icon=null;this.selectionEnabled=this.multipleSelectionEnabled=!1;this.selectedItems=new F;this.viewModel=new w;this.visibleElements={...x}}initialize(){this._setVisibleItems(this.tableItems);
this.addHandles([m.watch(()=>this.visibleElements,()=>this._itemsChanged()),m.on(()=>this.viewModel.tableItems,"change",()=>this._itemsChanged()),m.watch(()=>this.selectionEnabled,()=>this._toggleSorting(),m.initial)])}destroy(){this._destroySortable()}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get listItemCreatedFunction(){return this.viewModel.listItemCreatedFunction}set listItemCreatedFunction(a){this.viewModel.listItemCreatedFunction=a}get map(){return this.viewModel.map}set map(a){this.viewModel.map=
a}get tableItems(){return this.viewModel.tableItems}castVisibleElements(a){return{...x,...a}}triggerAction(a,b){return this.viewModel.triggerAction(a,b)}render(){const {visibleItems:a}=this,b=this.viewModel?.state;return h.tsx("div",{class:this.classes("esri-table-list",p.globalCss.widget,p.globalCss.panel,{[p.globalCss.hidden]:"loading"===b,[p.globalCss.disabled]:"disabled"===b})},a?.length?this._renderList():this._renderNoItems())}_renderNoItems(){return h.tsx("div",{class:"esri-table-list__no-items"},
this.messages.noItemsToDisplay)}_renderList(){const {visibleItems:a,messages:b,selectionEnabled:c}=this;return h.tsx("ul",{afterCreate:this._sortNodeCreated,afterRemoved:this._destroySortable,"aria-label":b.widgetLabel,bind:this,class:this.classes("esri-table-list__list","esri-table-list__list--root"),"data-node-ref":"_sortableNode",role:c?"listbox":void 0},a?.map(d=>this._renderItem(d)).toArray())}_renderItem(a){const {id:b,selectionEnabled:c,selectedItems:d}=this,e=`${`${b}_${a.uid}`}__title`,n=
{["esri-table-list__item--has-message"]:!!this._hasMessage(a),["esri-table-list__item--selectable"]:c};if(c){const k={["data-layer-uid"]:a.layer?.uid};return h.tsx("li",{afterCreate:this._focusListItem,afterUpdate:this._focusListItem,"aria-labelledby":e,"aria-selected":u.findSelectedItem(a,d)?"true":"false",bind:this,class:this.classes("esri-table-list__item",n),"data-item":a,key:`item-with-selection-${a.uid}`,onclick:this._toggleSelection,onkeydown:this._selectionKeydown,role:"option",tabIndex:0,
...k},this._renderItemContent(a,e))}return h.tsx("li",{afterCreate:this._focusListItem,afterUpdate:this._focusListItem,"aria-labelledby":e,bind:this,class:this.classes("esri-table-list__item",n),key:`item-no-selection-${a.uid}`},this._renderItemContent(a,e))}_renderActionsMenuIcon(a,b){const {messagesCommon:c}=this;return h.tsx("div",{"aria-controls":b,"aria-label":c.options,bind:this,class:this.classes("esri-table-list__item-actions-menu-item",{["esri-table-list__item-actions-menu-item--active"]:a.actionsOpen}),
"data-item":a,key:"actions-menu-toggle",onclick:this._toggleActionsOpen,onkeydown:this._toggleActionsOpen,role:"button",tabIndex:0,title:c.options},h.tsx("span",{"aria-hidden":"true",class:q.legacyIcon.handleHorizontal}))}_renderActionsMenu(a,b,c,d){const e=(b=1===c&&this._getSingleActionButton(b))?this._renderAction({item:a,action:b,singleAction:!0}):null;return(a=!b&&c?this._renderActionsMenuIcon(a,d):null)||b?h.tsx("div",{class:"esri-table-list__item-actions-menu",key:"actions-menu"},e,a):null}_renderItemMessage(a){return a.error?
h.tsx("div",{class:"esri-table-list__item-message",key:"esri-table-list__error",role:"alert"},h.tsx("span",{"aria-hidden":"true",class:q.legacyIcon.noticeTriangle}),this.messages.tableError):null}_renderItemStatus(a){const {visibleElements:b}=this;if(!b.statusIndicators)return null;({publishing:a}=a);return h.tsx("span",{class:this.classes({["esri-table-list__publishing"]:a}),key:"layer-item-status"})}_renderItemContent(a,b){var {id:c}=this;c=`${`${c}_${a.uid}`}_actions`;const d=this._filterActions(a.actionsSections),
e=this._countActions(d);return[h.tsx("div",{class:"esri-table-list__item-container",key:"list-item-container"},this._renderTitle(a,b),this._renderItemStatus(a),this._renderActionsMenu(a,d,e,c)),this._renderItemMessage(a),e?this._renderActionsSections(a,d,c):null]}_renderTitle(a,b){const {messages:c}=this;return h.tsx("span",{class:"esri-table-list__item-title",id:b,key:"layer-title-container"},a.title||c.untitledTable)}_renderActionsSections(a,b,c){b=b.toArray().map((d,e)=>h.tsx("ul",{class:"esri-table-list__item-actions-list",
key:`${a}-action-section-${e}`},this._renderActionSection(a,d)));return h.tsx("div",{"aria-expanded":a.actionsOpen?"true":"false",class:"esri-table-list__item-actions",hidden:a.actionsOpen?null:!0,id:c,key:"actions-section",role:"group"},b)}_renderActionSection(a,b){return(b&&b.toArray()).map(c=>this._renderAction({item:a,action:c}))}_renderActionIcon(a){const {active:b,className:c}=a,d=this._getIconImageStyles(a);a="button"!==a.type||a.image||c?c:q.legacyIcon.defaultAction;const e={["esri-table-list__item-action-image"]:!b&&
!!d["background-image"],[q.legacyIcon.loadingIndicator]:b,[p.globalCss.rotating]:b};a&&!b&&(e[a]=!0);return h.tsx("span",{"aria-hidden":"true",class:this.classes("esri-table-list__item-action-icon",e),key:"action-icon",styles:d})}_renderActionTitle(a,b){return b?null:h.tsx("span",{class:"esri-table-list__item-action-title",key:"action-title"},a)}_renderAction(a){const {item:b,action:c,singleAction:d}=a,{active:e,disabled:n,title:k}=c;a={["esri-table-list__item-actions-menu-item"]:d&&"button"===c.type,
["esri-table-list__item-action"]:e||!d&&"toggle"!==c.type,["esri-table-list__action-toggle"]:!e&&"toggle"===c.type,["esri-table-list__action-toggle--on"]:!e&&"toggle"===c.type&&c.value,[p.globalCss.disabledElement]:n};const r=[this._renderActionIcon(c),this._renderActionTitle(k,d)];return d?h.tsx("div",{"aria-label":k,bind:this,classes:a,"data-action":c,"data-item":b,key:`single-action-${c.uid}`,onclick:this._triggerAction,onkeydown:this._triggerAction,role:"button",tabIndex:0,title:k??void 0},r):
h.tsx("li",{"aria-label":k,bind:this,classes:a,"data-action":c,"data-item":b,key:`action-${c.uid}`,onclick:this._triggerAction,onkeydown:this._triggerAction,role:"button",tabIndex:0,title:k??void 0},r)}_hasMessage(a){return!!a.error}_filterActions(a){return a.map(b=>b.filter(c=>c.visible))}_setVisibleItems(a){this.visibleItems=a?.filter(b=>!b.hidden&&(this.visibleElements.errors||!b.error))}_destroySortable(){const {_sortable:a}=this;a&&a.destroy();this._sortable=null}_toggleSorting(){const {_sortable:a,
_sortableNode:b,selectionEnabled:c}=this;if(b)if(a)a.option("disabled",!c);else{const d=E.Sortable.create(b,{dataIdAttr:"data-layer-uid",group:"root-tables",fallbackTolerance:4,disabled:!c,onSort:()=>this._sortTablesToItems(d.toArray()),chosenClass:"esri-table-list__item--chosen"});this._sortable=d}}_sortNodeCreated(a){this._sortableNode=a;this._toggleSorting()}_sortTablesToItems(a){const b=this.map?.tables;b&&b.sort((c,d)=>{c=a.indexOf(c.uid);d=a.indexOf(d.uid);return c>d?-1:c<d?1:0})}_getSingleActionButton(a){return a.reduce(b=>
b).filter(b=>b&&"button"===b.type).at(0)}_focusListItem(a){const {_focusSortUid:b}=this;a&&b&&a["data-item"].layer?.uid===b&&(a.focus(),this._focusSortUid=null)}_watchActionSectionChanges(a){this.addHandles(a.on("change",()=>this.scheduleRender()),"action-section");a.forEach(b=>this._renderOnActionChanges(b))}_renderOnActionChanges(a){const b=()=>this.scheduleRender();"toggle"===a.type?this.addHandles(m.watch(()=>[a.className,a.image,a.id,a.title,a.visible,a.value],b,m.initial),"actions"):"slider"===
a.type?this.addHandles(m.watch(()=>[a.className,a.id,a.title,a.visible,a.value,a.displayValueEnabled,a.max,a.min,a.step],b,m.initial),"actions"):this.addHandles(m.watch(()=>[a.className,a.image,a.id,a.title,a.visible],b,m.initial),"actions")}_renderOnItemChanges(a){const b=()=>this.scheduleRender();this.addHandles([m.watch(()=>[a.actionsOpen,a.title,a.error,a.publishing],b,m.initial),m.watch(()=>[a.hidden,a.error],()=>this._setVisibleItems(this.tableItems)),a.actionsSections.on("change",b)],"items");
a.actionsSections.forEach(c=>this._watchActionSectionChanges(c))}_itemsChanged(){const {tableItems:a}=this.viewModel;this._setVisibleItems(a);this.removeHandles("action-section");this.removeHandles("actions");this.removeHandles("items");a.forEach(b=>this._renderOnItemChanges(b));this.scheduleRender()}_countActions(a){return a.reduce((b,c)=>b+c.length,0)}_getIconImageStyles(a){a="esri.support.Action.ActionButton"===a.declaredClass||"esri.support.Action.ActionToggle"===a.declaredClass?a.image:null;
return{"background-image":a?`url("${a}")`:void 0}}_selectionKeydown(a){var b=y.eventKey(a);if(["ArrowDown","ArrowUp"].includes(b)){a.stopPropagation();var c=a.currentTarget["data-item"],{_sortable:d,selectedItems:e}=this;if(d){var n=u.findSelectedItem(c,e),k=d.toArray();a=k.indexOf(a.target.dataset.layerUid);if(-1!==a){if("ArrowDown"===b){const r=a+1;if(r>=k.length)return;n?(k.splice(r,0,k.splice(a,1)[0]),d.sort(k),this._sortTablesToItems(d.toArray()),this._focusSortUid=c.layer?.uid):(this._focusSortUid=
c.layer?.uid,this.scheduleRender())}"ArrowUp"===b&&(b=a-1,-1>=b||(n?(k.splice(b,0,k.splice(a,1)[0]),d.sort(k),this._sortTablesToItems(d.toArray()),this._focusSortUid=c.layer?.uid):(this._focusSortUid=c.layer?.uid,this.scheduleRender())))}}}else this._toggleSelection(a)}_toggleActionsOpen(a){const b=a.currentTarget["data-item"];var {actionsOpen:c}=b;(c=!c)&&this.tableItems.forEach(d=>{const {actionsOpen:e}=d;e&&(d.actionsOpen=!1)});b.actionsOpen=c;a.stopPropagation()}_triggerAction(a){var b=a.currentTarget;
const c=b["data-action"];b=b["data-item"];"toggle"===c.type&&(c.value=!c.value);this.triggerAction(c,b);a.stopPropagation()}_toggleSelection(a){a.stopPropagation();const {multipleSelectionEnabled:b,selectedItems:c}=this,d=b&&(a.metaKey||a.ctrlKey);a=a.currentTarget["data-item"];const e=u.findSelectedItem(a,c),{length:n}=c,k=e&&1===n;d?e?c.remove(e):c.add(a):n&&!k?(c.removeAll(),c.add(a)):e?c.remove(e):c.add(a)}get test(){return{visibleItems:this.visibleItems}}};g.__decorate([l.property()],f.prototype,
"visibleItems",void 0);g.__decorate([l.property()],f.prototype,"iconClass",void 0);g.__decorate([l.property()],f.prototype,"icon",void 0);g.__decorate([l.property()],f.prototype,"label",null);g.__decorate([l.property()],f.prototype,"listItemCreatedFunction",null);g.__decorate([l.property()],f.prototype,"map",null);g.__decorate([l.property(),v.messageBundle("esri/widgets/TableList/t9n/TableList")],f.prototype,"messages",void 0);g.__decorate([l.property(),v.messageBundle("esri/t9n/common")],f.prototype,
"messagesCommon",void 0);g.__decorate([l.property()],f.prototype,"multipleSelectionEnabled",void 0);g.__decorate([l.property()],f.prototype,"selectionEnabled",void 0);g.__decorate([l.property()],f.prototype,"selectedItems",void 0);g.__decorate([l.property({readOnly:!0})],f.prototype,"tableItems",null);g.__decorate([C.vmEvent("trigger-action"),l.property({type:w})],f.prototype,"viewModel",void 0);g.__decorate([l.property()],f.prototype,"visibleElements",void 0);g.__decorate([z.cast("visibleElements")],
f.prototype,"castVisibleElements",null);g.__decorate([t.accessibleHandler()],f.prototype,"_toggleActionsOpen",null);g.__decorate([t.accessibleHandler()],f.prototype,"_triggerAction",null);g.__decorate([t.accessibleHandler()],f.prototype,"_toggleSelection",null);return f=g.__decorate([A.subclass("esri.widgets.TableList")],f)});