// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require ../chunks/tslib.es6 ../core/deprecate ../core/Logger ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/arrayUtils ../core/has ../core/accessorSupport/decorators/subclass ./Widget ./support/componentsUtils ./support/globalCss ./support/legacyIcon ./support/decorators/accessibleHandler ./support/decorators/messageBundle ./support/decorators/vmEvent ./support/jsxFactory ./support/widgetUtils ./Track/TrackViewModel".split(" "),function(k,c,l,b,d,y,
z,A,r,t,u,h,m,v,w,x,g,B,n){var p=m.legacyIcon.tracking;const q=b.getLogger("esri.widgets.Track");b=class extends t{constructor(a,e){super(a,e);this.iconClass=p;this.messages=this.icon=null;this.viewModel=new n}loadDependencies(){return u.loadCalciteComponents({icon:()=>new Promise((a,e)=>k(["../chunks/calcite-icon"],a,e)),loader:()=>new Promise((a,e)=>k(["../chunks/calcite-loader"],a,e))})}get geolocationOptions(){return this.viewModel.geolocationOptions}set geolocationOptions(a){this.viewModel.geolocationOptions=
a}get goToLocationEnabled(){return this.viewModel.goToLocationEnabled}set goToLocationEnabled(a){this.viewModel.goToLocationEnabled=a}get goToOverride(){return this.viewModel.goToOverride}set goToOverride(a){this.viewModel.goToOverride=a}get graphic(){return this.viewModel.graphic}set graphic(a){this.viewModel.graphic=a}get label(){return this.messages?.widgetLabel??""}set label(a){this._overrideIfSome("label",a)}get rotationEnabled(){return this.viewModel.rotationEnabled}set rotationEnabled(a){this.viewModel.rotationEnabled=
a}get scale(){return this.viewModel.scale}set scale(a){this.viewModel.scale=a}get tracking(){return this.viewModel.tracking}get useHeadingEnabled(){l.deprecatedProperty(q,"useHeadingEnabled",{replacement:"rotationEnabled",version:"4.27",warnOnce:!0});return this.viewModel.rotationEnabled}set useHeadingEnabled(a){l.deprecatedProperty(q,"useHeadingEnabled",{replacement:"rotationEnabled",version:"4.27",warnOnce:!0});this.viewModel.rotationEnabled=a}get view(){return this.viewModel.view}set view(a){this.viewModel.view=
a}start(){this.viewModel.start()}stop(){this.viewModel.stop()}render(){const a=this.viewModel?.state,e={[h.globalCss.disabled]:"disabled"===a,[h.globalCss.hidden]:"feature-unsupported"===a};var {messages:f}=this;f=("tracking"===a?f?.stopTracking:f?.startTracking)??"";return g.tsx("div",{"aria-label":f,bind:this,class:this.classes("esri-track",h.globalCss.widget,h.globalCss.widgetButton,e),hidden:"feature-unsupported"===a,onclick:this._toggleTracking,onkeydown:this._toggleTracking,role:"button",tabIndex:0,
title:f},this._renderIcon(),g.tsx("span",{class:m.legacyIcon.fontFallbackText},f))}_renderIcon(){const {icon:a,iconClass:e,viewModel:f}=this;switch(f?.state){case "waiting":return g.tsx("calcite-loader",{inline:!0,key:"loader",label:"",scale:"s",type:"indeterminate"});case "tracking":return this._renderCalciteIcon("pause");default:return a?this._renderCalciteIcon(a):e&&e!==p?this._renderLegacyIcon(e):this._renderCalciteIcon("compass-north-circle")}}_renderCalciteIcon(a){return g.tsx("calcite-icon",
{icon:a,key:"icon",scale:"s"})}_renderLegacyIcon(a){return g.tsx("span",{"aria-hidden":"true",class:a,key:"legacy-icon"})}_toggleTracking(){const a=this.viewModel;a&&"feature-unsupported"!==a.state&&"disabled"!==a.state&&("tracking"===a.state||"waiting"===a.state?this.viewModel.stop():this.viewModel.start())}};c.__decorate([d.property()],b.prototype,"geolocationOptions",null);c.__decorate([d.property()],b.prototype,"goToLocationEnabled",null);c.__decorate([d.property()],b.prototype,"goToOverride",
null);c.__decorate([d.property()],b.prototype,"graphic",null);c.__decorate([d.property()],b.prototype,"iconClass",void 0);c.__decorate([d.property()],b.prototype,"icon",void 0);c.__decorate([d.property()],b.prototype,"label",null);c.__decorate([d.property(),w.messageBundle("esri/widgets/Track/t9n/Track")],b.prototype,"messages",void 0);c.__decorate([d.property()],b.prototype,"rotationEnabled",null);c.__decorate([d.property()],b.prototype,"scale",null);c.__decorate([d.property({readOnly:!0})],b.prototype,
"tracking",null);c.__decorate([d.property()],b.prototype,"useHeadingEnabled",null);c.__decorate([d.property()],b.prototype,"view",null);c.__decorate([d.property({type:n}),x.vmEvent(["track","track-error"])],b.prototype,"viewModel",void 0);c.__decorate([v.accessibleHandler()],b.prototype,"_toggleTracking",null);return b=c.__decorate([r.subclass("esri.widgets.Track")],b)});