// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../core/MapUtils ../../../../core/maybe ../../../../core/reactiveUtils ../../../../core/Logger ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/has ../../../../core/Error ../../../../core/accessorSupport/decorators/subclass ../../../../chunks/boundedPlane ./Deconflictor ./enums ./LabelDeconflictor ../../../support/Scheduler".split(" "),function(e,m,n,l,f,v,w,x,y,z,p,q,g,d,r,t){function h(a){a=a.layer;return!(!a?.featureReduction||
"selection"!==a.featureReduction.type)}function u(a){(a=a.graphics3DGraphics)&&a.forEach(b=>b.setVisibilityFlag(d.VisibilityGroup.GRAPHIC,d.VisibilityFlag.DECONFLICTION,!0))}e.GraphicsDeconflictor=class extends g.Deconflictor{constructor(){super(...arguments);this._contexts=new Map;this._viewState=new g.DeconflictorViewState;this.visibilityGroup=d.VisibilityGroup.GRAPHIC;this._marginFactor=-.1}get labels(){return this._labels}get viewState(){return this._viewState}initialize(){this.addHandles([f.watch(()=>
this.view?.state?.camera,()=>{this._updateViewState();this.setDirty()}),f.watch(()=>this.view?.map?.ground?.opacity,(a,b)=>{1!==a&&1!==b||this.setDirty()}),f.watch(()=>this.view?.slicePlane,()=>{this._updateSlicePlane();this._slicePlaneChanged()},f.initial)]);this._frameTask=this.view.resourceController.scheduler.registerTask(t.TaskPriority.GRAPHICS_DECONFLICTOR,this);this._labels=new r.LabelDeconflictor({view:this.view,parent:this})}destroy(){this._labels=l.destroyMaybe(this._labels);this._frameTask=
l.removeMaybe(this._frameTask)}get marginFactor(){return this._marginFactor}set marginFactor(a){this._marginFactor=a;this.setDirty()}setDirty(){0<this._contexts.size&&(super.setDirty(),this._labels.setDirty())}runTask(a){super.runTask(a);this.running||this._labels.setDirty()}setInitialIconVisibilityFlag(a,b){a=!(this._graphicSupportsDeconfliction(b)&&h(a));b.setVisibilityFlag(d.VisibilityGroup.GRAPHIC,d.VisibilityFlag.DECONFLICTION,a)}_updateViewState(){this.view?.state&&(this._viewState.camera.copyFrom(this.view.state.camera),
this._updateSlicePlane())}_updateSlicePlane(){const a=this.view?this.view.slicePlane:null;null!=a&&q.transform(a,this._viewState.camera.viewMatrix,this._viewState.slicePlane);this._viewState.slicePlaneEnabled=null!=a}_slicePlaneChanged(){n.someMap(this._contexts,(a,b)=>b.symbolCreationContext.slicePlaneEnabled)&&this.setDirty()}addGraphicsOwner(a){const b=this._getGraphicsContext(a);return{addGraphic:c=>this._addGraphic(a,b,c),removeGraphic:c=>this._removeGraphic(b,c),labelingInfoChange:()=>this._labels.enabledChanged(a,
b),featureReductionChange:()=>this.enabledChanged(a,b),slicePlaneEnabledChange:()=>this._slicePlaneEnabledChanged(a,b),clear:()=>b.forEach(c=>this._removeGraphic(b,c.graphics3DGraphic))}}removeGraphicsOwner(a){const b=this._contexts.get(a);b&&(b.forEach(c=>this._removeGraphic(b,c.graphics3DGraphic)),this._contexts.delete(a),this.setDirty())}_addGraphic(a,b,c){const k=c.graphic.uid;c=new g.DeconflictorGraphic(c,a.symbolCreationContext.slicePlaneEnabled);b.set(k,c);h(a)&&this.addToActiveGraphics(c);
a.labelsEnabled&&this._labels.addToActiveGraphics(c)}_removeGraphic(a,b){b=b.graphic.uid;const c=a.get(b);c&&(this.removeFromActiveGraphics(c),this._labels.removeFromActiveGraphics(c),a.delete(b),this.setDirty())}enabledChanged(a,b){const c=h(a);c||u(a);this.modifyGraphics(b,c)}_slicePlaneEnabledChanged(a,b){const c=a.symbolCreationContext.slicePlaneEnabled;b.forEach(k=>k.slicePlaneEnabled=c);this.setDirty()}getGraphicsLayers(a){return a.layers}_graphicSupportsDeconfliction(a){if(a.isDraped)return!1;
a=a.layers;if(!a?.length)return!1;for(const b of a)if(this.layerSupportsDeconfliction(b))return!0;return!1}_getGraphicsContext(a){var b=this._contexts.get(a);if(b)return b;b=new Map;this._contexts.set(a,b);this.setDirty();return b}};e.GraphicsDeconflictor=m.__decorate([p.subclass("esri.views.3d.layers.graphics.GraphicsDeconflictor")],e.GraphicsDeconflictor);Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});