// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("./chunks/tslib.es6 ./geometry ./PopupTemplate ./symbols ./core/Clonable ./core/JSONSupport ./core/uid ./core/accessorSupport/decorators/property ./core/accessorSupport/ensureType ./core/arrayUtils ./core/has ./core/accessorSupport/decorators/subclass ./geometry/support/jsonUtils".split(" "),function(e,n,p,q,c,k,l,g,t,u,v,r,m){var h;c=h=class extends c.ClonableMixin(k.JSONSupport){constructor(...a){super(...a);this.isAggregate=!1;this.sourceLayer=this.popupTemplate=this.layer=null;Object.defineProperty(this,
"uid",{value:l.generateUID(),configurable:!0})}normalizeCtorArgs(a,b,d,f){return a&&!a.declaredClass?a:{geometry:a,symbol:b,attributes:d,popupTemplate:f}}set aggregateGeometries(a){const b=this._get("aggregateGeometries");JSON.stringify(b)!==JSON.stringify(a)&&this._set("aggregateGeometries",a)}set attributes(a){const b=this._get("attributes");b!==a&&(this._set("attributes",a),this._notifyLayer("attributes",b,a))}set geometry(a){const b=this._get("geometry");b!==a&&(this._set("geometry",a),this._notifyLayer("geometry",
b,a))}set symbol(a){const b=this._get("symbol");b!==a&&(this._set("symbol",a),this._notifyLayer("symbol",b,a))}set visible(a){const b=this._get("visible");b!==a&&(this._set("visible",a),this._notifyLayer("visible",b,a))}cloneShallow(){return new h({aggregateGeometries:this.aggregateGeometries,attributes:this.attributes,geometry:this.geometry,isAggregate:this.isAggregate,layer:this.layer,popupTemplate:this.popupTemplate,sourceLayer:this.sourceLayer,symbol:this.symbol,visible:this.visible})}getEffectivePopupTemplate(a=
!1){if(this.popupTemplate)return this.popupTemplate;for(const b of[this.sourceLayer,this.layer])if(b){if("popupTemplate"in b&&b.popupTemplate)return b.popupTemplate;if(a&&"defaultPopupTemplate"in b&&null!=b.defaultPopupTemplate)return b.defaultPopupTemplate}return null}getAttribute(a){return this.attributes?.[a]}setAttribute(a,b){if(this.attributes){const d=this.getAttribute(a);this.attributes[a]=b;this._notifyLayer("attributes",d,b,a)}else this.attributes={[a]:b},this._notifyLayer("attributes",void 0,
b,a)}getObjectId(){return this.sourceLayer?"objectIdField"in this.sourceLayer&&this.sourceLayer.objectIdField?this.getAttribute(this.sourceLayer.objectIdField):null:null}toJSON(){var a=this.aggregateGeometries;if(null==a)a=null;else{var b={};for(const d in a){const f=a[d];f&&(b[d]=f.toJSON())}a=0!==Object.keys(b).length?b:null}return{aggregateGeometries:a,geometry:null!=this.geometry?this.geometry.toJSON():null,symbol:null!=this.symbol?this.symbol.toJSON():null,attributes:k.isSerializable(this.attributes)?
this.attributes.toJSON():{...this.attributes},popupTemplate:this.popupTemplate?.toJSON()??null}}notifyGeometryChanged(){this._notifyLayer("geometry",this.geometry,this.geometry)}notifyMeshTransformChanged(a={}){var {geometry:b}=this;"mesh"===b?.type&&(b={origin:b.origin,transform:b.transform},this._notifyLayer("origin-transform",b,b,a.action))}_notifyLayer(a,b,d,f){this.layer&&"graphicChanged"in this.layer&&(b={graphic:this,property:a,oldValue:b,newValue:d},"origin-transform"===a&&(b.action=f),"attributes"===
a&&(b.attributeName=f),this.layer.graphicChanged(b))}};e.__decorate([g.property({value:null,json:{read:function(a){if(!a)return null;const b={};for(const d in a){const f=m.fromJSON(a[d]);f&&(b[d]=f)}return 0!==Object.keys(b).length?b:null}}})],c.prototype,"aggregateGeometries",null);e.__decorate([g.property({value:null})],c.prototype,"attributes",null);e.__decorate([g.property({value:null,types:n.geometryTypes,json:{read:m.fromJSON}})],c.prototype,"geometry",null);e.__decorate([g.property({type:Boolean})],
c.prototype,"isAggregate",void 0);e.__decorate([g.property({clonable:"reference"})],c.prototype,"layer",void 0);e.__decorate([g.property({type:p})],c.prototype,"popupTemplate",void 0);e.__decorate([g.property({clonable:"reference"})],c.prototype,"sourceLayer",void 0);e.__decorate([g.property({value:null,types:q.symbolTypes})],c.prototype,"symbol",null);e.__decorate([g.property({type:Boolean,value:!0})],c.prototype,"visible",null);c=h=e.__decorate([r.subclass("esri.Graphic")],c);(c||(c={})).generateUID=
l.generateUID;return c});