// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../core/Error ../../../core/maybe ../PixelBlock ./ImageCanvasDecoder ./JpgPlus ./Lerc ./Lzw ./pixelRangeUtils ../../../chunks/Zlib ./Raw ./TiffDecoder ./utils".split(" "),function(A,y,G,w,H,I,B,J,K,C,L,D,M){async function N(a,e){if(!M.isPlatformLittleEndian)throw new y("rasterCoded:decode","lerc decoder is not supported on big endian platform");await B.load();const {offset:n}=e,{width:l,height:r,pixelType:b,statistics:f,depthCount:d,noDataValues:c,bandMasks:g,pixels:h,mask:k}=
B.decode(a,{inputOffset:n,returnInterleaved:e.returnInterleaved});a=new w({width:l,height:r,pixelType:b.toLowerCase(),pixels:h,mask:k,statistics:f,bandMasks:g,depthCount:d,noDataValues:c});f?.length||a.updateStatistics();return a}async function O(a,e){a=await D.decode(a,{...e,noDataValue:null});G.assertIsSome(a);a=new w({width:a.width,height:a.height,pixels:a.pixels,pixelType:a.pixelType.toLowerCase(),mask:a.mask,bandMasks:a.bandMasks,statistics:null});a.updateStatistics();return a}async function P(a,
e){a=await D.decodeTileOrStrip(a,e.customOptions);a=new w({width:a.width,height:a.height,pixels:a.pixels,pixelType:a.pixelType.toLowerCase(),mask:a.mask,statistics:null});a.updateStatistics();return a}function E(a,e){const n=e.pixelType||"u8",l=w.getPixelArrayConstructor(n),r="u8"===n?a:new l(a.buffer),b=[],f=e.planes||1;if(1===f)b.push(r);else for(let d=0;d<f;d++){const c=(e.width||1)*(e.height||a.length),g=new l(c);for(let h=0;h<c;h++)g[h]=r[h*f+d];b.push(g)}a=new w({width:e.width||1,height:e.height||
a.length,pixels:b,pixelType:n,statistics:null});a.updateStatistics();return a}function Q(a,e){a=(new C.Zlib(new Uint8Array(a))).getBytes();return E(a,e)}function R(a,e){a=J.decode(a,e.offset,e.eof,!e.isInputBigEndian);return E(a,e)}function S(a,e){a=I.decode(a,e.hasNoZlibMask??void 0);a=new w({width:a.width,height:a.height,pixels:a.pixels,pixelType:"U8",mask:a.mask,statistics:null});a.updateStatistics();return a}function T(a,e){a=new Uint8Array(a);a=new U(a);const {width:n,height:l}=e;e=n*l;a=a.decode();
let r=0;var b=0;let f;b=new Uint8Array(e);for(r=0;r<e;r++)b[r]=a[4*r+3];const d=new w({width:n,height:l,pixels:[],pixelType:"U8",mask:b,statistics:[]});for(r=0;3>r;r++){f=new Uint8Array(e);for(b=0;b<e;b++)f[b]=a[4*b+r];d.addData({pixels:f})}d.updateStatistics();return d}async function V(a,e,n,l){a=await (new H).decode(a,{applyJpegMask:!1,format:e,...n},l);a=new w(a);a.updateStatistics();return a}function F(a){if(null==a)throw new y("rasterCodec:decode","parameter encodeddata is required.");a=new Uint8Array(a,
0,10);let e="";255===a[0]&&216===a[1]?e="jpg":137===a[0]&&80===a[1]&&78===a[2]&&71===a[3]?e="png":67===a[0]&&110===a[1]&&116===a[2]&&90===a[3]&&73===a[4]&&109===a[5]&&97===a[6]&&103===a[7]&&101===a[8]&&32===a[9]?e="lerc":76===a[0]&&101===a[1]&&114===a[2]&&99===a[3]&&50===a[4]&&32===a[5]?e="lerc2":73===a[0]&&73===a[1]&&42===a[2]&&0===a[3]||77===a[0]&&77===a[1]&&0===a[2]&&42===a[3]||73===a[0]&&73===a[1]&&43===a[2]&&0===a[3]||77===a[0]&&77===a[1]&&0===a[2]&&43===a[3]?e="tiff":71===a[0]&&73===a[1]&&70===
a[2]?e="gif":66===a[0]&&77===a[1]?e="bmp":String.fromCharCode.apply(null,a).toLowerCase().includes("error")&&(e="error");return e}function W(a){let e=null;switch(a){case "lerc":case "lerc2":e=N;break;case "jpg":e=S;break;case "png":e=T;break;case "bsq":case "bip":e=(n,l)=>{var r=l.pixelType,b=null;let f=null;switch(r?r.toLowerCase():"f32"){case "u1":case "u2":case "u4":case "u8":f=255;b=Uint8Array;break;case "u16":f=f||65535;b=Uint16Array;break;case "u32":f=f||2**32-1;b=Uint32Array;break;case "s8":f=
f||-128;b=Int8Array;break;case "s16":f=f||-32768;b=Int16Array;break;case "s32":f=f||-(2**31);b=Int32Array;break;default:b=Float32Array}({pixelTypeCtor:r}={pixelTypeCtor:b,noDataValue:f});b=L.decode;n=b(n,{width:l.width,height:l.height,pixelType:r,format:a});l=new w({width:l.width,height:l.height,pixels:n.pixels,pixelType:l.pixelType,mask:n.mask,statistics:null});l.updateStatistics();return l};break;case "tiff":e=O;break;case "deflate":e=Q;break;case "lzw":e=R;break;case "error":e=()=>{throw new y("rasterCodec:decode",
"input data contains error");};break;default:e=()=>{throw new y("rasterCodec:decode","unsupported raster format");}}return e}function X(a,e=1){if(a){var {pixels:n,width:l,height:r,mask:b}=a;if(n&&0!==n.length){var f=n.length,d=l-1,c=r-1,g=[],h,k,t=null,p=w.getPixelArrayConstructor(a.pixelType);if(0===e){for(e=0;e<f;e++){var m=n[e];var u=new p(d*c);for(h=0;h<c;h++){var q=h*l;for(k=0;k<d;k++)u[h*d+k]=m[q+k]}g.push(u)}if(null!=b)for(t=new Uint8Array(d*c),h=0;h<c;h++)for(q=h*l,k=0;k<d;k++)t[h*d+k]=b[q+
k]}else{for(e=0;e<f;e++){m=n[e];u=new p(d*c);for(h=0;h<c;h++)for(q=h*l,k=0;k<d;k++)u[h*d+k]=(m[q+k]+m[q+k+1]+m[q+l+k]+m[q+l+k+1])/4;g.push(u)}if(b)for(t=new Uint8Array(d*c),h=0;h<c;h++)for(q=h*l,k=0;k<d;k++)t[h*d+k]=Math.min.apply(null,[b[q+k],b[q+k+1],b[q+l+k],b[q+l+k+1]])}a.width=d;a.height=c;a.mask=t;a.pixels=g}}}var U=function(a){function e(b){var f,d;this.data=b;this.pos=8;this.palette=[];this.imgData=[];this.transparency={};this.animation=null;this.text={};for(d=null;;){var c=this.readUInt32();
var g=b=void 0;b=[];for(g=0;4>g;++g)b.push(String.fromCharCode(this.data[this.pos++]));b=b.join("");switch(b){case "IHDR":this.width=this.readUInt32();this.height=this.readUInt32();this.bits=this.data[this.pos++];this.colorType=this.data[this.pos++];this.compressionMethod=this.data[this.pos++];this.filterMethod=this.data[this.pos++];this.interlaceMethod=this.data[this.pos++];break;case "acTL":this.animation={numFrames:this.readUInt32(),numPlays:this.readUInt32()||Infinity,frames:[]};break;case "PLTE":this.palette=
this.read(c);break;case "fcTL":d&&this.animation.frames.push(d);this.pos+=4;d={width:this.readUInt32(),height:this.readUInt32(),xOffset:this.readUInt32(),yOffset:this.readUInt32()};b=this.readUInt16();c=this.readUInt16()||100;d.delay=1E3*b/c;d.disposeOp=this.data[this.pos++];d.blendOp=this.data[this.pos++];d.data=[];break;case "IDAT":case "fdAT":"fdAT"===b&&(this.pos+=4,c-=4);b=(null!=d?d.data:void 0)||this.imgData;for(g=0;0<=c?g<c:g>c;0<=c?++g:--g)b.push(this.data[this.pos++]);break;case "tRNS":this.transparency=
{};switch(this.colorType){case 3:this.transparency.indexed=this.read(c);c=255-this.transparency.indexed.length;if(0<c)for(b=0;0<=c?b<c:b>c;0<=c?++b:--b)this.transparency.indexed.push(255);break;case 0:this.transparency.grayscale=this.read(c)[0];break;case 2:this.transparency.rgb=this.read(c)}break;case "tEXt":g=this.read(c);c=g.indexOf(0);b=String.fromCharCode.apply(String,g.slice(0,c));this.text[b]=String.fromCharCode.apply(String,g.slice(c+1));break;case "IEND":d&&this.animation.frames.push(d);
a:{switch(this.colorType){case 0:case 3:case 4:d=1;break a;case 2:case 6:d=3;break a}d=void 0}this.colors=d;this.hasAlphaChannel=4===(f=this.colorType)||6===f;f=this.colors+(this.hasAlphaChannel?1:0);this.pixelBitlength=this.bits*f;a:{switch(this.colors){case 1:f="DeviceGray";break a;case 3:f="DeviceRGB";break a}f=void 0}this.colorSpace=f;this.imgData=new Uint8Array(this.imgData);return;default:this.pos+=c}this.pos+=4;if(this.pos>this.data.length)throw Error("Incomplete or corrupt PNG file");}}var n;
e.load=function(b,f,d){"function"===typeof f&&(d=f);var c=new XMLHttpRequest;c.open("GET",b,!0);c.responseType="arraybuffer";c.onload=function(){var g=new Uint8Array(c.response||c.mozResponseArrayBuffer);g=new e(g);"function"===typeof(null!=f?f.getContext:void 0)&&g.render(f);return"function"===typeof d?d(g):void 0};return c.send(null)};e.prototype.read=function(b){var f;var d=[];for(f=0;0<=b?f<b:f>b;0<=b?++f:--f)d.push(this.data[this.pos++]);return d};e.prototype.readUInt32=function(){var b=this.data[this.pos++]<<
24;var f=this.data[this.pos++]<<16;var d=this.data[this.pos++]<<8;var c=this.data[this.pos++];return b|f|d|c};e.prototype.readUInt16=function(){var b=this.data[this.pos++]<<8;var f=this.data[this.pos++];return b|f};e.prototype.decodePixels=function(b){var f,d,c,g,h,k,t,p;null==b&&(b=this.imgData);if(0===b.length)return new Uint8Array(0);b=new C.Zlib(b);b=b.getBytes();var m=this.pixelBitlength/8;var u=m*this.width;var q=new Uint8Array(u*this.height);var Y=b.length;for(d=g=h=0;g<Y;){switch(b[g++]){case 0:for(c=
f=0;f<u;c=f+=1)q[d++]=b[g++];break;case 1:for(c=k=0;k<u;c=k+=1){f=b[g++];var v=c<m?0:q[d-m];q[d++]=(f+v)%256}break;case 2:for(c=v=0;v<u;c=v+=1){f=b[g++];var x=(c-c%m)/m;k=h&&q[(h-1)*u+x*m+c%m];q[d++]=(k+f)%256}break;case 3:for(c=p=0;p<u;c=p+=1)f=b[g++],x=(c-c%m)/m,v=c<m?0:q[d-m],k=h&&q[(h-1)*u+x*m+c%m],q[d++]=(f+Math.floor((v+k)/2))%256;break;case 4:for(c=p=0;p<u;c=p+=1){f=b[g++];x=(c-c%m)/m;v=c<m?0:q[d-m];0===h?k=t=0:(k=q[(h-1)*u+x*m+c%m],t=x&&q[(h-1)*u+(x-1)*m+c%m]);var z=v+k-t;c=Math.abs(z-v);
x=Math.abs(z-k);z=Math.abs(z-t);v=c<=x&&c<=z?v:x<=z?k:t;q[d++]=(f+v)%256}break;default:throw Error("Invalid filter algorithm: "+b[g-1]);}h++}return q};e.prototype.decodePalette=function(){var b,f,d,c;var g=this.palette;var h=this.transparency.indexed||[];var k=new Uint8Array((h.length||0)+g.length);var t=0;g.length;var p=f=b=0;for(d=g.length;f<d;p=f+=3)k[t++]=g[p],k[t++]=g[p+1],k[t++]=g[p+2],k[t++]=null!=(c=h[b++])?c:255;return k};e.prototype.copyToImageData=function(b,f){var d,c;var g=this.colors;
var h=null;var k=this.hasAlphaChannel;this.palette.length&&(h=null!=(d=this._decodedPalette)?d:this._decodedPalette=this.decodePalette(),g=4,k=!0);b=b.data||b;var t=b.length;var p=h||f;d=c=0;if(1===g)for(;d<t;)g=h?4*f[d/4]:c,c=p[g++],b[d++]=c,b[d++]=c,b[d++]=c,b[d++]=k?p[g++]:this.transparency.grayscale&&this.transparency.grayscale===c?0:255,c=g;else for(;d<t;)g=h?4*f[d/4]:c,b[d++]=p[g++],b[d++]=p[g++],b[d++]=p[g++],b[d++]=k?p[g++]:this.transparency.rgb&&this.transparency.rgb[1]===p[g-3]&&this.transparency.rgb[3]===
p[g-2]&&this.transparency.rgb[5]===p[g-1]?0:255,c=g};e.prototype.decode=function(){var b=new Uint8Array(this.width*this.height*4);this.copyToImageData(b,this.decodePixels());return b};var l=(n=a.document&&a.document.createElement("canvas"))&&n.getContext("2d");var r=function(b){l.width=b.width;l.height=b.height;l.clearRect(0,0,b.width,b.height);l.putImageData(b,0,0);b=new Image;b.src=n.toDataURL();return b};e.prototype.decodeFrames=function(b){var f,d;if(this.animation){var c=this.animation.frames;
var g=[];var h=f=0;for(d=c.length;f<d;h=++f){h=c[h];var k=b.createImageData(h.width,h.height);var t=this.decodePixels(new Uint8Array(h.data));this.copyToImageData(k,t);h.imageData=k;g.push(h.image=r(k))}return g}};e.prototype.renderFrame=function(b,f){var d=this.animation.frames;var c=d[f];d=d[f-1];0===f&&b.clearRect(0,0,this.width,this.height);1===(null!=d?d.disposeOp:void 0)?b.clearRect(d.xOffset,d.yOffset,d.width,d.height):2===(null!=d?d.disposeOp:void 0)&&b.putImageData(d.imageData,d.xOffset,
d.yOffset);0===c.blendOp&&b.clearRect(c.xOffset,c.yOffset,c.width,c.height);return b.drawImage(c.image,c.xOffset,c.yOffset)};e.prototype.animate=function(b){var f,d=this;var c=0;var g=this.animation;var h=g.numFrames;var k=g.frames;var t=g.numPlays;return(f=function(){var p=c++%h;var m=k[p];d.renderFrame(b,p);if(1<h&&c/h<t)return d.animation._timeout=setTimeout(f,m.delay)})()};e.prototype.stopAnimation=function(){var b;return clearTimeout(null!=(b=this.animation)?b._timeout:void 0)};e.prototype.render=
function(b){b._png&&b._png.stopAnimation();b._png=this;b.width=this.width;b.height=this.height;b=b.getContext("2d");if(this.animation)return this.decodeFrames(b),this.animate(b);var f=b.createImageData(this.width,this.height);this.copyToImageData(f,this.decodePixels());return b.putImageData(f,0,0)};return e}(self);const Z=new Set(["jpg","png","bmp","gif"]);A.decode=async function(a,e={},n){if(null==a)throw new y("rasterCodec:decode","missing encodeddata parameter.");let l=e.format?.toLowerCase();
if(!("bsq"!==l&&"bip"!==l||null!=e.width&&null!=e.height))throw new y("rasterCodec:decode","requires width and height in options parameter.");if("tiff"===l&&e.customOptions)return P(a,e);if(!l||"bsq"!==l&&"bip"!==l&&"deflate"!==l&&"lzw"!==l)l=F(a);if(e.useCanvas&&Z.has(l))return V(a,l,e,n);n=W(l);e.isPoint&&(e={...e},null!=e.width&&e.width++,null!=e.height&&e.height++);a=await n(a,e);if(!a)return a;"jpg"!==l&&null!=e.noDataValue&&1===a.depthCount&&K.convertNoDataToMask(a,e.noDataValue,{customFloatTolerance:e.tolerance});
e.isPoint&&X(a);return a};A.getFormat=function(a){a=F(a);"lerc2"===a?a="lerc":"error"===a&&(a="");return a};Object.defineProperty(A,Symbol.toStringTag,{value:"Module"})});