// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/tslib.es6 ../../../../../core/arrayUtils ../../../../../core/Evented ../../../../../core/handleUtils ../../../../../core/maybe ../../../../../core/quantityUtils ../../../../../core/reactiveUtils ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/has ../../../../../core/accessorSupport/decorators/subclass ../../../../../core/support/UpdatingHandles ../../../../../geometry/Point ../../../../../support/elevationInfoUtils ../../../../ViewingMode ../../Manipulator3D ../../manipulatorUtils ../../SnappingVisualizer3D ../manipulatorUtils ../meshFastUpdateUtils ../visualElementUtils ../manipulations/config ../manipulations/MoveManipulation ../manipulations/moveUtils ./GraphicScaleRotateTransform ./ScaleRotateMeshAdapter ./ScaleRotateObjectSymbol3DAdapter ./undoRecords ../../../layers/graphics/GraphicState ../../../../interactive/dragEventPipeline ../../../../interactive/InteractiveToolBase ../../../../interactive/editGeometry/EditGeometryOperations ../../../../interactive/sketch/SketchTooltipOptions ../../../../interactive/snapping/SnappingContext ../../../../interactive/snapping/SnappingDragPipelineStep ../../../../interactive/tooltip/Tooltip ../../../../interactive/tooltip/TranslateTooltipInfos ../../../../support/automaticLengthMeasurementUtils ../../../../support/euclideanLengthMeasurementUtils".split(" "),
function(d,f,A,B,C,r,u,q,g,ca,da,D,E,F,G,H,I,J,K,x,L,M,N,l,O,P,Q,R,S,T,U,V,W,y,X,Y,Z,v,z,aa){d.GraphicTransformTool=class extends B.EventedMixin(V.InteractiveToolBase){constructor(a){super(a);this.enableScaling=this.enableRotation=this.enableZ=!0;this.tooltipOptions=new y;this.type="transform-3d";this._updatingHandles=new E.UpdatingHandles;this._translateGraphicZTooltipInfo=this._translateGraphicXYTooltipInfo=this._translateGraphicTooltipInfo=this._tooltip=this._scaleRotate=null}initialize(){const {graphic:a,
view:c}=this;this.graphicState=new T.GraphicState({graphic:a});this.addHandles(q.watch(()=>this.tooltipOptions.enabled,b=>{this._tooltip=b?new Z.Tooltip({view:c}):r.destroyMaybe(this._tooltip)},q.syncAndInitial));this._moveManipulation=new l.MoveManipulation({tool:this,view:c,snapToScene:this.snapToScene,xyAvailable:!0,xyAxisAvailable:!0,zAvailable:this.enableZ&&x.canMoveZ(a),radius:l.MoveManipulation.radiusForSymbol(a.symbol)});this._moveManipulation.forEachManipulator(b=>this.addHandles(b.events.on("immediate-click",
h=>{this.emit("immediate-click",{...h,graphic:a});h.stopPropagation()})));const k=b=>h=>{this.addHandles(h.events.on("focus-changed",({action:m})=>{const n=this._tooltip;null!=n&&("focus"===m?this._updateMoveTooltip(b):n.clear())}))};this._moveManipulation.xyManipulation.forEachManipulator(k(l.ManipulationType.XY));this._moveManipulation.xyAxisManipulation.forEachManipulator(k(l.ManipulationType.XY_AXIS));this._moveManipulation.zManipulation.forEachManipulator(k(l.ManipulationType.Z));const e=G.getGraphicEffectiveElevationInfo(a);
this._moveManipulation.elevationInfo=e;this.addHandles(L.meshTransformFastUpdateHandles(this.graphicState));const {geometry:p}=a;this._moveManipulation.createGraphicDragPipeline((b,h,m,n,w)=>{if(null!=p&&b===l.ManipulationType.XY){const {snappingStep:t,cancelSnapping:ba}=Y.createSnapDragEventPipelineStep({snappingContext:new X.SnappingContext({elevationInfo:e,pointer:w,editGeometryOperations:W.EditGeometryOperations.fromGeometry(new F({spatialReference:p.spatialReference}),c.state.viewingMode),visualizer:new K.SnappingVisualizer3D,
excludeFeature:a}),snappingManager:this.snappingManager,updatingHandles:this._updatingHandles,useZ:!1});n=n.next(ba);m=m.next(U.sceneSnappingAtProjectedLocation(this.view,e)).next(...t)}m=m.next(t=>{this._updateMoveTooltip(b,t);return t});return{steps:m,cancel:n}},this.graphicState,b=>{const {action:h,graphic:m,dxScreen:n,dyScreen:w}=b;b={graphic:m,dxScreen:n,dyScreen:w};switch(h){case "start":this.emit("graphic-translate-start",b);this.emit("record-undo",{record:this._createGeometryUndoRecord()});
break;case "update":this.emit("graphic-translate",b);break;case "end":this.emit("graphic-translate-stop",b)}});this._moveManipulation.angle=null!=this._scaleRotate?this._scaleRotate.angle:0;this._scaleRotateAdapter=this._createScaleRotateAdapter();this.addHandles(q.watch(()=>this._scaleRotateAdapter.angle,()=>this._updateMoveAngle()));if(this.enableScaling||this.enableRotation)this._scaleRotate=new P.GraphicScaleRotateTransform({tool:this,mode:this.enableScaling&&this.enableRotation?null:this.enableScaling?
"scale":"rotate",adapter:this._scaleRotateAdapter,tooltipOptions:this.tooltipOptions}),this.addHandles(this._scaleRotate.events.on("scale-changed",()=>this._onScaleChanged()));this.addHandles([M.createVisualElements({view:this.view,graphic:this.graphic,forEachManipulator:b=>this._forEachManipulator(b),onManipulatorsChanged:()=>C.makeHandle()}),this.graphicState.on("changed",()=>this._onGeometryChanged()),this._hideManipulatorsForGraphicState(),q.watch(()=>c.scale,()=>this._updateMoveAngle())].filter(A.isSome));
this.addHandles(this.view.trackGraphicState(this.graphicState));this._onGeometryChanged();this._updateMoveAngle();this._forEachManipulator(b=>{b instanceof I.Manipulator3D&&this.addHandles(b.events.on("grab-changed",()=>this._updateManipulatorsInteractive()))});this.finishToolCreation()}destroy(){this._tooltip=r.destroyMaybe(this._tooltip);this._moveManipulation.destroy();this._scaleRotate=r.destroyMaybe(this._scaleRotate);this._scaleRotateAdapter=r.destroyMaybe(this._scaleRotateAdapter);this._updatingHandles.destroy();
this._set("view",null);this._set("graphic",null)}_updateManipulatorsInteractive(){null!=this._scaleRotate&&(this._scaleRotate.interactive=!this._moveManipulation.grabbing,this._moveManipulation.interactive=!this._scaleRotate.grabbing)}_createScaleRotateAdapter(){return null!=this.graphic.geometry&&"mesh"===this.graphic.geometry.type?new Q.ScaleRotateMeshAdapter({graphic:this.graphic,geometry:this.graphic.geometry,viewingMode:this.view.state.viewingMode}):new R.ScaleRotateObjectSymbol3DAdapter({graphic:this.graphic,
sizeFilter:a=>this._enforceNonZeroSize(a),findLayerView:()=>this.view.allLayerViews.find(a=>a.layer===this.graphic.layer),sizeAxis:this.tooltipOptions?.visualVariables?.size?.axis??null})}_forEachManipulator(a){this._moveManipulation?.forEachManipulator(a);this._scaleRotate?.forEachManipulator(a)}_hideManipulatorsForGraphicState(){return q.watch(()=>this.graphicState.displaying,a=>{this._forEachManipulator(c=>c.available=a);this._moveManipulation.zManipulation.available=a&&this.enableZ&&x.canMoveZ(this.graphic)})}_createGeometryUndoRecord(){return S.createGraphicGeometryUndoRecord(this.graphic)}set snapToScene(a){this._moveManipulation&&
(this._moveManipulation.snapToScene=a);this._set("snapToScene",a)}get updating(){return this._updatingHandles.updating||!!this._scaleRotate?.updating}set location(a){this._moveManipulation.location=a;this._scaleRotate&&(this._scaleRotate.location=a)}set elevationAlignedLocation(a){this._moveManipulation.elevationAlignedLocation=a;this._scaleRotate&&(this._scaleRotate.elevationAlignedLocation=a)}reset(){}onHide(){this._scaleRotate?.cancelActiveAnimation()}_onScaleChanged(){null!=this._scaleRotate&&
(this._moveManipulation.displayScale=this._scaleRotate.getScale())}_updateMoveAngle(){this._moveManipulation.angle=this.view.state.viewingMode===H.ViewingMode.Local||this.view.scale<N.alignArrowsScaleThreshold?this._scaleRotateAdapter.angle:0}_onGeometryChanged(){J.placeAtGraphic(this.view,this,this.graphic)}_enforceNonZeroSize(a){return a||this.view.state.camera.computeRenderPixelSizeAt(this._moveManipulation.renderLocation)}_updateMoveTooltip(a,c){const {tooltipOptions:k,_tooltip:e}=this;if(null!=
e){e.clear();var p=this.graphicState.isDraped?"on-the-ground":"absolute-height";switch(a){case l.ManipulationType.XY:e.info=this._translateGraphicTooltipInfo??(this._translateGraphicTooltipInfo=new v.TranslateGraphicTooltipInfo({tooltipOptions:k}));this._updateMoveTooltipDistance(e.info,c,(b,h)=>z.autoHorizontalDistanceByElevationModeBetweenPoints(b,h,p));break;case l.ManipulationType.XY_AXIS:e.info=this._translateGraphicXYTooltipInfo??(this._translateGraphicXYTooltipInfo=new v.TranslateGraphicXYTooltipInfo({tooltipOptions:k}));
this._updateMoveTooltipDistance(e.info,c,(b,h)=>{b=z.autoHorizontalDistanceByElevationModeBetweenPoints(b,h,p);return u.scale(b,O.axisConstrainedDragSign(c))});break;case l.ManipulationType.Z:e.info=this._translateGraphicZTooltipInfo??(this._translateGraphicZTooltipInfo=new v.TranslateGraphicZTooltipInfo({tooltipOptions:k})),this._updateMoveTooltipDistance(e.info,c,aa.verticalSignedDistanceBetweenPoints)}e.info.tooltipOptions=k}}_updateMoveTooltipDistance(a,c,k){if(null!=c&&"end"!==c.action){const {mapStart:e,
mapEnd:p}=c;c=k(e,p);a.distance=null!=c?c:u.zeroMeters}else a.distance=u.zeroMeters}get test(){return{discManipulator:this._moveManipulation.xyManipulation.test.discManipulator,zManipulator:this._moveManipulation.zManipulation.test.manipulator,ringManipulator:null!=this._scaleRotate?this._scaleRotate.test.ringManipulator:null,arrowManipulators:this._moveManipulation.xyAxisManipulation.test.arrowManipulators,setRingIndicatorDelayMs:a=>null!=this._scaleRotate?this._scaleRotate.test.setRingIndicatorDelayMs(a):
null,scaleRotateAdapter:this._scaleRotateAdapter,scaleRotateTransform:this._scaleRotate,tooltip:this._tooltip}}};f.__decorate([g.property({constructOnly:!0,nonNullable:!0})],d.GraphicTransformTool.prototype,"view",void 0);f.__decorate([g.property({constructOnly:!0,nonNullable:!0})],d.GraphicTransformTool.prototype,"graphic",void 0);f.__decorate([g.property({constructOnly:!0,nonNullable:!0})],d.GraphicTransformTool.prototype,"enableZ",void 0);f.__decorate([g.property()],d.GraphicTransformTool.prototype,
"enableRotation",void 0);f.__decorate([g.property()],d.GraphicTransformTool.prototype,"enableScaling",void 0);f.__decorate([g.property({constructOnly:!0,type:y})],d.GraphicTransformTool.prototype,"tooltipOptions",void 0);f.__decorate([g.property()],d.GraphicTransformTool.prototype,"graphicState",void 0);f.__decorate([g.property({value:!1})],d.GraphicTransformTool.prototype,"snapToScene",null);f.__decorate([g.property({constructOnly:!0})],d.GraphicTransformTool.prototype,"snappingManager",void 0);
f.__decorate([g.property({readOnly:!0})],d.GraphicTransformTool.prototype,"type",void 0);f.__decorate([g.property({readOnly:!0})],d.GraphicTransformTool.prototype,"updating",null);d.GraphicTransformTool=f.__decorate([D.subclass("esri.views.3d.interactive.editingTools.graphicTransform3D.GraphicTransformTool")],d.GraphicTransformTool);Object.defineProperty(d,Symbol.toStringTag,{value:"Module"})});