// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("require exports ../core/shaderLibrary/ShaderOutput ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../lib/TransparencyPassType ../lib/VertexAttribute ../../../../chunks/RibbonLine.glsl ../../../webgl/enums ../../../webgl/renderState".split(" "),function(t,h,m,u,v,f,w,b,n,c,x,p,d){const q=new Map([[c.VertexAttribute.POSITION,0],[c.VertexAttribute.SUBDIVISIONFACTOR,1],[c.VertexAttribute.UV0,
2],[c.VertexAttribute.AUXPOS1,3],[c.VertexAttribute.AUXPOS2,4],[c.VertexAttribute.COLOR,5],[c.VertexAttribute.COLORFEATUREATTRIBUTE,5],[c.VertexAttribute.SIZE,6],[c.VertexAttribute.SIZEFEATUREATTRIBUTE,6],[c.VertexAttribute.OPACITYFEATUREATTRIBUTE,7],[c.VertexAttribute.OBJECTANDLAYERIDCOLOR,8]]);class k extends v.ShaderTechnique{initializeProgram(a){return new w.Program(a.rctx,k.shader.get().build(this.configuration),q)}_makePipelineState(a,g){const e=this.configuration,l=a===n.TransparencyPassType.NONE,
y=a===n.TransparencyPassType.FrontFace;return d.makePipelineState({blending:e.output===m.ShaderOutput.Color||e.output===m.ShaderOutput.Alpha?l?f.blendingDefault:f.oitBlending(a):null,depthTest:{func:f.oitDepthTest(a)},depthWrite:l?e.writeDepth?d.defaultDepthWriteParams:null:f.oitDepthWrite(a),colorWrite:d.defaultColorWriteParams,stencilWrite:e.hasOccludees?b.stencilWriteMaskOn:null,stencilTest:e.hasOccludees?g?b.stencilToolMaskBaseParams:b.stencilBaseAllZerosParams:null,polygonOffset:l||y?e.hasPolygonOffset?
r:null:f.OITPolygonOffset})}initializePipeline(){var a=this.configuration;a.occluder&&(a=a.hasPolygonOffset?r:null,this._occluderPipelineTransparent=d.makePipelineState({blending:f.blendingDefault,polygonOffset:a,depthTest:b.depthCompareAlways,depthWrite:null,colorWrite:d.defaultColorWriteParams,stencilWrite:null,stencilTest:b.stencilToolTransparentOccluderParams}),this._occluderPipelineOpaque=d.makePipelineState({blending:f.blendingDefault,polygonOffset:a,depthTest:b.depthCompareAlways,depthWrite:null,
colorWrite:d.defaultColorWriteParams,stencilWrite:b.stencilWriteMaskOff,stencilTest:b.stencilToolMaskOccluderParams}),this._occluderPipelineMaskWrite=d.makePipelineState({blending:null,polygonOffset:a,depthTest:b.depthCompareLess,depthWrite:null,colorWrite:null,stencilWrite:b.stencilWriteMaskOn,stencilTest:b.stencilToolMaskBaseParams}));this._occludeePipelineState=this._makePipelineState(this.configuration.transparencyPassType,!0);return this._makePipelineState(this.configuration.transparencyPassType,
!1)}get primitiveType(){return this.configuration.wireframe?p.PrimitiveType.LINES:p.PrimitiveType.TRIANGLE_STRIP}getPipeline(a,g,e){return a?this._occludeePipelineState:this.configuration.occluder?e?this._occluderPipelineTransparent:g?this._occluderPipelineOpaque:this._occluderPipelineMaskWrite:super.getPipeline()}}k.shader=new u.ReloadableShaderModule(x.RibbonLine,()=>new Promise((a,g)=>t(["./RibbonLine.glsl"],a,g)));const r={factor:0,units:-4};h.RibbonLineTechnique=k;h.vertexAttributeLocations=
q;Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});