// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../core/CircularArray ./geohashUtils ../geometry/SpatialReference ../layers/graphics/featureConversionUtils ../layers/graphics/OptimizedGeometry ../layers/graphics/data/projectionSupport ../views/2d/layers/features/support/FeatureSetReaderJSON".split(" "),function(G,M,N,H,D,E,I,J){class O{constructor(b=[],a,e=8096){this.onRelease=d=>{};this._nodes=0;this._root=new F(this,0,0,0);this._statisticFields=b;this._pool=e?new M(8096):null;this._serviceInfo=a}destroy(){this.clear()}_acquire(b,
a,e){this._nodes++;let d=null;null!=this._pool&&(d=this._pool.dequeue());null!=d?d.realloc(b,a,e):d=new F(this,b,a,e);return d}_release(b){this.onRelease(b);this._nodes--;null!=this._pool&&this._pool.enqueue(b)}get count(){return this._root.count}get size(){return this._nodes}get poolSize(){return this._pool?.size??0}get depth(){let b=0;this.forEach(a=>b=Math.max(b,a.depth));return b}dropLevels(b){this.forEach(a=>{if(a.depth>=b)for(let e=0;e<a.children.length;e++){const d=a.children[e];d&&this._release(d)}});
this.forEach(a=>{if(a.depth>=b)for(let e=0;e<a.children.length;e++)a.children[e]=null})}clear(){this.forEach(b=>this._release(b));this._root=new F(this,0,0,0)}insert(b,a,e=0){const d=J.FeatureSetReaderJSON.fromOptimizedFeatures([b],this._serviceInfo).getCursor();d.next();const g=d.readGeometry();if(g){var [f,c]=g.coords;this.insertCursor(d,b.displayId,f,c,b.geohashX,b.geohashY,a,e)}}insertCursor(b,a,e,d,g,f,c,m=0){let h=this._root,l=0,n=0,r=0;for(;null!==h;){h.depth>=m&&(h.count+=1,h.xTotal+=e,h.yTotal+=
d,h.xGeohashTotal+=g,h.yGeohashTotal+=f,h.referenceId=a,this._updateStatisticsCursor(b,h,1));if(l>=c){h.add(a);break}var q=Math.ceil((l+1)/2),k=Math.floor((l+1)/2);const t=1-l%2;var p=30-(3*q+2*k);q=30-(2*q+3*k);p=(g&7*t+3*(1-t)<<p)>>p;q=(f&3*t+7*(1-t)<<q)>>q;k=p+q*(8*t+4*(1-t));const u=2*t+3*(1-t);n=n<<3*t+2*(1-t)|p;r=r<<u|q;null==h.children[k]&&(h.children[k]=this._acquire(n,r,l+1));l+=1;h=h.children[k]}}remove(b,a){const e=J.FeatureSetReaderJSON.fromOptimizedFeatures([b],this._serviceInfo).getCursor();
e.next();const d=e.readGeometry();if(d){var [g,f]=d.coords;this.removeCursor(e,g,f,b.geohashX,b.geohashY,a)}}removeCursor(b,a,e,d,g,f){let c=this._root,m=0;for(;null!==c;){--c.count;c.xTotal-=a;c.yTotal-=e;c.xGeohashTotal-=d;c.yGeohashTotal-=g;this._updateStatisticsCursor(b,c,-1);if(m>=f){c.remove(b.getDisplayId());break}var h=Math.ceil((m+1)/2);const r=Math.floor((m+1)/2);var l=1-m%2,n=30-(3*h+2*r);h=30-(2*h+3*r);l=((d&7*l+3*(1-l)<<n)>>n)+((g&3*l+7*(1-l)<<h)>>h)*(8*l+4*(1-l));n=c.children[l];1===
n?.count&&(this._release(n),c.children[l]=null);m+=1;c=n}}forEach(b){let a=this._root;for(;null!==a;){const e=this._linkChildren(a)||a.next;b(a);a=e}}find(b,a,e){return this._root.find(b,a,e,0,0,0)}findIf(b){let a=null;this.forEach(e=>{b(e)&&(a=e)});return a}findAllIf(b){const a=[];this.forEach(e=>{b(e)&&a.push(e)});return a}findSingleOccupancyNode(b,a,e,d,g){let f=this._root;for(;null!==f;){var c=f.depth,m=f.xNode,h=f.yNode;const p=1-c%2;var l=f.xGeohashTotal/f.count,n=f.yGeohashTotal/f.count;if(1===
f.count&&b<l&&l<=e&&a<n&&n<=d)return f;if(c>=g)f=f.next;else{n=Math.ceil((c+1)/2);c=Math.floor((c+1)/2);l=30-(3*n+2*c);var r=30-(2*n+3*c),q=~((1<<l)-1),k=~((1<<r)-1);m<<=3*p+2*(1-p);h<<=2*p+3*(1-p);c=Math.max(m,(b&q)>>l);n=Math.max(h,(a&k)>>r);l=Math.min(m+8*p+4*(1-p),(e&q)>>l);r=Math.min(h+4*p+8*(1-p),(d&k)>>r);for(q=k=null;n<=r;n++)for(let t=c;t<=l;t++){const u=f.children[t-m+(n-h)*(8*p+4*(1-p))];u&&(k||(k=u,k.next=f.next),q&&(q.next=u),q=u,u.next=f.next)}f=k||f.next}}return null}getRegionDisplayIds(b){let a=
this._root;const {bounds:e,geohashBounds:d,level:g}=b,[f,c,m,h]=e,l=[];for(;null!==a;){b=a.depth;var n=a.xNode,r=a.yNode;if(b>=g)b=a.xTotal/a.count,n=a.yTotal/a.count,b>=f&&b<=m&&n>=c&&n<=h&&a.displayIds.forEach(x=>l.push(x)),a=a.next;else{var q=Math.ceil((b+1)/2),k=Math.floor((b+1)/2);b=1-b%2;var p=30-(3*q+2*k),t=30-(2*q+3*k),u=~((1<<p)-1),v=~((1<<t)-1);n<<=3*b+2*(1-b);r<<=2*b+3*(1-b);q=Math.max(n,(d.xLL&u)>>p);k=Math.max(r,(d.yLL&v)>>t);p=Math.min(n+8*b+4*(1-b),(d.xTR&u)>>p);t=Math.min(r+4*b+8*
(1-b),(d.yTR&v)>>t);for(u=v=null;k<=t;k++)for(let x=q;x<=p;x++){const y=a.children[x-n+(k-r)*(8*b+4*(1-b))];y&&(v||(v=y,v.next=a.next),u&&(u.next=y),u=y,y.next=a.next)}a=v||a.next}}return l}getRegionStatistics(b){var a=this._root;let e=0,d=0,g=0;const f={},{bounds:c,geohashBounds:m,level:h}=b,[l,n,r,q]=c;for(b=0;null!==a;){var k=a.depth,p=a.xNode,t=a.yNode;if(k>=h)k=a.xTotal/a.count,p=a.yTotal/a.count,k>l&&k<=r&&p>n&&p<=q&&(e+=a.count,d+=a.xTotal,g+=a.yTotal,1===a.count&&(b=a.referenceId),this._aggregateStatistics(f,
a.statistics)),a=a.next;else{var u=Math.ceil((k+1)/2),v=Math.floor((k+1)/2);k=1-k%2;var x=30-(3*u+2*v),y=30-(2*u+3*v),A=~((1<<x)-1),z=~((1<<y)-1);p<<=3*k+2*(1-k);t<<=2*k+3*(1-k);u=Math.max(p,(m.xLL&A)>>x);v=Math.max(t,(m.yLL&z)>>y);x=Math.min(p+8*k+4*(1-k),(m.xTR&A)>>x);y=Math.min(t+4*k+8*(1-k),(m.yTR&z)>>y);A=z=null;for(let B=v;B<=y;B++)for(let C=u;C<=x;C++){const w=a.children[C-p+(B-t)*(8*k+4*(1-k))];if(w)if(B!==v&&B!==y&&C!==u&&C!==x){const K=w.xTotal/w.count,L=w.yTotal/w.count;K>l&&K<=r&&L>n&&
L<=q&&(e+=w.count,d+=w.xTotal,g+=w.yTotal,1===w.count&&(b=w.referenceId),this._aggregateStatistics(f,w.statistics))}else z||(z=w,z.next=a.next),A&&(A.next=w),A=w,w.next=a.next}a=z||a.next}}a=this.normalizeStatistics(f,e);return{count:e,attributes:a,xTotal:d,yTotal:g,referenceId:b}}getBins(b){const a=[],{geohashBounds:e,level:d}=b;for(b=this._root;null!==b;){var g=b.depth,f=b.xNode,c=b.yNode;if(g>=d)a.push(b),b=b.next;else{var m=Math.ceil((g+1)/2),h=Math.floor((g+1)/2);g=1-g%2;var l=30-(3*m+2*h),n=
30-(2*m+3*h),r=~((1<<l)-1),q=~((1<<n)-1);f<<=3*g+2*(1-g);c<<=2*g+3*(1-g);m=Math.max(f,(e.xLL&r)>>l);h=Math.max(c,(e.yLL&q)>>n);l=Math.min(f+8*g+4*(1-g),(e.xTR&r)>>l);n=Math.min(c+4*g+8*(1-g),(e.yTR&q)>>n);for(r=q=null;h<=n;h++)for(let k=m;k<=l;k++){const p=b.children[k-f+(h-c)*(8*g+4*(1-g))];p&&(q||(q=p,q.next=b.next),r&&(r.next=p),r=p,p.next=b.next)}b=q||b.next}}return a}_linkChildren(b){let a=null,e=null;for(let d=0;d<=b.children.length;d++){const g=b.children[d];g&&(a||(a=g,a.next=b.next),e&&(e.next=
g),e=g,g.next=b.next)}return a}_updateStatisticsCursor(b,a,e){for(const f of this._statisticFields){const c=f.name,m=f.inField?b.readAttribute(f.inField):b.getComputedNumericAtIndex(f.inFieldIndex);switch(f.statisticType){case "min":if(isNaN(m))break;if(!a.statistics[c]){a.statistics[c]={value:m};break}a.statistics[c].value=Math.min(a.statistics[c].value,m);break;case "max":if(isNaN(m))break;if(!a.statistics[c]){a.statistics[c]={value:m};break}a.statistics[c].value=Math.max(a.statistics[c].value,
m);break;case "sum":case "avg":a.statistics[c]||(a.statistics[c]={value:0,nanCount:0});var d=a.statistics[c].value,g=a.statistics[c].nanCount??0;null==m||isNaN(m)?a.statistics[c].nanCount=g+e:a.statistics[c].value=d+e*m;break;case "avg_angle":a.statistics[c]||(a.statistics[c]={x:0,y:0,nanCount:0});d=a.statistics[c].x;g=a.statistics[c].y;const h=a.statistics[c].nanCount??0,l=Math.PI/180;null==m||isNaN(m)?a.statistics[c].nanCount=h+e:(a.statistics[c].x=d+e*Math.cos(m*l),a.statistics[c].y=g+e*Math.sin(m*
l));break;case "mode":a.statistics[c]||(a.statistics[c]={}),a.statistics[c][m]=(a.statistics[c][m]||0)+e}}}_aggregateStatistics(b,a){for(const e of this._statisticFields){const d=e.name;switch(e.statisticType){case "min":if(!b[d]){b[d]={value:a[d].value};break}b[d].value=Math.min(b[d].value,a[d].value);break;case "max":if(!b[d]){b[d]={value:a[d].value};break}b[d].value=Math.max(b[d].value,a[d].value);break;case "sum":case "avg":case "avg_angle":case "mode":b[d]||(b[d]={});for(const g in a[d])b[d][g]=
(b[d][g]||0)+a[d][g]}}}normalizeStatistics(b,a){const e={};for(const g of this._statisticFields){const f=g.name;switch(g.statisticType){case "min":case "max":var d=b[f];if(!a||!d)break;e[f]=d.value;break;case "count":if(!a)break;e[f]=a;break;case "sum":if(!a)break;const {value:c,nanCount:m}=b[f];if(!(a-m))break;e[f]=c;break;case "avg":if(!a)break;const {value:h,nanCount:l}=b[f];if(!(a-l))break;e[f]=h/(a-l);break;case "avg_angle":if(!a)break;const {x:n,y:r,nanCount:q}=b[f];if(!(a-q))break;e[f]=180/
Math.PI*Math.atan2(r/(a-q),n/(a-q));break;case "mode":d=b[f];let k=0,p=0,t=null;for(const u in d){const v=d[u];v===k?p+=1:v>k&&(k=v,p=1,t=u)}e[f]="null"===t||1<p?null:t}}return e}}class F{constructor(b,a,e,d){this.yTotal=this.xTotal=this.count=0;this.statistics={};this.referenceId=this.displayId=0;this.displayIds=new Set;this.next=null;this.yGeohashTotal=this.xGeohashTotal=this.yNode=this.xNode=this.depth=0;this._tree=b;this.children=Array(32);for(b=0;b<this.children.length;b++)this.children[b]=null;
this.xNode=a;this.yNode=e;this.depth=d}realloc(b,a,e){for(let d=0;d<this.children.length;d++)this.children[d]=null;this.xNode=b;this.yNode=a;this.depth=e;this.next=null;this.count=this.yTotal=this.xTotal=this.referenceId=this.displayId=this.yGeohashTotal=this.xGeohashTotal=0;this.statistics={};this.displayIds.clear();return this}get id(){return`${this.xNode}.${this.yNode}`}add(b){this.displayIds.add(b)}remove(b){this.displayIds.delete(b)}getAttributes(){const b=this._tree.normalizeStatistics(this.statistics,
this.count);b.referenceId=null;b.aggregateId=this.id;b.aggregateCount=this.count;return b}getGeometry(b,a){const e=this.getLngLatBounds(),[d,g,f,c]=e;b=I.project({rings:[[[d,g],[d,c],[f,c],[f,g],[d,g]]]},H.WGS84,b);b=D.convertFromPolygon(new E,b,!1,!1);return null!=a?D.quantizeOptimizedGeometry(new E,b,!1,!1,"esriGeometryPolygon",a,!1,!1):b}getGeometryCentroid(b,a){const e=this.getLngLatBounds(),[d,g,f,c]=e;b=I.project({x:(d+f)/2,y:(g+c)/2},H.WGS84,b);b=D.convertFromPoint(new E,b);return null!=a?
D.quantizeOptimizedGeometry(new E,b,!1,!1,"esriGeometryPoint",a,!1,!1):b}getLngLatBounds(){var b=this.depth;const a=Math.ceil(b/2);b=Math.floor(b/2);return N.decodeGeohashXY({geohashX:this.xNode<<30-(3*a+2*b),geohashY:this.yNode<<30-(2*a+3*b)},this.depth)}find(b,a,e,d,g,f){if(d>=e)return this;var c=1-d%2;const m=3*c+2*(1-c),h=2*c+3*(1-c),l=30-g-m,n=30-f-h;c=this.children[((b&7*c+3*(1-c)<<l)>>l)+((a&3*c+7*(1-c)<<n)>>n)*(8*c+4*(1-c))];return null==c?null:c.find(b,a,e,d+1,g+m,f+h)}}G.GeohashNode=F;G.GeohashTree=
O;Object.defineProperty(G,Symbol.toStringTag,{value:"Module"})});