// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
require({cache:{"esri/geometry/support/DoubleArray":function(){define(["exports","../../core/typedArrayUtil"],function(e,p){e.copyInto=function(A,z){for(let D=0;D<z.length;++D)A[D]=z[D];return A};e.doubleArrayFrom=function(A){return(p.isArray(A)?A.length:A.byteLength/8)<=p.nativeArrayMaxSize?Array.from(A):new Float64Array(A)};e.doubleSubArray=function(A,z,D){return Array.isArray(A)?A.slice(z,z+D):A.subarray(z,z+D)};e.newDoubleArray=function(A,z=!1){return A<=p.nativeArrayMaxSize?z?Array(A).fill(0):
Array(A):new Float64Array(A)};e.toFloat64Array=function(A){return Array.isArray(A)?new Float64Array(A):A};Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/MeshGeoreferencedRelativeVertexSpace":function(){define("../../chunks/tslib.es6 ../../core/Clonable ../../core/JSONSupport ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/enumeration ../../core/accessorSupport/decorators/subclass ../../chunks/vec3f64 ../Point".split(" "),
function(e,p,A,z,D,n,B,x,M,N,Q){p=class extends p.ClonableMixin(A.JSONSupport){constructor(w){super(w);this.type="georeferenced-relative";this.isGeoreferenced=this.isRelative=!0;this.origin=N.create()}getOriginPoint(w){const [u,v,C]=this.origin;return new Q({x:u,y:v,z:C,spatialReference:w})}setOriginFromPoint({x:w,y:u,z:v}){this.origin=N.fromValues(w,u,v??0)}};e.__decorate([x.enumeration({georeferencedRelative:"georeferenced-relative"},{readOnly:!0})],p.prototype,"type",void 0);e.__decorate([z.property({type:[Number],
nonNullable:!0,json:{write:!0}})],p.prototype,"origin",void 0);return p=e.__decorate([M.subclass("esri.geometry.support.MeshGeoreferencedRelativeVertexSpace")],p)})},"esri/core/Clonable":function(){define("exports ../chunks/tslib.es6 ./Accessor ./has ./lang ./Logger ./maybe ./accessorSupport/PropertyOrigin ./accessorSupport/utils ./accessorSupport/decorators/subclass".split(" "),function(e,p,A,z,D,n,B,x,M,N){z=Q=>{Q=class extends Q{clone(){var w=M.getProperties(this);B.assertIsSome(w,"unable to clone instance of non-accessor class");
var u=w.metadatas;const v=w.store,C={};w=new Map;for(var J in u){var R=u[J];const E=v?.originOf(J),S=R.clonable;if(R.readOnly||!1===S||E!==x.OriginId.USER&&E!==x.OriginId.DEFAULTS&&E!==x.OriginId.WEB_MAP&&E!==x.OriginId.WEB_SCENE)continue;R=this[J];let q=null;q="function"===typeof S?S(R):"reference"===S?R:D.tryClone(R);if(null==R||null!=q)E===x.OriginId.DEFAULTS?w.set(J,q):C[J]=q}u=new (Object.getPrototypeOf(this).constructor)(C);if(w.size&&(J=M.getProperties(u)?.store))for(const [E,S]of w)J.set(E,
S,x.OriginId.DEFAULTS);return u}};return Q=p.__decorate([N.subclass("esri.core.Clonable")],Q)};e.Clonable=class extends z(A){};e.Clonable=p.__decorate([N.subclass("esri.core.Clonable")],e.Clonable);e.ClonableMixin=z;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/core/accessorSupport/decorators/enumeration":function(){define(["exports","../../jsonMap","./property"],function(e,p,A){e.enumeration=function(z,D={}){z=z instanceof p.JSONMap?z:new p.JSONMap(z,D);z={type:D?.ignoreUnknown??
!0?z.apiValues:String,json:{type:z.jsonValues,read:D?.readOnly?!1:{reader:z.read},write:{writer:z.write}}};void 0!==D?.readOnly&&(z.readOnly=!!D.readOnly);void 0!==D?.default&&(z.json.default=D.default);void 0!==D?.name&&(z.json.name=D.name);void 0!==D?.nonNullable&&(z.nonNullable=D.nonNullable);return A.property(z)};Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/MeshLocalVertexSpace":function(){define("../../chunks/tslib.es6 ../../core/Clonable ../../core/JSONSupport ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/enumeration ../../core/accessorSupport/decorators/subclass ../../chunks/vec3f64 ../Point".split(" "),
function(e,p,A,z,D,n,B,x,M,N,Q){p=class extends p.ClonableMixin(A.JSONSupport){constructor(w){super(w);this.type="local";this.isRelative=!0;this.isGeoreferenced=!1;this.origin=N.create()}getOriginPoint(w){const [u,v,C]=this.origin;return new Q({x:u,y:v,z:C,spatialReference:w})}setOriginFromPoint({x:w,y:u,z:v}){this.origin=N.fromValues(w,u,v??0)}};e.__decorate([x.enumeration({local:"local"},{readOnly:!0})],p.prototype,"type",void 0);e.__decorate([z.property({type:[Number],nonNullable:!0,json:{write:!0}})],
p.prototype,"origin",void 0);return p=e.__decorate([M.subclass("esri.geometry.support.MeshLocalVertexSpace")],p)})},"esri/chunks/vec32":function(){define(["exports","../geometry/support/buffer/math/common"],function(e,p){function A(u,v,C){z(u.typedBuffer,v.typedBuffer,C,u.typedBufferStride,v.typedBufferStride)}function z(u,v,C,J=3,R=J){if(u.length/J!==Math.ceil(v.length/R))return p.mathLogger.error("source and destination buffers need to have the same number of elements"),u;const E=u.length/J,S=C[0],
q=C[1],H=C[2],I=C[4],U=C[5],Z=C[6],ma=C[8],fa=C[9],Y=C[10],na=C[12],oa=C[13];C=C[14];let ha=0,ea=0;for(let ka=0;ka<E;ka++){const aa=v[ha],ia=v[ha+1],O=v[ha+2];u[ea]=S*aa+I*ia+ma*O+na;u[ea+1]=q*aa+U*ia+fa*O+oa;u[ea+2]=H*aa+Z*ia+Y*O+C;ha+=R;ea+=J}return u}function D(u,v,C){n(u.typedBuffer,v.typedBuffer,C,u.typedBufferStride,v.typedBufferStride)}function n(u,v,C,J=3,R=J){if(u.length/J!==Math.ceil(v.length/R))p.mathLogger.error("source and destination buffers need to have the same number of elements");
else{var E=u.length/J,S=C[0],q=C[1],H=C[2],I=C[3],U=C[4],Z=C[5],ma=C[6],fa=C[7];C=C[8];var Y=0,na=0;for(let oa=0;oa<E;oa++){const ha=v[Y],ea=v[Y+1],ka=v[Y+2];u[na]=S*ha+I*ea+ma*ka;u[na+1]=q*ha+U*ea+fa*ka;u[na+2]=H*ha+Z*ea+C*ka;Y+=R;na+=J}}}function B(u,v,C){x(u.typedBuffer,v,C,u.typedBufferStride)}function x(u,v,C,J=3){const R=Math.min(u.length/J,v.count),E=v.typedBuffer;v=v.typedBufferStride;let S=0,q=0;for(let H=0;H<R;H++)u[q]=C*E[S],u[q+1]=C*E[S+1],u[q+2]=C*E[S+2],S+=v,q+=J}function M(u,v){N(u.typedBuffer,
v.typedBuffer,u.typedBufferStride,v.typedBufferStride)}function N(u,v,C=3,J=C){const R=Math.min(u.length/C,v.length/J);let E=0,S=0;for(let H=0;H<R;H++){const I=v[E],U=v[E+1],Z=v[E+2];var q=I*I+U*U+Z*Z;0<q&&(q=1/Math.sqrt(q),u[S]=q*I,u[S+1]=q*U,u[S+2]=q*Z);E+=J;S+=C}}function Q(u,v,C){const J=Math.min(u.count,v.count),R=u.typedBuffer;u=u.typedBufferStride;const E=v.typedBuffer;v=v.typedBufferStride;let S=0,q=0;for(let H=0;H<J;H++)R[q]=E[S]>>C,R[q+1]=E[S+1]>>C,R[q+2]=E[S+2]>>C,S+=v,q+=u}const w=Object.freeze(Object.defineProperty({__proto__:null,
normalize:N,normalizeView:M,scale:x,scaleView:B,shiftRight:Q,transformMat3:n,transformMat3View:D,transformMat4:z,transformMat4View:A},Symbol.toStringTag,{value:"Module"}));e.normalize=N;e.normalizeView=M;e.scale=x;e.scaleView=B;e.shiftRight=Q;e.transformMat3=n;e.transformMat3View=D;e.transformMat4=z;e.transformMat4View=A;e.vec3=w})},"esri/geometry/support/buffer/math/common":function(){define(["exports","../../../../core/Logger"],function(e,p){p=p.getLogger("esri.views.3d.support.buffer.math");e.mathLogger=
p;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/libs/i3s/enums":function(){define(["exports"],function(e){e.IndexType=void 0;(function(p){p[p.None=0]="None";p[p.Int16=1]="Int16";p[p.Int32=2]="Int32"})(e.IndexType||(e.IndexType={}));e.ModificationType=void 0;(function(p){p[p.Replace=0]="Replace";p[p.Outside=1]="Outside";p[p.Inside=2]="Inside";p[p.Finished=3]="Finished"})(e.ModificationType||(e.ModificationType={}));Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},
"esri/libs/i3s/I3SModule":function(){define(["require","exports","../../assets"],function(e,p,A){function z(n){return A.getAssetUrl(`esri/libs/i3s/${n}`)}let D;p.get=function(){D||(D=(new Promise(n=>(new Promise((B,x)=>e(["../../chunks/i3s"],B,x))).then(B=>B.i3s).then(({default:B})=>{const x=B({locateFile:z,onRuntimeInitialized:()=>n(x)});delete x.then}))).catch(n=>{throw n;}));return D};Object.defineProperty(p,Symbol.toStringTag,{value:"Module"})})},"esri/views/3d/layers/i3s/I3SNode":function(){define(["exports",
"../../../../chunks/sphere"],function(e,p){class A{constructor(n,B){this.id=n;this.mbs=B;this.renderMbs=p.fromValues(0,0,0,-1);this.elevationRangeMax=this.elevationRangeMin=NaN}invalidateElevationRange(){this.elevationRangeMin=NaN}}e.NodeFilterImpact=void 0;(function(n){n[n.Unmodified=0]="Unmodified";n[n.Culled=1]="Culled";n[n.NotChecked=2]="NotChecked"})(e.NodeFilterImpact||(e.NodeFilterImpact={}));e.NodeIMModificationImpact=void 0;(function(n){n[n.Unmodified=0]="Unmodified";n[n.PotentiallyModified=
1]="PotentiallyModified";n[n.Culled=2]="Culled";n[n.Unknown=3]="Unknown";n[n.NotChecked=4]="NotChecked"})(e.NodeIMModificationImpact||(e.NodeIMModificationImpact={}));class z extends A{constructor(n,B,x,M,N,Q,w,u,v,C){super(n,x);this.index=B;this.childCount=M;this.level=N;this.resources=Q;this.version=w;this.lodMetric=u;this.maxError=v;this.numFeatures=C;this.failed=!1;this.cacheState=e.CacheState.Unknown;this.childrenLoaded=this.memory=this.vertexCount=0;this.hasModifications=!1;this.imModificationImpact=
e.NodeIMModificationImpact.NotChecked}}e.CacheState=void 0;(function(n){n[n.Unknown=0]="Unknown";n[n.Uncached=1]="Uncached";n[n.Cached=2]="Cached"})(e.CacheState||(e.CacheState={}));e.LodMetric=void 0;(function(n){n[n.None=0]="None";n[n.MaxScreenThreshold=1]="MaxScreenThreshold";n[n.ScreenSpaceRelative=2]="ScreenSpaceRelative";n[n.RemovedFeatureDiameter=3]="RemovedFeatureDiameter";n[n.DistanceRangeFromDefaultCamera=4]="DistanceRangeFromDefaultCamera"})(e.LodMetric||(e.LodMetric={}));e.NodeState=void 0;
(function(n){n[n.Hole=0]="Hole";n[n.Leaf=1]="Leaf"})(e.NodeState||(e.NodeState={}));class D{constructor(n,B,x,M){this.nodeHasLOD=n;this.isChosen=B;this.lodLevel=x;this.version=M}}e.Node=z;e.NodeBase=A;e.NodeTraversalState=D;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/chunks/sphere":function(){define("exports ../core/has ../core/Logger ../core/mathUtils ./mat4 ./vec3 ./vec3f64 ./vec4 ./vec4f64 ./common ../geometry/support/Axis ../geometry/support/ray ../geometry/support/vector ../geometry/support/vectorStacks".split(" "),
function(e,p,A,z,D,n,B,x,M,N,Q,w,u,v){function C(){return M.create()}function J(r,a=C()){return x.copy(a,r)}function R(r,a){return M.fromValues(r[0],r[1],r[2],a)}function E(r){return r}function S(r){r[0]=r[1]=r[2]=r[3]=0}function q(r,a){r[0]=r[1]=r[2]=0;r[3]=a;return r}function H(r){return r[3]}function I(r){return r}function U(r,a,b,c){return M.fromValues(r,a,b,c)}function Z(r,a,b){r!==b&&n.copy(b,r);b[3]=r[3]+a;return b}function ma(r,a,b){A.getLogger("esri.geometry.support.sphere").error("sphere.setExtent is not yet supported");
return r===b?b:J(r,b)}function fa(r,a,b){if(null==a||!na(r,a,Ba))return!1;let {t0:c,t1:d}=Ba;if(0>c||d<c&&0<d)c=d;if(0>c)return!1;if(b){const {origin:f,direction:g}=a;b[0]=f[0]+g[0]*c;b[1]=f[1]+g[1]*c;b[2]=f[2]+g[2]*c}return!0}function Y(r,a,b){a=w.fromPoints(a,b);if(!na(r,a,Ba))return[];const {origin:c,direction:d}=a,{t0:f,t1:g}=Ba;a=k=>{const l=B.create();n.scaleAndAdd(l,c,d,k);return aa(r,l,l)};return Math.abs(f-g)<N.getEpsilon()?[a(f)]:[a(f),a(g)]}function na(r,a,b){const {origin:c,direction:d}=
a,f=Fa;f[0]=c[0]-r[0];f[1]=c[1]-r[1];f[2]=c[2]-r[2];a=d[0]*d[0]+d[1]*d[1]+d[2]*d[2];if(0===a)return!1;const g=2*(d[0]*f[0]+d[1]*f[1]+d[2]*f[2]);r=g*g-4*a*(f[0]*f[0]+f[1]*f[1]+f[2]*f[2]-r[3]*r[3]);if(0>r)return!1;r=Math.sqrt(r);b.t0=(-g-r)/(2*a);b.t1=(-g+r)/(2*a);return!0}function oa(r,a){return fa(r,a,null)}function ha(r,a,b){if(fa(r,a,b))return b;r=ea(r,a,v.sv3d.get());n.add(b,a.origin,n.scale(v.sv3d.get(),a.direction,n.distance(a.origin,r)/n.length(a.direction)));return b}function ea(r,a,b){const c=
v.sv3d.get(),d=v.sm4d.get();n.cross(c,a.origin,a.direction);const f=r[3];n.cross(b,c,a.origin);n.scale(b,b,1/n.length(b)*f);r=O(r,a.origin);a=u.angle(a.origin,b);D.fromRotation(d,a+r,c);n.transformMat4(b,b,d);return b}function ka(r,a,b){if(fa(r,a,b))return b;w.closestPoint(a,r,b);return aa(r,b,b)}function aa(r,a,b){a=n.subtract(v.sv3d.get(),a,r);a=n.scale(v.sv3d.get(),a,r[3]/n.length(a));return n.add(b,a,r)}function ia(r,a){a=n.subtract(v.sv3d.get(),a,r);a=n.squaredLength(a);return Math.sqrt(Math.abs(a-
r[3]*r[3]))}function O(r,a){a=n.subtract(v.sv3d.get(),a,r);a=n.length(a);r=r[3];return z.acosClamped(r/(r+Math.abs(r-a)))}function ca(r,a,b,c){r=n.subtract(Ca,a,r);switch(b){case Q.Axis.X:return b=z.cartesianToSpherical(r,Ca)[2],n.set(c,-Math.sin(b),Math.cos(b),0);case Q.Axis.Y:return r=z.cartesianToSpherical(r,Ca),b=r[1],r=r[2],a=Math.sin(b),n.set(c,-a*Math.cos(r),-a*Math.sin(r),Math.cos(b));case Q.Axis.Z:return n.normalize(c,r)}}function ja(r,a){a=n.subtract(Da,a,r);return n.length(a)-r[3]}function la(r,
a,b,c){const d=ja(r,a);r=ca(r,a,Q.Axis.Z,Da);b=n.scale(Da,r,b-d);return n.add(c,a,b)}function za(r,a){a=n.squaredDistance(r,a);r=r[3];return a<=r*r}function Aa(r,a,b=C()){const c=n.distance(r,a),d=r[3],f=a[3];if(c+f<d)return x.copy(b,r),b;if(c+d<f)return x.copy(b,a),b;n.lerp(b,r,a,(c+f-d)/(2*c));b[3]=(c+d+f)/2;return b}p=C();const ya=x.equals,qa=x.equals,Ba={t0:0,t1:0},Fa=B.create(),Ca=B.create(),Da=B.create(),Ea=C(),Ga=Object.freeze(Object.defineProperty({__proto__:null,NullSphere:p,altitudeAt:ja,
angleToSilhouette:O,axisAt:ca,clear:S,closestPoint:ka,closestPointOnSilhouette:ea,containsPoint:za,copy:J,create:C,distanceToSilhouette:ia,elevate:Z,equals:qa,exactEquals:ya,fromCenterAndRadius:R,fromRadius:q,fromValues:U,getCenter:I,getRadius:H,intersectLine:Y,intersectRay:fa,intersectRayClosestSilhouette:ha,intersectsRay:oa,projectPoint:aa,setAltitudeAt:la,setExtent:ma,tmpSphere:Ea,union:Aa,wrap:E},Symbol.toStringTag,{value:"Module"}));e.NullSphere=p;e.altitudeAt=ja;e.angleToSilhouette=O;e.axisAt=
ca;e.clear=S;e.closestPoint=ka;e.closestPointOnSilhouette=ea;e.containsPoint=za;e.copy=J;e.create=C;e.distanceToSilhouette=ia;e.elevate=Z;e.equals=qa;e.exactEquals=ya;e.fromCenterAndRadius=R;e.fromRadius=q;e.fromValues=U;e.getCenter=I;e.getRadius=H;e.intersectLine=Y;e.intersectRay=fa;e.intersectRayClosestSilhouette=ha;e.intersectsRay=oa;e.projectPoint=aa;e.setAltitudeAt=la;e.setExtent=ma;e.sphere=Ga;e.tmpSphere=Ea;e.union=Aa;e.wrap=E})},"esri/chunks/mat4":function(){define(["exports","./vec3f64",
"./common"],function(e,p,A){function z(a,b){a[0]=b[0];a[1]=b[1];a[2]=b[2];a[3]=b[3];a[4]=b[4];a[5]=b[5];a[6]=b[6];a[7]=b[7];a[8]=b[8];a[9]=b[9];a[10]=b[10];a[11]=b[11];a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a}function D(a,b,c,d,f,g,k,l,h,m,t,y,G,F,P,L,K){a[0]=b;a[1]=c;a[2]=d;a[3]=f;a[4]=g;a[5]=k;a[6]=l;a[7]=h;a[8]=m;a[9]=t;a[10]=y;a[11]=G;a[12]=F;a[13]=P;a[14]=L;a[15]=K;return a}function n(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=
0;a[13]=0;a[14]=0;a[15]=1;return a}function B(a,b){if(a===b){const c=b[1],d=b[2],f=b[3],g=b[6],k=b[7],l=b[11];a[1]=b[4];a[2]=b[8];a[3]=b[12];a[4]=c;a[6]=b[9];a[7]=b[13];a[8]=d;a[9]=g;a[11]=b[14];a[12]=f;a[13]=k;a[14]=l}else a[0]=b[0],a[1]=b[4],a[2]=b[8],a[3]=b[12],a[4]=b[1],a[5]=b[5],a[6]=b[9],a[7]=b[13],a[8]=b[2],a[9]=b[6],a[10]=b[10],a[11]=b[14],a[12]=b[3],a[13]=b[7],a[14]=b[11],a[15]=b[15];return a}function x(a,b){M(a,b)||n(a);return a}function M(a,b){const c=b[0],d=b[1],f=b[2],g=b[3],k=b[4],l=
b[5],h=b[6],m=b[7],t=b[8],y=b[9],G=b[10],F=b[11],P=b[12],L=b[13],K=b[14];b=b[15];const ba=c*l-d*k,T=c*h-f*k,V=c*m-g*k,W=d*h-f*l,X=d*m-g*l,ra=f*m-g*h,sa=t*L-y*P,ta=t*K-G*P,ua=t*b-F*P,va=y*K-G*L,wa=y*b-F*L,xa=G*b-F*K;let da=ba*xa-T*wa+V*va+W*ua-X*ta+ra*sa;if(!da)return null;da=1/da;a[0]=(l*xa-h*wa+m*va)*da;a[1]=(f*wa-d*xa-g*va)*da;a[2]=(L*ra-K*X+b*W)*da;a[3]=(G*X-y*ra-F*W)*da;a[4]=(h*ua-k*xa-m*ta)*da;a[5]=(c*xa-f*ua+g*ta)*da;a[6]=(K*V-P*ra-b*T)*da;a[7]=(t*ra-G*V+F*T)*da;a[8]=(k*wa-l*ua+m*sa)*da;a[9]=
(d*ua-c*wa-g*sa)*da;a[10]=(P*X-L*V+b*ba)*da;a[11]=(y*V-t*X-F*ba)*da;a[12]=(l*ta-k*va-h*sa)*da;a[13]=(c*va-d*ta+f*sa)*da;a[14]=(L*T-P*W-K*ba)*da;a[15]=(t*W-y*T+G*ba)*da;return a}function N(a,b){const c=b[0],d=b[1],f=b[2],g=b[3],k=b[4],l=b[5],h=b[6],m=b[7],t=b[8],y=b[9],G=b[10],F=b[11],P=b[12],L=b[13],K=b[14];b=b[15];a[0]=l*(G*b-F*K)-y*(h*b-m*K)+L*(h*F-m*G);a[1]=-(d*(G*b-F*K)-y*(f*b-g*K)+L*(f*F-g*G));a[2]=d*(h*b-m*K)-l*(f*b-g*K)+L*(f*m-g*h);a[3]=-(d*(h*F-m*G)-l*(f*F-g*G)+y*(f*m-g*h));a[4]=-(k*(G*b-
F*K)-t*(h*b-m*K)+P*(h*F-m*G));a[5]=c*(G*b-F*K)-t*(f*b-g*K)+P*(f*F-g*G);a[6]=-(c*(h*b-m*K)-k*(f*b-g*K)+P*(f*m-g*h));a[7]=c*(h*F-m*G)-k*(f*F-g*G)+t*(f*m-g*h);a[8]=k*(y*b-F*L)-t*(l*b-m*L)+P*(l*F-m*y);a[9]=-(c*(y*b-F*L)-t*(d*b-g*L)+P*(d*F-g*y));a[10]=c*(l*b-m*L)-k*(d*b-g*L)+P*(d*m-g*l);a[11]=-(c*(l*F-m*y)-k*(d*F-g*y)+t*(d*m-g*l));a[12]=-(k*(y*K-G*L)-t*(l*K-h*L)+P*(l*G-h*y));a[13]=c*(y*K-G*L)-t*(d*K-f*L)+P*(d*G-f*y);a[14]=-(c*(l*K-h*L)-k*(d*K-f*L)+P*(d*h-f*l));a[15]=c*(l*G-h*y)-k*(d*G-f*y)+t*(d*h-f*l);
return a}function Q(a){const b=a[0],c=a[1],d=a[2],f=a[3],g=a[4],k=a[5],l=a[6],h=a[7],m=a[8],t=a[9],y=a[10],G=a[11],F=a[12],P=a[13],L=a[14];a=a[15];return(b*k-c*g)*(y*a-G*L)-(b*l-d*g)*(t*a-G*P)+(b*h-f*g)*(t*L-y*P)+(c*l-d*k)*(m*a-G*F)-(c*h-f*k)*(m*L-y*F)+(d*h-f*l)*(m*P-t*F)}function w(a,b,c){const d=b[0],f=b[1],g=b[2],k=b[3],l=b[4],h=b[5],m=b[6],t=b[7],y=b[8],G=b[9],F=b[10],P=b[11],L=b[12],K=b[13],ba=b[14];b=b[15];let T=c[0],V=c[1],W=c[2],X=c[3];a[0]=T*d+V*l+W*y+X*L;a[1]=T*f+V*h+W*G+X*K;a[2]=T*g+V*
m+W*F+X*ba;a[3]=T*k+V*t+W*P+X*b;T=c[4];V=c[5];W=c[6];X=c[7];a[4]=T*d+V*l+W*y+X*L;a[5]=T*f+V*h+W*G+X*K;a[6]=T*g+V*m+W*F+X*ba;a[7]=T*k+V*t+W*P+X*b;T=c[8];V=c[9];W=c[10];X=c[11];a[8]=T*d+V*l+W*y+X*L;a[9]=T*f+V*h+W*G+X*K;a[10]=T*g+V*m+W*F+X*ba;a[11]=T*k+V*t+W*P+X*b;T=c[12];V=c[13];W=c[14];X=c[15];a[12]=T*d+V*l+W*y+X*L;a[13]=T*f+V*h+W*G+X*K;a[14]=T*g+V*m+W*F+X*ba;a[15]=T*k+V*t+W*P+X*b;return a}function u(a,b,c){const d=c[0],f=c[1];c=c[2];if(b===a)a[12]=b[0]*d+b[4]*f+b[8]*c+b[12],a[13]=b[1]*d+b[5]*f+b[9]*
c+b[13],a[14]=b[2]*d+b[6]*f+b[10]*c+b[14],a[15]=b[3]*d+b[7]*f+b[11]*c+b[15];else{const g=b[0],k=b[1],l=b[2],h=b[3],m=b[4],t=b[5],y=b[6],G=b[7],F=b[8],P=b[9],L=b[10],K=b[11];a[0]=g;a[1]=k;a[2]=l;a[3]=h;a[4]=m;a[5]=t;a[6]=y;a[7]=G;a[8]=F;a[9]=P;a[10]=L;a[11]=K;a[12]=g*d+m*f+F*c+b[12];a[13]=k*d+t*f+P*c+b[13];a[14]=l*d+y*f+L*c+b[14];a[15]=h*d+G*f+K*c+b[15]}return a}function v(a,b,c){const d=c[0],f=c[1];c=c[2];a[0]=b[0]*d;a[1]=b[1]*d;a[2]=b[2]*d;a[3]=b[3]*d;a[4]=b[4]*f;a[5]=b[5]*f;a[6]=b[6]*f;a[7]=b[7]*
f;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=b[11]*c;a[12]=b[12];a[13]=b[13];a[14]=b[14];a[15]=b[15];return a}function C(a,b,c,d){let f=d[0],g=d[1];d=d[2];let k=Math.sqrt(f*f+g*g+d*d);var l=void 0,h=void 0;let m=void 0,t=void 0,y=void 0,G=void 0,F=void 0,P=void 0,L=void 0,K=void 0,ba=void 0,T=void 0,V=void 0,W=void 0,X=void 0,ra=void 0,sa=void 0,ta=void 0,ua=void 0,va=void 0,wa=void 0,xa=void 0;h=l=void 0;if(k<A.getEpsilon())return null;k=1/k;f*=k;g*=k;d*=k;l=Math.sin(c);h=Math.cos(c);m=1-h;t=b[0];
y=b[1];G=b[2];F=b[3];P=b[4];L=b[5];K=b[6];ba=b[7];T=b[8];V=b[9];W=b[10];X=b[11];ra=f*f*m+h;sa=g*f*m+d*l;ta=d*f*m-g*l;ua=f*g*m-d*l;va=g*g*m+h;wa=d*g*m+f*l;xa=f*d*m+g*l;l=g*d*m-f*l;h=d*d*m+h;a[0]=t*ra+P*sa+T*ta;a[1]=y*ra+L*sa+V*ta;a[2]=G*ra+K*sa+W*ta;a[3]=F*ra+ba*sa+X*ta;a[4]=t*ua+P*va+T*wa;a[5]=y*ua+L*va+V*wa;a[6]=G*ua+K*va+W*wa;a[7]=F*ua+ba*va+X*wa;a[8]=t*xa+P*l+T*h;a[9]=y*xa+L*l+V*h;a[10]=G*xa+K*l+W*h;a[11]=F*xa+ba*l+X*h;b!==a&&(a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);return a}function J(a,
b,c){const d=Math.sin(c);c=Math.cos(c);const f=b[4],g=b[5],k=b[6],l=b[7],h=b[8],m=b[9],t=b[10],y=b[11];b!==a&&(a[0]=b[0],a[1]=b[1],a[2]=b[2],a[3]=b[3],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[4]=f*c+h*d;a[5]=g*c+m*d;a[6]=k*c+t*d;a[7]=l*c+y*d;a[8]=h*c-f*d;a[9]=m*c-g*d;a[10]=t*c-k*d;a[11]=y*c-l*d;return a}function R(a,b,c){const d=Math.sin(c);c=Math.cos(c);const f=b[0],g=b[1],k=b[2],l=b[3],h=b[8],m=b[9],t=b[10],y=b[11];b!==a&&(a[4]=b[4],a[5]=b[5],a[6]=b[6],a[7]=b[7],a[12]=b[12],a[13]=b[13],
a[14]=b[14],a[15]=b[15]);a[0]=f*c-h*d;a[1]=g*c-m*d;a[2]=k*c-t*d;a[3]=l*c-y*d;a[8]=f*d+h*c;a[9]=g*d+m*c;a[10]=k*d+t*c;a[11]=l*d+y*c;return a}function E(a,b,c){const d=Math.sin(c);c=Math.cos(c);const f=b[0],g=b[1],k=b[2],l=b[3],h=b[4],m=b[5],t=b[6],y=b[7];b!==a&&(a[8]=b[8],a[9]=b[9],a[10]=b[10],a[11]=b[11],a[12]=b[12],a[13]=b[13],a[14]=b[14],a[15]=b[15]);a[0]=f*c+h*d;a[1]=g*c+m*d;a[2]=k*c+t*d;a[3]=l*c+y*d;a[4]=h*c-f*d;a[5]=m*c-g*d;a[6]=t*c-k*d;a[7]=y*c-l*d;return a}function S(a,b){a[0]=1;a[1]=0;a[2]=
0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=b[0];a[13]=b[1];a[14]=b[2];a[15]=1;return a}function q(a,b){a[0]=b[0];a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b[1];a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=b[2];a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function H(a,b,c){if(0===b)return n(a);let d=c[0],f=c[1];c=c[2];let g=Math.sqrt(d*d+f*f+c*c),k=void 0,l=void 0,h=void 0;if(g<A.getEpsilon())return null;g=1/g;d*=g;f*=g;c*=g;k=Math.sin(b);l=Math.cos(b);h=1-l;a[0]=d*d*h+l;a[1]=f*d*h+c*
k;a[2]=c*d*h-f*k;a[3]=0;a[4]=d*f*h-c*k;a[5]=f*f*h+l;a[6]=c*f*h+d*k;a[7]=0;a[8]=d*c*h+f*k;a[9]=f*c*h-d*k;a[10]=c*c*h+l;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function I(a,b){const c=Math.sin(b);b=Math.cos(b);a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=c;a[7]=0;a[8]=0;a[9]=-c;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function U(a,b){const c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=0;a[2]=-c;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=c;a[9]=0;a[10]=b;a[11]=0;a[12]=0;a[13]=0;a[14]=
0;a[15]=1;return a}function Z(a,b){const c=Math.sin(b);b=Math.cos(b);a[0]=b;a[1]=c;a[2]=0;a[3]=0;a[4]=-c;a[5]=b;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function ma(a,b,c){var d=b[0],f=b[1],g=b[2],k=b[3],l=d+d,h=f+f;const m=g+g;b=d*l;const t=d*h;d*=m;const y=f*h;f*=m;g*=m;l*=k;h*=k;k*=m;a[0]=1-(y+g);a[1]=t+k;a[2]=d-h;a[3]=0;a[4]=t-k;a[5]=1-(b+g);a[6]=f+l;a[7]=0;a[8]=d+h;a[9]=f-l;a[10]=1-(b+y);a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a}function fa(a,
b){const c=r,d=-b[0],f=-b[1],g=-b[2],k=b[3],l=b[4],h=b[5],m=b[6],t=b[7],y=d*d+f*f+g*g+k*k;0<y?(c[0]=2*(l*k+t*d+h*g-m*f)/y,c[1]=2*(h*k+t*f+m*d-l*g)/y,c[2]=2*(m*k+t*g+l*f-h*d)/y):(c[0]=2*(l*k+t*d+h*g-m*f),c[1]=2*(h*k+t*f+m*d-l*g),c[2]=2*(m*k+t*g+l*f-h*d));ma(a,b,c);return a}function Y(a,b){a[0]=b[12];a[1]=b[13];a[2]=b[14];return a}function na(a,b){const c=b[0],d=b[1],f=b[2],g=b[4],k=b[5],l=b[6],h=b[8],m=b[9];b=b[10];a[0]=Math.sqrt(c*c+d*d+f*f);a[1]=Math.sqrt(g*g+k*k+l*l);a[2]=Math.sqrt(h*h+m*m+b*b);
return a}function oa(a,b){const c=b[0]+b[5]+b[10];let d=0;0<c?(d=2*Math.sqrt(c+1),a[3]=.25*d,a[0]=(b[6]-b[9])/d,a[1]=(b[8]-b[2])/d,a[2]=(b[1]-b[4])/d):b[0]>b[5]&&b[0]>b[10]?(d=2*Math.sqrt(1+b[0]-b[5]-b[10]),a[3]=(b[6]-b[9])/d,a[0]=.25*d,a[1]=(b[1]+b[4])/d,a[2]=(b[8]+b[2])/d):b[5]>b[10]?(d=2*Math.sqrt(1+b[5]-b[0]-b[10]),a[3]=(b[8]-b[2])/d,a[0]=(b[1]+b[4])/d,a[1]=.25*d,a[2]=(b[6]+b[9])/d):(d=2*Math.sqrt(1+b[10]-b[0]-b[5]),a[3]=(b[1]-b[4])/d,a[0]=(b[8]+b[2])/d,a[1]=(b[6]+b[9])/d,a[2]=.25*d);return a}
function ha(a,b,c,d){var f=b[0],g=b[1],k=b[2],l=b[3],h=f+f,m=g+g,t=k+k;b=f*h;const y=f*m;f*=t;const G=g*m;g*=t;k*=t;h*=l;m*=l;l*=t;t=d[0];const F=d[1];d=d[2];a[0]=(1-(G+k))*t;a[1]=(y+l)*t;a[2]=(f-m)*t;a[3]=0;a[4]=(y-l)*F;a[5]=(1-(b+k))*F;a[6]=(g+h)*F;a[7]=0;a[8]=(f+m)*d;a[9]=(g-h)*d;a[10]=(1-(b+G))*d;a[11]=0;a[12]=c[0];a[13]=c[1];a[14]=c[2];a[15]=1;return a}function ea(a,b,c,d,f){var g=b[0],k=b[1],l=b[2],h=b[3],m=g+g,t=k+k,y=l+l;b=g*m;var G=g*t,F=g*y;g=k*t;k*=y;var P=l*y;l=h*m;t*=h;const L=h*y;var K=
d[0],ba=d[1];y=d[2];d=f[0];h=f[1];f=f[2];m=(1-(g+P))*K;const T=(G+L)*K;K*=F-t;G=(G-L)*ba;P=(1-(b+P))*ba;ba*=k+l;F=(F+t)*y;k=(k-l)*y;b=(1-(b+g))*y;a[0]=m;a[1]=T;a[2]=K;a[3]=0;a[4]=G;a[5]=P;a[6]=ba;a[7]=0;a[8]=F;a[9]=k;a[10]=b;a[11]=0;a[12]=c[0]+d-(m*d+G*h+F*f);a[13]=c[1]+h-(T*d+P*h+k*f);a[14]=c[2]+f-(K*d+ba*h+b*f);a[15]=1;return a}function ka(a,b){var c=b[0],d=b[1],f=b[2];b=b[3];var g=c+c,k=d+d;const l=f+f;c*=g;const h=d*g;d*=k;const m=f*g,t=f*k;f*=l;g*=b;k*=b;b*=l;a[0]=1-d-f;a[1]=h+b;a[2]=m-k;a[3]=
0;a[4]=h-b;a[5]=1-c-f;a[6]=t+g;a[7]=0;a[8]=m+k;a[9]=t-g;a[10]=1-c-d;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a}function aa(a,b,c,d,f,g,k){const l=1/(c-b),h=1/(f-d),m=1/(g-k);a[0]=2*g*l;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=2*g*h;a[6]=0;a[7]=0;a[8]=(c+b)*l;a[9]=(f+d)*h;a[10]=(k+g)*m;a[11]=-1;a[12]=0;a[13]=0;a[14]=k*g*2*m;a[15]=0;return a}function ia(a,b,c,d,f){b=1/Math.tan(b/2);let g=void 0;a[0]=b/c;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=b;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[11]=-1;a[12]=0;a[13]=0;a[15]=0;null!=
f&&Infinity!==f?(g=1/(d-f),a[10]=(f+d)*g,a[14]=2*f*d*g):(a[10]=-1,a[14]=-2*d);return a}function O(a,b,c,d){const f=Math.tan(b.upDegrees*Math.PI/180),g=Math.tan(b.downDegrees*Math.PI/180),k=Math.tan(b.leftDegrees*Math.PI/180);b=Math.tan(b.rightDegrees*Math.PI/180);const l=2/(k+b),h=2/(f+g);a[0]=l;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=h;a[6]=0;a[7]=0;a[8]=-((k-b)*l*.5);a[9]=(f-g)*h*.5;a[10]=d/(c-d);a[11]=-1;a[12]=0;a[13]=0;a[14]=d*c/(c-d);a[15]=0;return a}function ca(a,b,c,d,f,g,k){const l=1/(b-c),h=1/(d-
f),m=1/(g-k);a[0]=-2*l;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=-2*h;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=2*m;a[11]=0;a[12]=(b+c)*l;a[13]=(f+d)*h;a[14]=(k+g)*m;a[15]=1;return a}function ja(a,b,c,d){const f=b[0],g=b[1];b=b[2];let k=f-c[0],l=g-c[1];c=b-c[2];var h=A.getEpsilon();if(Math.abs(k)<h&&Math.abs(l)<h&&Math.abs(c)<h)n(a);else{var m=1/Math.sqrt(k*k+l*l+c*c);k*=m;l*=m;c*=m;m=d[0];var t=d[1];h=d[2];d=t*c-h*l;h=h*k-m*c;t=m*l-t*k;(m=Math.sqrt(d*d+h*h+t*t))?(m=1/m,d*=m,h*=m,t*=m):t=h=d=0;var y=l*t-c*h,G=c*d-
k*t,F=k*h-l*d;(m=Math.sqrt(y*y+G*G+F*F))?(m=1/m,y*=m,G*=m,F*=m):F=G=y=0;a[0]=d;a[1]=y;a[2]=k;a[3]=0;a[4]=h;a[5]=G;a[6]=l;a[7]=0;a[8]=t;a[9]=F;a[10]=c;a[11]=0;a[12]=-(d*f+h*g+t*b);a[13]=-(y*f+G*g+F*b);a[14]=-(k*f+l*g+c*b);a[15]=1}}function la(a,b,c,d){const f=b[0],g=b[1];b=b[2];var k=d[0];const l=d[1];var h=d[2];d=f-c[0];let m=g-c[1];c=b-c[2];let t=d*d+m*m+c*c;0<t&&(t=1/Math.sqrt(t),d*=t,m*=t,c*=t);let y=l*c-h*m;h=h*d-k*c;k=k*m-l*d;t=y*y+h*h+k*k;0<t&&(t=1/Math.sqrt(t),y*=t,h*=t,k*=t);a[0]=y;a[1]=h;
a[2]=k;a[3]=0;a[4]=m*k-c*h;a[5]=c*y-d*k;a[6]=d*h-m*y;a[7]=0;a[8]=d;a[9]=m;a[10]=c;a[11]=0;a[12]=f;a[13]=g;a[14]=b;a[15]=1;return a}function za(a){return"mat4("+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+")"}function Aa(a){return Math.sqrt(a[0]**2+a[1]**2+a[2]**2+a[3]**2+a[4]**2+a[5]**2+a[6]**2+a[7]**2+a[8]**2+a[9]**2+a[10]**2+a[11]**2+a[12]**2+a[13]**2+a[14]**2+a[15]**2)}function ya(a,
b,c){a[0]=b[0]+c[0];a[1]=b[1]+c[1];a[2]=b[2]+c[2];a[3]=b[3]+c[3];a[4]=b[4]+c[4];a[5]=b[5]+c[5];a[6]=b[6]+c[6];a[7]=b[7]+c[7];a[8]=b[8]+c[8];a[9]=b[9]+c[9];a[10]=b[10]+c[10];a[11]=b[11]+c[11];a[12]=b[12]+c[12];a[13]=b[13]+c[13];a[14]=b[14]+c[14];a[15]=b[15]+c[15];return a}function qa(a,b,c){a[0]=b[0]-c[0];a[1]=b[1]-c[1];a[2]=b[2]-c[2];a[3]=b[3]-c[3];a[4]=b[4]-c[4];a[5]=b[5]-c[5];a[6]=b[6]-c[6];a[7]=b[7]-c[7];a[8]=b[8]-c[8];a[9]=b[9]-c[9];a[10]=b[10]-c[10];a[11]=b[11]-c[11];a[12]=b[12]-c[12];a[13]=
b[13]-c[13];a[14]=b[14]-c[14];a[15]=b[15]-c[15];return a}function Ba(a,b,c){a[0]=b[0]*c;a[1]=b[1]*c;a[2]=b[2]*c;a[3]=b[3]*c;a[4]=b[4]*c;a[5]=b[5]*c;a[6]=b[6]*c;a[7]=b[7]*c;a[8]=b[8]*c;a[9]=b[9]*c;a[10]=b[10]*c;a[11]=b[11]*c;a[12]=b[12]*c;a[13]=b[13]*c;a[14]=b[14]*c;a[15]=b[15]*c;return a}function Fa(a,b,c,d){a[0]=b[0]+c[0]*d;a[1]=b[1]+c[1]*d;a[2]=b[2]+c[2]*d;a[3]=b[3]+c[3]*d;a[4]=b[4]+c[4]*d;a[5]=b[5]+c[5]*d;a[6]=b[6]+c[6]*d;a[7]=b[7]+c[7]*d;a[8]=b[8]+c[8]*d;a[9]=b[9]+c[9]*d;a[10]=b[10]+c[10]*d;a[11]=
b[11]+c[11]*d;a[12]=b[12]+c[12]*d;a[13]=b[13]+c[13]*d;a[14]=b[14]+c[14]*d;a[15]=b[15]+c[15]*d;return a}function Ca(a,b){return a[0]===b[0]&&a[1]===b[1]&&a[2]===b[2]&&a[3]===b[3]&&a[4]===b[4]&&a[5]===b[5]&&a[6]===b[6]&&a[7]===b[7]&&a[8]===b[8]&&a[9]===b[9]&&a[10]===b[10]&&a[11]===b[11]&&a[12]===b[12]&&a[13]===b[13]&&a[14]===b[14]&&a[15]===b[15]}function Da(a,b){if(a===b)return!0;const c=a[0],d=a[1],f=a[2],g=a[3],k=a[4],l=a[5],h=a[6],m=a[7],t=a[8],y=a[9],G=a[10],F=a[11],P=a[12],L=a[13],K=a[14];a=a[15];
const ba=b[0],T=b[1],V=b[2],W=b[3],X=b[4],ra=b[5],sa=b[6],ta=b[7],ua=b[8],va=b[9],wa=b[10],xa=b[11],da=b[12],Ha=b[13],Ia=b[14];b=b[15];const pa=A.getEpsilon();return Math.abs(c-ba)<=pa*Math.max(1,Math.abs(c),Math.abs(ba))&&Math.abs(d-T)<=pa*Math.max(1,Math.abs(d),Math.abs(T))&&Math.abs(f-V)<=pa*Math.max(1,Math.abs(f),Math.abs(V))&&Math.abs(g-W)<=pa*Math.max(1,Math.abs(g),Math.abs(W))&&Math.abs(k-X)<=pa*Math.max(1,Math.abs(k),Math.abs(X))&&Math.abs(l-ra)<=pa*Math.max(1,Math.abs(l),Math.abs(ra))&&Math.abs(h-
sa)<=pa*Math.max(1,Math.abs(h),Math.abs(sa))&&Math.abs(m-ta)<=pa*Math.max(1,Math.abs(m),Math.abs(ta))&&Math.abs(t-ua)<=pa*Math.max(1,Math.abs(t),Math.abs(ua))&&Math.abs(y-va)<=pa*Math.max(1,Math.abs(y),Math.abs(va))&&Math.abs(G-wa)<=pa*Math.max(1,Math.abs(G),Math.abs(wa))&&Math.abs(F-xa)<=pa*Math.max(1,Math.abs(F),Math.abs(xa))&&Math.abs(P-da)<=pa*Math.max(1,Math.abs(P),Math.abs(da))&&Math.abs(L-Ha)<=pa*Math.max(1,Math.abs(L),Math.abs(Ha))&&Math.abs(K-Ia)<=pa*Math.max(1,Math.abs(K),Math.abs(Ia))&&
Math.abs(a-b)<=pa*Math.max(1,Math.abs(a),Math.abs(b))}function Ea(a){const b=A.getEpsilon(),c=a[0],d=a[1],f=a[2],g=a[4],k=a[5],l=a[6],h=a[8],m=a[9];a=a[10];return Math.abs(1-(c*c+g*g+h*h))<=b&&Math.abs(1-(d*d+k*k+m*m))<=b&&Math.abs(1-(f*f+l*l+a*a))<=b}function Ga(a){return 1===a[0]&&0===a[1]&&0===a[2]&&0===a[4]&&1===a[5]&&0===a[6]&&0===a[8]&&0===a[9]&&1===a[10]}const r=p.create();p=Object.freeze(Object.defineProperty({__proto__:null,add:ya,adjoint:N,copy:z,determinant:Q,equals:Da,exactEquals:Ca,frob:Aa,
fromQuat:ka,fromQuat2:fa,fromRotation:H,fromRotationTranslation:ma,fromRotationTranslationScale:ha,fromRotationTranslationScaleOrigin:ea,fromScaling:q,fromTranslation:S,fromXRotation:I,fromYRotation:U,fromZRotation:Z,frustum:aa,getRotation:oa,getScaling:na,getTranslation:Y,hasIdentityRotation:Ga,identity:n,invert:M,invertOrIdentity:x,isOrthoNormal:Ea,lookAt:ja,mul:w,multiply:w,multiplyScalar:Ba,multiplyScalarAndAdd:Fa,ortho:ca,perspective:ia,perspectiveFromFieldOfView:O,rotate:C,rotateX:J,rotateY:R,
rotateZ:E,scale:v,set:D,str:za,sub:qa,subtract:qa,targetTo:la,translate:u,transpose:B},Symbol.toStringTag,{value:"Module"}));e.add=ya;e.adjoint=N;e.copy=z;e.determinant=Q;e.equals=Da;e.exactEquals=Ca;e.frob=Aa;e.fromQuat=ka;e.fromQuat2=fa;e.fromRotation=H;e.fromRotationTranslation=ma;e.fromRotationTranslationScale=ha;e.fromRotationTranslationScaleOrigin=ea;e.fromScaling=q;e.fromTranslation=S;e.fromXRotation=I;e.fromYRotation=U;e.fromZRotation=Z;e.frustum=aa;e.getRotation=oa;e.getScaling=na;e.getTranslation=
Y;e.hasIdentityRotation=Ga;e.identity=n;e.invert=M;e.invertOrIdentity=x;e.isOrthoNormal=Ea;e.lookAt=ja;e.mat4=p;e.mul=w;e.multiply=w;e.multiplyScalar=Ba;e.multiplyScalarAndAdd=Fa;e.ortho=ca;e.perspective=ia;e.perspectiveFromFieldOfView=O;e.rotate=C;e.rotateX=J;e.rotateY=R;e.rotateZ=E;e.scale=v;e.set=D;e.str=za;e.sub=qa;e.subtract=qa;e.targetTo=la;e.translate=u;e.transpose=B})},"esri/geometry/support/ray":function(){define("exports ../../core/arrayUtils ../../core/ObjectStack ../../chunks/vec3 ../../chunks/vec3f64 ./vectorStacks".split(" "),
function(e,p,A,z,D,n){function B(w){return w?x(D.clone(w.origin),D.clone(w.direction)):x(D.create(),D.create())}function x(w,u){return{origin:w,direction:u}}function M(w,u,v=B()){z.copy(v.origin,w);z.copy(v.direction,u);return v}function N(w,u){w=z.cross(n.sv3d.get(),z.normalize(n.sv3d.get(),w.direction),z.subtract(n.sv3d.get(),u,w.origin));return z.dot(w,w)}const Q=new A.ObjectStack(()=>B());e.closestPoint=function(w,u,v){u=z.dot(w.direction,z.subtract(v,u,w.origin));z.add(v,w.origin,z.scale(v,w.direction,
u));return v};e.copy=function(w,u=B()){return M(w.origin,w.direction,u)};e.create=B;e.distance=function(w,u){return Math.sqrt(N(w,u))};e.distance2=N;e.equals=function(w,u){return p.equals(w.origin,u.origin)&&p.equals(w.direction,u.direction)};e.fromPoints=function(w,u,v=B()){z.copy(v.origin,w);z.subtract(v.direction,u,w);return v};e.fromValues=M;e.wrap=function(w,u){const v=Q.get();v.origin=w;v.direction=u;return v};Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/core/ObjectStack":function(){define(["exports",
"./nextTick"],function(e,p){class A{constructor(z){this._allocator=z;this._items=[];this._itemsPtr=0;this._grow()}get(){0===this._itemsPtr&&p.nextTick(()=>this._reset());this._itemsPtr===this._items.length&&this._grow();return this._items[this._itemsPtr++]}_reset(){this._items.length=Math.min(Math.min(3*Math.max(8,this._itemsPtr),this._itemsPtr+3072),this._items.length);this._itemsPtr=0}_grow(){for(let z=0;z<Math.max(8,Math.min(this._items.length,1024));z++)this._items.push(this._allocator())}}e.ObjectStack=
A;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/geometry/support/vectorStacks":function(){define(["exports","../../core/VectorStack"],function(e,p){const A=p.VectorStack.createVec2f64(),z=p.VectorStack.createVec3f64(),D=p.VectorStack.createVec4f64(),n=p.VectorStack.createMat3f64(),B=p.VectorStack.createMat4f64();p=p.VectorStack.createQuatf64();e.sm3d=n;e.sm4d=B;e.sq4d=p;e.sv2d=A;e.sv3d=z;e.sv4d=D;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/core/VectorStack":function(){define("exports ./ByteSizeUnit ./nextTick ../chunks/mat3f64 ../chunks/mat4f64 ../chunks/quatf64 ../chunks/vec2f64 ../chunks/vec3f64 ../chunks/vec4f64".split(" "),
function(e,p,A,z,D,n,B,x,M){class N{constructor(w,u,v){this._itemByteSize=w;this._itemCreate=u;this._buffers=[];this._items=[];this._itemsPtr=0;this._itemsPerBuffer=Math.ceil(v/this._itemByteSize)}get(){0===this._itemsPtr&&A.nextTick(()=>this._reset());const w=Math.floor(this._itemsPtr/this._itemsPerBuffer);for(;this._buffers.length<=w;){const u=new ArrayBuffer(this._itemsPerBuffer*this._itemByteSize);for(let v=0;v<this._itemsPerBuffer;++v)this._items.push(this._itemCreate(u,v*this._itemByteSize));
this._buffers.push(u)}return this._items[this._itemsPtr++]}_reset(){const w=2*(Math.floor(this._itemsPtr/this._itemsPerBuffer)+1);for(;this._buffers.length>w;)this._buffers.pop(),this._items.length=this._buffers.length*this._itemsPerBuffer;this._itemsPtr=0}static createVec2f64(w=Q){return new N(16,B.createView,w)}static createVec3f64(w=Q){return new N(24,x.createView,w)}static createVec4f64(w=Q){return new N(32,M.createView,w)}static createMat3f64(w=Q){return new N(72,z.createView,w)}static createMat4f64(w=
Q){return new N(128,D.createView,w)}static createQuatf64(w=Q){return new N(32,n.createView,w)}get test(){return{size:this._buffers.length*this._itemsPerBuffer*this._itemByteSize}}}const Q=4*p.ByteSizeUnit.KILOBYTES;e.VectorStack=N;Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/core/ByteSizeUnit":function(){define(["exports"],function(e){e.ByteSizeUnit=void 0;var p=e.ByteSizeUnit||(e.ByteSizeUnit={});p[p.KILOBYTES=1024]="KILOBYTES";p[p.MEGABYTES=1048576]="MEGABYTES";p[p.GIGABYTES=
1073741824]="GIGABYTES";Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},"esri/chunks/mat3f64":function(){define(["exports"],function(e){function p(){return[1,0,0,0,1,0,0,0,1]}function A(B){return[B[0],B[1],B[2],B[3],B[4],B[5],B[6],B[7],B[8]]}function z(B,x,M,N,Q,w,u,v,C){return[B,x,M,N,Q,w,u,v,C]}function D(B,x){return new Float64Array(B,x,9)}const n=Object.freeze(Object.defineProperty({__proto__:null,clone:A,create:p,createView:D,fromValues:z},Symbol.toStringTag,{value:"Module"}));
e.clone=A;e.create=p;e.createView=D;e.fromValues=z;e.mat3f64=n})},"esri/chunks/mat4f64":function(){define(["exports"],function(e){function p(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}function A(x){return[x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],x[8],x[9],x[10],x[11],x[12],x[13],x[14],x[15]]}function z(x,M,N,Q,w,u,v,C,J,R,E,S,q,H,I,U){return[x,M,N,Q,w,u,v,C,J,R,E,S,q,H,I,U]}function D(x,M){return new Float64Array(x,M,16)}const n=p(),B=Object.freeze(Object.defineProperty({__proto__:null,IDENTITY:n,clone:A,
create:p,createView:D,fromValues:z},Symbol.toStringTag,{value:"Module"}));e.IDENTITY=n;e.clone=A;e.create=p;e.createView=D;e.fromValues=z;e.mat4f64=B})},"esri/chunks/quatf64":function(){define(["exports"],function(e){function p(){return[0,0,0,1]}function A(x){return[x[0],x[1],x[2],x[3]]}function z(x,M,N,Q){return[x,M,N,Q]}function D(x,M){return new Float64Array(x,M,4)}const n=p(),B=Object.freeze(Object.defineProperty({__proto__:null,IDENTITY:n,clone:A,create:p,createView:D,fromValues:z},Symbol.toStringTag,
{value:"Module"}));e.IDENTITY=n;e.clone=A;e.create=p;e.createView=D;e.fromValues=z;e.quatf64=B})},"esri/chunks/vec2f64":function(){define(["exports"],function(e){function p(){return[0,0]}function A(J){return[J[0],J[1]]}function z(J,R){return[J,R]}function D(J,R=[0,0]){const E=Math.min(2,J.length);for(let S=0;S<E;++S)R[S]=J[S];return R}function n(J,R){return new Float64Array(J,R,2)}function B(){return[0,0]}function x(){return[1,1]}function M(){return[1,0]}function N(){return[0,1]}const Q=[0,0],w=[1,
1],u=[1,0],v=[0,1],C=Object.freeze(Object.defineProperty({__proto__:null,ONES:w,UNIT_X:u,UNIT_Y:v,ZEROS:Q,clone:A,create:p,createView:n,fromArray:D,fromValues:z,ones:x,unitX:M,unitY:N,zeros:B},Symbol.toStringTag,{value:"Module"}));e.ONES=w;e.UNIT_X=u;e.UNIT_Y=v;e.ZEROS=Q;e.clone=A;e.create=p;e.createView=n;e.fromArray=D;e.fromValues=z;e.ones=x;e.unitX=M;e.unitY=N;e.vec2f64=C;e.zeros=B})},"esri/geometry/support/vector":function(){define(["exports","../../core/mathUtils","../../chunks/vec3","../../chunks/vec3f64"],
function(e,p,A,z){const D=z.create(),n=z.create();e.angle=function(B,x){B=A.dot(B,x)/(A.length(B)*A.length(x));return-p.acosClamped(B)};e.angleAroundAxis=function(B,x,M){A.normalize(D,B);A.normalize(n,x);B=A.dot(D,n);B=p.acosClamped(B);x=A.cross(D,D,n);return 0>A.dot(x,M)?2*Math.PI-B:B};e.projectPoint=function(B,x,M){x=A.dot(B,x)/A.dot(B,B);return A.scale(M,B,x)};e.projectPointSignedLength=function(B,x){return A.dot(B,x)/A.length(B)};Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})})},
"*noref":1}});
define("require exports ../../../geometry/SpatialReference ../../../geometry/support/DoubleArray ../../../geometry/support/MeshGeoreferencedRelativeVertexSpace ../../../geometry/support/MeshLocalVertexSpace ../../../chunks/vec32 ../../../libs/i3s/enums ../../../libs/i3s/I3SModule ./i3s/I3SNode".split(" "),function(e,p,A,z,D,n,B,x,M,N){function Q(q){if(E){var H=q.modifications,I=E._malloc(8*H.length),U=new Float64Array(E.HEAPU8.buffer,I,H.length);for(let Z=0;Z<H.length;++Z)U[Z]=H[Z];E.setModifications(q.context,
I,H.length,q.isGeodetic);E._free(I)}}function w(q,H,I){const {context:U,localOrigin:Z,globalTrafo:ma,mbs:fa,obb:Y,elevationOffset:na,geometryBuffer:oa,geometryDescriptor:ha,indexToVertexProjector:ea,vertexToRenderProjector:ka}=H;var aa=q._malloc(oa.byteLength),ia=q._malloc(33*Float64Array.BYTES_PER_ELEMENT),O=new Uint8Array(q.HEAPU8.buffer,aa,oa.byteLength);O.set(new Uint8Array(oa));var ca=new Float64Array(q.HEAPU8.buffer,ia,33);C(ca,Z);var ja=ca.byteOffset+3*ca.BYTES_PER_ELEMENT,la=new Float64Array(ca.buffer,
ja);C(la,ma);ja+=16*ca.BYTES_PER_ELEMENT;la=new Float64Array(ca.buffer,ja);C(la,fa);ja+=4*ca.BYTES_PER_ELEMENT;null!=Y&&(la=new Float64Array(ca.buffer,ja),C(la,Y.center),ja+=3*ca.BYTES_PER_ELEMENT,la=new Float64Array(ca.buffer,ja),C(la,Y.halfSize),ja+=3*ca.BYTES_PER_ELEMENT,la=new Float64Array(ca.buffer,ja),C(la,Y.quaternion));ca={isDraco:!1,isLegacy:!1,color:H.layouts.some(ya=>ya.some(qa=>"color"===qa.name)),normal:H.needNormals&&H.layouts.some(ya=>ya.some(qa=>"normalCompressed"===qa.name)),uv0:H.layouts.some(ya=>
ya.some(qa=>"uv0"===qa.name)),uvRegion:H.layouts.some(ya=>ya.some(qa=>"uvRegion"===qa.name)),featureIndex:ha.featureIndex};O=q.process(U,!!H.obb,aa,O.byteLength,ha,ca,ia,na,ea,ka,H.normalReferenceFrame);q._free(ia);q._free(aa);if(0<O.error.length)throw Error(`i3s.wasm: ${O.error}`);if(O.discarded)return null;q=0<O.componentOffsets.length?O.componentOffsets.slice():null;aa=0<O.featureIds.length?O.featureIds.slice():null;ia=0<O.anchorIds.length?Array.from(O.anchorIds):null;ca=0<O.anchors.length?Array.from(O.anchors):
null;ja=O.interleavedVertedData.slice().buffer;la=O.indicesType===x.IndexType.Int16?(new Uint16Array(O.indices.buffer,O.indices.byteOffset,O.indices.byteLength/2)).slice():(new Uint32Array(O.indices.buffer,O.indices.byteOffset,O.indices.byteLength/4)).slice();const za=O.positions.slice(),Aa=O.positionIndicesType===x.IndexType.Int16?(new Uint16Array(O.positionIndices.buffer,O.positionIndices.byteOffset,O.positionIndices.byteLength/2)).slice():(new Uint32Array(O.positionIndices.buffer,O.positionIndices.byteOffset,
O.positionIndices.byteLength/4)).slice();H={layout:H.layouts[0],interleavedVertexData:ja,indices:la,hasColors:O.hasColors,hasModifications:O.hasModifications,positionData:{data:za,indices:Aa}};aa&&I.push(aa.buffer);q&&I.push(q.buffer);I.push(ja);I.push(la.buffer);I.push(za.buffer);I.push(Aa.buffer);return{componentOffsets:q,featureIds:aa,anchorIds:ia,anchors:ca,transformedGeometry:H,obb:O.obb}}function u(q){if(E){var {context:H,buffer:I}=q;q=E._malloc(I.byteLength);var U=I.byteLength/Float64Array.BYTES_PER_ELEMENT,
Z=new Float64Array(E.HEAPU8.buffer,q,U),ma=new Float64Array(I);Z.set(ma);E.filterOBBs(H,q,U);ma.set(Z);E._free(q)}}function v(q){E&&0===E.destroy(q)&&(E=null)}function C(q,H){for(let I=0;I<H.length;++I)q[I]=H[I]}function J(){if(E)return Promise.resolve(E);R||(R=M.get().then(q=>{E=q;R=null;return E}));return R}let R,E;const S={transform:(q,H)=>E&&w(E,q,H),destroy:v};p.destroyContext=function(q){v(q)};p.dracoDecompressPointCloudData=async function(q){E=await J();const H=[q.geometryBuffer];var {geometryBuffer:I}=
q,U=I.byteLength;q=E._malloc(U);U=new Uint8Array(E.HEAPU8.buffer,q,U);U.set(new Uint8Array(I));I=E.dracoDecompressPointCloudData(q,U.byteLength);E._free(q);if(0<I.error.length)throw Error(`i3s.wasm: ${I.error}`);q=0<I.featureIds?.length?I.featureIds.slice():null;I=I.positions.slice();q&&H.push(q.buffer);H.push(I.buffer);return{result:{positions:I,featureIds:q},transferList:H}};p.filterObbsForModifications=async function(q){await J();u(q);q={buffer:q.buffer};return{result:q,transferList:[q.buffer]}};
p.filterObbsForModificationsSync=u;p.initialize=async function(){E||await J()};p.interpretObbModificationResults=function(q){return 0===q?N.NodeIMModificationImpact.Unmodified:1===q?N.NodeIMModificationImpact.PotentiallyModified:2===q?N.NodeIMModificationImpact.Culled:N.NodeIMModificationImpact.Unknown};p.process=async function(q){E=await J();const H=[q.geometryBuffer];return{result:w(E,q,H),transferList:H}};p.project=async function(q){const {localMatrix:H,origin:I,positions:U,vertexSpace:Z,localMode:ma}=
q;var fa=A.fromJSON(q.inSpatialReference);q=A.fromJSON(q.outSpatialReference);if("georeferenced"===Z.type){const [{projectBuffer:ea},{initializeProjection:ka}]=await Promise.all([new Promise((aa,ia)=>e(["../../../geometry/projection/projectBuffer"],aa,ia)),new Promise((aa,ia)=>e(["../../../geometry/projection"],aa,ia))]);await ka(fa,q);var Y=new Float64Array(U.length);ea(U,fa,0,Y,q,0,Y.length/3)}else{Y="georeferencedRelative"===Z.type?D.fromJSON(Z):n.fromJSON(Z);const {project:ea}=await new Promise((ka,
aa)=>e(["../../../geometry/support/meshUtils/georeference"],ka,aa));Y=z.toFloat64Array(ea({positions:U,transform:H?{localMatrix:H}:void 0,vertexSpace:Y,inSpatialReference:fa,outSpatialReference:q,localMode:ma}))}fa=Y.length;const [na,oa,ha]=I;for(q=0;q<fa;q+=3)Y[q]-=na,Y[q+1]-=oa,Y[q+2]-=ha;return{result:{projected:Y,original:U},transferList:[Y.buffer,U.buffer]}};p.setLegacySchema=async function(q){E=await J();E.setLegacySchema(q.context,q.jsonSchema)};p.setModifications=async function(q){await J();
Q(q)};p.setModificationsSync=Q;p.test=S;p.transformNormals=async function({normalMatrix:q,normals:H}){const I=new Float32Array(H.length);B.transformMat3(I,H,q);B.normalize(I,I);return{result:{transformed:I,original:H},transferList:[I.buffer,H.buffer]}};Object.defineProperty(p,Symbol.toStringTag,{value:"Module"})});