// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../../chunks/tslib.es6 ../../core/Collection ../../core/Evented ../../core/reactiveUtils ../../core/accessorSupport/decorators/property ../../core/accessorSupport/ensureType ../../core/arrayUtils ../../core/has ../../core/accessorSupport/decorators/subclass ../LayerList/ListItem".split(" "),function(g,e,u,f,h,x,y,z,v,r){const l=e.ofType(r);e=class extends u.EventedAccessor{constructor(a){super(a);this.baseItems=new l;this.baseListItemCreatedFunction=null;this.checkPublishStatusEnabled=!1;
this.referenceListItemCreatedFunction=null;this.referenceItems=new l;this.view=null;this._compileBaseList=this._compileBaseList.bind(this);this._compileReferenceList=this._compileReferenceList.bind(this)}initialize(){this.addHandles([f.watch(()=>[this.view?.map?.basemap,this.view,this.view?.ready,this.view?.basemapView],()=>this._watchBasemapLayers(),f.initial),f.watch(()=>[this.baseListItemCreatedFunction,this.checkPublishStatusEnabled],()=>this._baseListItemCreatedFunctionChanged()),f.watch(()=>
[this.referenceListItemCreatedFunction,this.checkPublishStatusEnabled],()=>this._referenceListItemCreatedFunctionChanged())],"view")}destroy(){this.view=null;this.baseItems.removeAll();this.referenceItems.removeAll()}get basemapTitle(){return this.view?.map?.basemap?.title??null}set basemapTitle(a){this._override("basemapTitle",a)}get state(){return this.view?.ready?"ready":this.view?"loading":"disabled"}triggerAction(a,b){a&&!a.disabled&&this.emit("trigger-action",{action:a,item:b})}transferListItem({listItem:a,
from:b,to:c,newIndex:d}){const {referenceItems:k,baseItems:m}=this,{layer:t}=a;var n=this.view?.map?.basemap;const p=n?.baseLayers,q=n?.referenceLayers;if(p&&q&&b!==c){n="reference"===c?k:m;var w="reference"===b?q:p;c="reference"===c?q:p;("reference"===b?k:m).remove(a);w.remove(t);n.add(a,d);c.add(t,d)}}_createItemChangeHandles({items:a,key:b,callback:c}){this.removeHandles(b);c();a&&this.addHandles(a.on("change",()=>c()),b)}_createListItem({layer:a,type:b}){const {view:c,baseListItemCreatedFunction:d,
referenceListItemCreatedFunction:k,checkPublishStatusEnabled:m}=this;return new r({layer:a,checkPublishStatusEnabled:m,listItemCreatedFunction:"base"===b?d:k,view:c})}_watchLayersListMode({layers:a,key:b,callback:c}){this.removeHandles(b);a&&a.forEach(d=>{this.addHandles(f.watch(()=>d.listMode,()=>c()),b)})}_compileListItems({layers:a,items:b,key:c,type:d,callback:k}){this._watchLayersListMode({layers:a,key:c,callback:k});this._createNewItems({type:d,items:b,layers:a});this._removeItems({items:b,
layers:a});this._sortItems(b,a)}_compileReferenceList(){const {referenceItems:a}=this;this._compileListItems({type:"reference",layers:this.view?.map?.basemap?.referenceLayers,items:a,key:"base-layers-list-mode",callback:this._compileReferenceList})}_compileBaseList(){const {baseItems:a}=this;this._compileListItems({type:"base",layers:this.view?.map?.basemap?.baseLayers,items:a,key:"reference-layers-list-mode",callback:this._compileBaseList})}_compileLists(){this._compileReferenceList();this._compileBaseList()}_createNewItems({items:a,
layers:b,type:c}){b&&b.forEach(d=>{a.find(k=>k.layer===d)||a.add(this._createListItem({type:c,layer:d}))})}_removeItems({items:a,layers:b}){a&&a.forEach(c=>{c&&!b?.find(d=>c.layer===d)&&(this.removeHandles(`${"children"}-${c.uid}`),a.remove(c))})}_sortItems(a,b){a&&b&&a.sort((c,d)=>{c=b.indexOf(c.layer);d=b.indexOf(d.layer);return c>d?-1:c<d?1:0})}_removeAllBaseItems(){const {baseItems:a}=this;a.forEach(b=>{this.removeHandles(`${"children"}-${b.uid}`)});a.removeAll()}_removeAllReferenceItems(){const {referenceItems:a}=
this;a.forEach(b=>{this.removeHandles(`${"children"}-${b.uid}`)});a.removeAll()}_baseListItemCreatedFunctionChanged(){this._removeAllBaseItems();this._compileLists()}_referenceListItemCreatedFunctionChanged(){this._removeAllReferenceItems();this._compileLists()}_watchBasemapLayers(){const {view:a}=this;this.removeHandles(["base-layers","reference-layers","basemap","base-layer-views","reference-layer-views"]);this._compileLists();a&&a.ready&&this.addHandles([f.watch(()=>this.view?.map?.basemap?.baseLayers,
b=>this._createItemChangeHandles({items:b,key:"base-layers",callback:this._compileBaseList}),f.initial),f.watch(()=>this.view?.map?.basemap?.referenceLayers,b=>this._createItemChangeHandles({items:b,key:"reference-layers",callback:this._compileReferenceList}),f.initial),f.watch(()=>this.view?.basemapView?.baseLayerViews,b=>this._createItemChangeHandles({items:b,key:"base-layer-views",callback:this._compileBaseList}),f.initial),f.watch(()=>this.view?.basemapView?.referenceLayerViews,b=>this._createItemChangeHandles({items:b,
key:"reference-layer-views",callback:this._compileReferenceList}),f.initial)],"basemap")}};g.__decorate([h.property({type:l,readOnly:!0})],e.prototype,"baseItems",void 0);g.__decorate([h.property()],e.prototype,"basemapTitle",null);g.__decorate([h.property()],e.prototype,"baseListItemCreatedFunction",void 0);g.__decorate([h.property()],e.prototype,"checkPublishStatusEnabled",void 0);g.__decorate([h.property()],e.prototype,"referenceListItemCreatedFunction",void 0);g.__decorate([h.property({type:l,
readOnly:!0})],e.prototype,"referenceItems",void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"state",null);g.__decorate([h.property()],e.prototype,"view",void 0);g.__decorate([h.property()],e.prototype,"transferListItem",null);return e=g.__decorate([v.subclass("esri.widgets.BasemapLayerList.BasemapLayerListViewModel")],e)});