// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../has ../lang ../Logger ../ObjectPool ./interfaces ./Property ./PropertyOrigin ./Store ./tracking ./tracking/Flags".split(" "),function(y,p,q,r,g,n,h,t,l,f){q.getLogger("esri.core.accessorSupport.Properties");class u{constructor(a){this.host=a;this.propertiesByName=new Map;this.ctorArgs=null;this.destroyed=!1;this.lifecycle=g.Lifecycle.INITIALIZING;this.store=new t.Store;this._origin=h.OriginId.USER;a=this.host.constructor.__accessorMetadata__;for(const b in a){const c=new n.Property(b,a[b]);
this.propertiesByName.set(b,c)}this.metadatas=a}initialize(){this.lifecycle=g.Lifecycle.CONSTRUCTING}constructed(){this.lifecycle=g.Lifecycle.CONSTRUCTED}destroy(){this.destroyed=!0;for(const [a,b]of this.propertiesByName){if(b.metadata.autoDestroy){const c=this.internalGet(a);c&&c&&"function"===typeof c.destroy&&(c.destroy(),~b.flags&f.Flags.NonNullable&&this._internalSet(b,null))}b.destroy()}}get initialized(){return this.lifecycle!==g.Lifecycle.INITIALIZING}get(a){const b=this.propertiesByName.get(a);
if(b.metadata.get)return b.getComputed(this);l.trackAccess(b);const c=this.store;return c.has(a)?c.get(a):b.metadata.value}originOf(a){const b=this.store.originOf(a);return void 0===b&&(a=this.propertiesByName.get(a),void 0!==a&&a.flags&f.Flags.HasDefaultValue)?"defaults":h.idToName(b)}has(a){return this.propertiesByName.has(a)?this.store.has(a):!1}keys(){return[...this.propertiesByName.keys()]}internalGet(a){const b=this.propertiesByName.get(a);if(void 0!==b)return this.store.has(a)?this.store.get(a):
b.metadata.value}internalSet(a,b){a=this.propertiesByName.get(a);void 0!==a&&this._internalSet(a,b)}getDependsInfo(a,b,c){const e=this.propertiesByName.get(b);if(void 0===e)return"";const d=new Set,v=l.runTracked({onObservableAccessed:k=>d.add(k),onTrackingEnd:()=>{}},()=>e.metadata.get?.call(a)),w=a.declaredClass.split(".").pop();b=`${c}${w}.${b}: ${v}\n`;if(0===d.size)return b;c+="  ";for(const k of d)k instanceof n.Property&&(b+=`${c}${k.propertyName}: undefined\n`);return b}setAtOrigin(a,b,c){a=
this.propertiesByName.get(a);if(void 0!==a)return this._setAtOrigin(a,b,c)}isOverridden(a){a=this.propertiesByName.get(a);return void 0!==a&&!!(a.flags&f.Flags.Overriden)}clearOverride(a){(a=this.propertiesByName.get(a))&&a.flags&f.Flags.Overriden&&(a.flags&=~f.Flags.Overriden,a.notifyChange())}override(a,b){a=this.propertiesByName.get(a);if(!(void 0===a||null==b&&a.flags&f.Flags.NonNullable)){var c=a.metadata.cast;if(c){b=this._cast(c,b);const {valid:e,value:d}=b;m.release(b);if(!e)return;b=d}a.flags|=
f.Flags.Overriden;this._internalSet(a,b)}}set(a,b){a=this.propertiesByName.get(a);if(!(void 0===a||null==b&&a.flags&f.Flags.NonNullable)){var c=a.metadata.cast;if(c){b=this._cast(c,b);const {valid:e,value:d}=b;m.release(b);if(!e)return;b=d}(c=a.metadata.set)?c.call(this.host,b):this._internalSet(a,b)}}setDefaultOrigin(a){this._origin=h.nameToId(a)}getDefaultOrigin(){return h.idToName(this._origin)}notifyChange(a){a=this.propertiesByName.get(a);void 0!==a&&a.notifyChange()}invalidate(a){a=this.propertiesByName.get(a);
void 0!==a&&a.invalidate()}commit(a){a=this.propertiesByName.get(a);void 0!==a&&a.commit()}_internalSet(a,b){this._setAtOrigin(a,b,this.lifecycle!==g.Lifecycle.INITIALIZING?this._origin:h.OriginId.DEFAULTS)}_setAtOrigin(a,b,c){const e=this.store,d=a.propertyName;e.has(d,c)&&p.equals(b,e.get(d))&&~a.flags&f.Flags.Overriden&&c===e.originOf(d)||(a.invalidate(),e.set(d,b,c),a.commit(),l.initializeDependencyTracking(this.host,a))}_cast(a,b){const c=m.acquire();c.valid=!0;c.value=b;a&&(c.value=a.call(this.host,
b,c));return c}}class x{constructor(){this.value=null;this.valid=!0}acquire(){this.valid=!0}release(){this.value=null}}const m=new r(x);return u});