// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../core/unitUtils ../../../chunks/mat3f64 ../../../chunks/mat4 ../../../chunks/mat4f64 ../../../chunks/vec3 ../../../chunks/vec3f64 ../../../chunks/mat3 ../../projection ../../spatialReferenceEllipsoidUtils ../../projection/computeTranslationToOriginAndRotation ../../projection/projectBuffer ../DoubleArray ../MeshGeoreferencedRelativeVertexSpace ../MeshGeoreferencedVertexSpace ../MeshLocalVertexSpace ../MeshTransform ../../../chunks/vec32 ./geographicUtils ./projection".split(" "),
function(l,z,K,t,p,L,u,A,M,B,C,D,v,N,O,P,Q,k,E,m){function w(a,b,c){if(E.isGeographicMesh(b.spatialReference,c)){var e=b.spatialReference,f=F(b,c,n),d=new Float64Array(a.position.length);b=a.position;var g=e;var h=d;k.transformMat4(h,b,f);b=new Float64Array(b.length);g=m.projectFromPCPF(h,b,g);f=A.normalFromMat4(G,f);h=d;b=a.normal;c=f;var q=e;if(null==b)h=null;else{var r=new Float32Array(b.length);k.transformMat3(r,b,c);m.projectNormalFromPCPF(r,g,h,q,r);h=r}a=a.tangent;if(null==a)a=null;else{b=
new Float32Array(a.length);k.transformMat3(b,a,f,4);for(f=3;f<b.length;f+=4)b[f]=a[f];m.projectTangentFromPCPF(b,g,d,e,b);a=b}a={position:g,normal:h,tangent:a}}else{e=new Float64Array(a.position.length);g=a.position;d=b.x;f=b.y;h=b.z??0;b=x(c?c.unit:null,b.spatialReference);for(c=0;c<g.length;c+=3)e[c]=g[c]*b+d,e[c+1]=g[c+1]*b+f,e[c+2]=g[c+2]*b+h;a={position:e,normal:a.normal,tangent:a.tangent}}return a}function H(a,b=p.IDENTITY){const {position:c,normal:e,tangent:f}=a;a=k.transformMat4(new Float64Array(c.length),
c,b);const d=null!=e?m.transformNormal(e,new Float32Array(e.length),b):null;b=null!=f?m.transformTangent(f,new Float32Array(f.length),b):null;return{position:a,normal:d,tangent:b}}function I(a,b,c,e){const {position:f,normal:d,tangent:g}=a;if(!b.isRelative)return{position:f,normal:d,tangent:g};a=H(a,c?.localMatrix);return w(a,b.getOriginPoint(e),{geographic:!b.isGeoreferenced})}function y(a,b,c){if(E.isGeographicMesh(b.spatialReference,c)){const g=b.spatialReference;F(b,c,n);var e=t.invert(R,n);b=
new Float64Array(a.position.length);c=e;var f=m.projectToPCPF(a.position,g,b),d=new Float64Array(f.length);k.transformMat4(d,f,c);c=d;e=A.normalFromMat4(G,e);d=a.normal;f=e;null==d?f=null:(d=m.projectNormalToPCPF(d,a.position,b,g,new Float32Array(d.length)),k.transformMat3(d,d,f),f=d);d=a.tangent;null==d?a=null:(a=m.projectTangentToPCPF(d,a.position,b,g,new Float32Array(d.length)),k.transformMat3(a,a,e,4));a={position:c,normal:f,tangent:a}}else a=J(a,b,c);return a}function J(a,b,c){const e=new Float64Array(a.position.length),
f=a.position,d=b.x,g=b.y,h=b.z??0;b=x(c?c.unit:null,b.spatialReference);for(c=0;c<f.length;c+=3)e[c]=(f[c]-d)/b,e[c+1]=(f[c+1]-g)/b,e[c+2]=(f[c+2]-h)/b;return{position:e,normal:a.normal,tangent:a.tangent}}function F(a,b,c){C.computeTranslationToOriginAndRotation(a.spatialReference,[a.x,a.y,a.z??0],c,B.getSphericalPCPF(a.spatialReference));a=x(b?b.unit:null,a.spatialReference);t.scale(c,c,[a,a,a]);return c}function x(a,b){if(null==a)return 1;b=z.getMetersPerCartesianUnitForSR(b);return 1/z.convertUnit(b,
"meters",a)}const n=p.create(),R=p.create(),G=K.create();l.applyTransform=H;l.georeference=w;l.georeferenceApplyTransform=I;l.georeferenceByTransform=function(a,b,c){if(c?.useTransform){const {position:e,normal:f,tangent:d}=a,{x:g,y:h,z:q}=b;a=u.fromValues(g,h,q??0);return{vertexAttributes:{position:e,normal:f,tangent:d},vertexSpace:c.geographic??!0?new P({origin:a}):new N({origin:a}),transform:new Q}}return{vertexAttributes:w(a,b,c),vertexSpace:new O,transform:null}};l.project=function({positions:a,
transform:b,vertexSpace:c,inSpatialReference:e,outSpatialReference:f,outPositions:d,localMode:g}){const h=c.isRelative?c.origin:u.ZEROS;b=c.isRelative?b?.localMatrix??p.IDENTITY:p.IDENTITY;if(c.isGeoreferenced){d=d??v.newDoubleArray(a.length);t.equals(b,p.IDENTITY)?v.copyInto(d,a):k.transformMat4(d,a,b);if(!L.exactEquals(h,u.ZEROS)){const [r,S,T]=h;for(a=0;a<d.length;a+=3)d[a]+=r,d[a+1]+=S,d[a+2]+=T}D.projectBuffer(d,e,0,d,f,0,d.length/3);return d}c=e;const q=B.getSphericalPCPF(e);c=f.isWebMercator&&
g||!M.canProjectWithoutEngine(e,q)?c:q;C.computeTranslationToOriginAndRotation(e,h,n,c);t.multiply(n,n,b);e=d??v.newDoubleArray(a.length);k.transformMat4(e,a,n);D.projectBuffer(e,c,0,e,f,0,e.length/3);return e};l.ungeoreference=y;l.ungeoreferenceByTransform=function(a,b,c,e,f){if(!b.isRelative)return y(a,e,f);const {spatialReference:d}=e;a=I(a,b,c,d);return e.equals(b.getOriginPoint(d))?J(a,e,f):y(a,e,f)};Object.defineProperty(l,Symbol.toStringTag,{value:"Module"})});