// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../../../core/has ../../../../../../core/promiseUtils ../../../../../../geometry/libtess ../../DisplayId ../templates/WGLLabelTemplate ../templates/WGLMarkerTemplate ../templates/WGLTemplateStore".split(" "),function(q,y,r,t,v,u,w,n){class x{constructor(a,b,c){this._geometryType=a;this._idField=b;this._templateStore=c}update(a,b){null!=a.mesh.labels&&(this._labelTemplates=this._createLabelTemplates(a.mesh.labels,b));this._schema=a}_createLabelTemplates(a,b){const c=new Map;
if("simple"===a.type){for(var d of a.classes)a=u.fromLabelClass(d,b),c.set(d.index,a);return c}for(const f in a.classes){d=a.classes[f];for(const e of d)d=u.fromLabelClass(e,b),c.set(e.index,d)}return c}get templates(){return this._templateStore}async analyze(a,b,c,d,f,e,h){if(!r.isAborted(h)){var g;"dictionary"===c?.type&&(g=await c.analyze(this._idField,a.copy(),b,f,e,h));for(b=0;a.next();){var k=null;k=g?g[b++]:null!=d&&v.isAggregateId(a.getDisplayId())&&1!==a.readAttribute("cluster_count")?d.match(this._idField,
a,this._geometryType,f,e):c.match(this._idField,a,this._geometryType,f,e);a.setGroupId(k);if(n.isDynamicId(k)){k=this._templateStore.getDynamicTemplateGroup(k).templates;for(const l of k)l&&l.analyze&&l.analyze(this._templateStore,a,f,e)}}await t.loadLibtess();return this._templateStore.finalize(h)}}async analyzeGraphics(a,b,c,d,f,e){if(!r.isAborted(e)){a=a.getCursor();for(c&&await c.analyze(this._idField,a.copy(),b,d,f,e);a.next();){b=a.getGroupId();if(null==b||-1===b)b=c?.match(this._idField,a,
a.geometryType,d,f),a.setGroupId(b);if(n.isDynamicId(b)){const h=this._templateStore.getDynamicTemplateGroup(b).templates;for(const g of h)g&&g.analyze&&g.analyze(this._templateStore,a,d,f)}a.setGroupId(b)}await t.loadLibtess();return this._templateStore.finalize(e)}}writeGraphic(a,b,c,d){const f=b.getGroupId(),e=b.getDisplayId(),h=this._templateStore.getTemplateGroup(f);a.featureStart(b.insertAfter,0);if(null!=e){if(n.isDynamicId(f))for(const g of h.templates)g&&g.bindFeature(b,null,null);if(h){for(const g of h.templates)g&&
g.write(a,b,c,d);a.featureEnd()}}}writeCursor(a,b,c,d,f,e,h){const g=b.getGroupId(),k=b.getDisplayId();var l=this._templateStore.getTemplateGroup(g);const m=l.templates;l=this._getSortKeyValue(b,l);a.featureStart(0,l);if(null!=k&&m){if(n.isDynamicId(g))for(const p of m)p.bindFeature(b,c,d);for(const p of m)p.write(a,b,f,h);m.length&&null!=e&&(c=e&&this._findLabelRef(m),this._writeLabels(a,b,e,c,f,h));a.featureEnd()}}_getSortKeyValue(a,b){const c=this._schema.mesh.sortKey;if(null==c)return 0;let d=
0;d=!0===c.byRenderer&&null!=b.sortKey?b.sortKey:null!=c.fieldIndex?a.getComputedNumericAtIndex(c.fieldIndex):null!=c.field?a.readAttribute(c.field):a.readAttribute(this._idField);d*="asc"===c.order?1:-1;return null==d||isNaN(d)?0:d}_findLabelRef(a){for(const b of a)if(b instanceof w)return b;return null}_writeLabels(a,b,c,d,f,e){for(const h of c)if(null!=h&&h){const {glyphs:g,rtl:k,index:l}=h;if(c=this._labelTemplates.get(l))c.setZoomLevel(f),c.bindReferenceTemplate(d),c.bindTextInfo(g,k),c.write(a,
b,null,e)}}}q.WGLMeshFactory=x;Object.defineProperty(q,Symbol.toStringTag,{value:"Module"})});