// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/PooledArray ../../../../core/promiseUtils ../../../../core/accessorSupport/decorators/property ../../../../core/accessorSupport/ensureType ../../../../core/arrayUtils ../../../../core/has ../../../../core/accessorSupport/decorators/subclass ../core/shaderLibrary/ShaderOutput ../lib/basicInterfaces ../lib/depthRange ../lib/Material ../lib/RenderSlot".split(" "),function(e,h,m,n,k,p,w,x,y,q,g,r,l,t,u){e.RenderPluginManager=
class extends m{constructor(a){super({});this._context=a;this._renderPlugins=new n;this._slots=[];for(a=0;a<u.RenderSlot.MAX_SLOTS;++a)this._slots[a]=[]}normalizeCtorArgs(){return{}}add(a,b){const c=()=>{if(b?.aborted)throw a.uninitializeRenderContext(),k.createAbortError();this._renderPlugins.push(a);a.produces.forEach((f,v)=>{this._slots[v].push(a)});this._context.requestRender();this.notifyChange("updating")},d=a.initializeRenderContext(this._context,b);if(k.isPromiseLike(d))return d.then(c);c()}remove(a){if(null!=
this._renderPlugins.removeUnordered(a)){for(let b=0;b<this._slots.length;++b)this._slots[b]=this._slots[b].filter(c=>c!==a);a.uninitializeRenderContext();this._context.requestRender();this.notifyChange("updating")}}prepareRender(){this._renderPlugins.forAll(a=>{a.prepareRender&&a.prepareRender(this._context.renderContext)})}updateAnimation(a){let b=!1;this._renderPlugins.forAll(c=>{c.updateAnimation&&(b=c.updateAnimation(a)||b)});return b}renderFeatureChanged(){this._renderPlugins.forAll(a=>{a.renderFeatureChanged&&
a.renderFeatureChanged()})}prepare(a){this._context.renderContext.bindParameters.slot=a;this._slots[a].forEach(b=>{const c=b.produces.get(a);c&&c(g.ShaderOutput.Color)&&("prepareTechnique"in b&&b.prepareTechnique(this._context.renderContext),"prepareTechniques"in b&&b.prepareTechniques(this._context.renderContext))})}_getRenderables(a){this._context.renderContext.bindParameters.slot=a;const b=new Map;this._slots[a].forEach(c=>{var d=c.produces.get(a);!d||!d(g.ShaderOutput.Color)||c.isDecoration&&
this._context.renderContext.bindParameters.decorations===r.Decorations.OFF||("prepareTechnique"in c?(d=c.prepareTechnique(this._context.renderContext),null!=d&&b.set(c,d)):"prepareTechniques"in c?(d=c.prepareTechniques(this._context.renderContext),null!=d&&b.set(c,d)):b.set(c,null))});return b}render(a,b=null,c=null){this._getRenderables(a).forEach((d,f)=>c=f.renderNode(this._context.renderContext,d,b,c));return c}renderComposition(a,b){let c=null;this._getRenderables(a).forEach((d,f)=>{d=f.renderNode(this._context.renderContext,
d,b,null);c?.release();c=d;b.composite=c});return c}queryDepthRange(a){const b=new l.DepthRange;this._renderPlugins.forAll(c=>{c=c.queryDepthRange?.(a);l.union(b,c)});return b}get updating(){return this._renderPlugins.some(a=>a.running)}produces(a,b=g.ShaderOutput.Color){return this._slots[a].some(c=>(c=c.produces.get(a))?c(b):!1)}consumes(a){return this._renderPlugins.some(b=>b.consumes().required.includes(a))}get hasDecorations(){return this._renderPlugins.some(a=>a.isDecoration)}get renderOccludedFlags(){return this._renderPlugins.reduce((a,
b)=>a|b.renderOccludedFlags,t.RenderOccludedFlag.None)}get usedMemory(){return this._renderPlugins.reduce((a,b)=>a+(b.usedMemory??0),0)}};h.__decorate([p.property({readOnly:!0})],e.RenderPluginManager.prototype,"updating",null);e.RenderPluginManager=h.__decorate([q.subclass("esri.views.3d.webgl-engine.lib.RenderPluginManager")],e.RenderPluginManager);Object.defineProperty(e,Symbol.toStringTag,{value:"Module"})});