// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("../../../../../../core/screenUtils ../../../../../../symbols/cim/enums ../../../../../../symbols/cim/utils ../../alignmentUtils ../../color ../../definitions ../../number ../../materialKey/MaterialKey ./util ./WGLBaseTextTemplate ./WGLDynamicMeshTemplate ../../../../layers/features/textUtils".split(" "),function(l,v,c,q,n,p,w,x,y,z,A,B){class r extends z(A){constructor(a,d,b){super(a);this._horizontalAlignment="center";this._verticalAlignment="middle";this._textToGlyphs=new Map;this._minMaxZoom=
w.i1616to32(Math.round(d*p.minMaxZoomPrecisionFactor),Math.round(b*p.minMaxZoomPrecisionFactor));d=a.scaleFactor||1;this._cimTextLayer=a;const h=a.color;c.isFeatureValueFn(h)?this._dynamicPropertyMap.set("_color",(e,f,g)=>n.premultiplyAlphaRGBA(h(e,f,g))):this._color=n.premultiplyAlphaRGBA(h);const k=a.outlineColor;c.isFeatureValueFn(k)?this._dynamicPropertyMap.set("_haloColor",(e,f,g)=>n.premultiplyAlphaRGBA(k(e,f,g))):this._haloColor=n.premultiplyAlphaRGBA(k);let m;c.isFeatureValueFn(a.size)||(m=
Math.min(Math.round(l.pt2px(a.size*a.sizeRatio)),127));this._dynamicPropertyMap.set("_size",(e,f,g)=>c.isFeatureValueFn(a.size)?Math.min(Math.round(l.pt2px(a.size(e,f,g)*a.sizeRatio)),127):m);c.isFeatureValueFn(a.outlineSize)?this._dynamicPropertyMap.set("_haloSize",(e,f,g)=>Math.min(Math.floor(5*l.pt2px(a.outlineSize(e,f,g)*a.sizeRatio)),127)):this._haloSize=Math.min(Math.floor(5*l.pt2px(a.outlineSize*a.sizeRatio)),127);let t;c.isFeatureValueFn(a.offsetX)||(t=Math.round(l.pt2px(a.offsetX*a.sizeRatio)));
this._dynamicPropertyMap.set("_xOffset",(e,f,g)=>c.isFeatureValueFn(a.offsetX)?Math.round(l.pt2px(a.offsetX(e,f,g)*a.sizeRatio)):t);let u;c.isFeatureValueFn(a.offsetY)||(u=Math.round(l.pt2px(a.offsetY*a.sizeRatio)));this._dynamicPropertyMap.set("_yOffset",(e,f,g)=>c.isFeatureValueFn(a.offsetY)?Math.round(l.pt2px(a.offsetY(e,f,g)*a.sizeRatio)):u);c.isFeatureValueFn(a.angle)?this._dynamicPropertyMap.set("_angle",a.angle):this._angle=a.angle;c.isFeatureValueFn(a.horizontalAlignment)?this._dynamicPropertyMap.set("_horizontalAlignment",
a.horizontalAlignment):this._horizontalAlignment=a.horizontalAlignment;c.isFeatureValueFn(a.verticalAlignment)?this._dynamicPropertyMap.set("_verticalAlignment",a.verticalAlignment):this._verticalAlignment=a.verticalAlignment;null!=a.effects&&(b=a.effects,c.isFeatureValueFn(b)?this._dynamicPropertyMap.set("_effects",b):this._effects=b);null!=a.markerPlacement&&(b=a.markerPlacement,c.isFeatureValueFn(b)?this._dynamicPropertyMap.set("_markerPlacement",b):this._textPlacement=b);c.isFeatureValueFn(a.text)?
this._dynamicPropertyMap.set("_text",a.text):this._text=a.text;this._backgroundColor=a.backgroundColor&&n.premultiplyAlphaRGBA(a.backgroundColor);this._borderLineColor=a.borderLineColor&&n.premultiplyAlphaRGBA(a.borderLineColor);this._borderLineSize=a.borderLineWidth;this._scaleFactor=d;d=Math.min(Math.round(l.pt2px(a.referenceSize*a.sizeRatio)),127);this._referenceSize=Math.round(Math.sqrt(256*d));this._materialKey=a.materialKey;d=x.TextMaterialKey.load(this._materialKey);d.sdf=!0;this._bitset=(a.alignment===
v.Alignment.MAP?1:0)|(a.colorLocked?1:0)<<1;this._materialKey=d.data;this._decoration="none";this._lineHeight=1;this._lineWidth=512;this._isCIM=!0}static fromCIMText(a,d){const [b,h]=y.getMinMaxZoom(a.scaleInfo,d);return new r(a,b,h)}async analyze(a,d,b,h){var k=d.readLegacyFeature();var m=this._cimTextLayer;k="string"===typeof m.text?m.text:"function"===typeof m.text?m.text(k,b,h)??"":"";a=await super.analyze(a,d,b,h,B.codepoints(k));a?.glyphMosaicItems&&this._textToGlyphs.set(k,a.glyphMosaicItems);
return a}bindFeature(a,d,b){const h=a.readLegacyFeature();this._dynamicPropertyMap.forEach((k,m)=>{this[m]=k(h,d,b)});this._text&&0!==this._text.length?(this._size*=this._scaleFactor,this._scale=this._size/p.glyphSize,this._xOffset*=this._scaleFactor,this._yOffset*=this._scaleFactor,this._xAlignD=q.getXAnchorDirection(this._horizontalAlignment??"center"),this._yAlignD=q.getYAnchorDirection(this._verticalAlignment??"baseline"),a=this._textToGlyphs.get(this._text)??[],this.bindTextInfo(a,!1)):this._shapingInfo=
null}}return r});