// All material copyright Esri, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.28/esri/copyright.txt for details.
//>>built
define("exports ../../../../request ../../../../core/arrayUtils ../../../../core/Error ../../../../core/has ../../../../core/typedArrayUtil ../../../../chunks/mat3 ../../../../chunks/mat3f64 ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/quat ../../../../chunks/quatf64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../geometry/ellipsoidUtils ../../../../geometry/projection ../../../../geometry/SpatialReference ../../../../geometry/spatialReferenceEllipsoidUtils ../../../../geometry/projection/computeTranslationToOriginAndRotation ../../../../geometry/projection/projectBuffer ../../../../geometry/projection/projectVectorToVector ../../../../geometry/support/aaBoundingRect ../../../../geometry/support/spatialReferenceUtils ../../../../rest/support/Query ./I3SBinaryReader ./I3SProjectionUtil ../support/edgeUtils ../support/symbolColorUtils ../../support/orientedBoundingBox ../../webgl-engine/lib/Attribute".split(" "),
function(h,ma,P,u,na,Q,oa,pa,qa,R,C,ra,p,K,sa,ta,S,A,ua,B,T,x,U,va,wa,xa,V,L,D,ya){function M(a){return a?parseInt(a.substring(a.lastIndexOf("/")+1,a.length),10):void 0}function W(a,b){var c=b[0],d=b[1];b=b[3];const e=a[0]-c;c-=a[2];const f=a[1]-d;a=d-a[3];d=Math.max(e,c,0);const g=Math.max(f,a,0);d=d*d+g*g;return d>b*b?h.MbsIntersectResult.OUTSIDE:0<d?h.MbsIntersectResult.INTERSECTS_CENTER_OUTSIDE:-Math.max(e,c,f,a)>b?h.MbsIntersectResult.INSIDE:h.MbsIntersectResult.INTERSECTS_CENTER_INSIDE}function X(a,
b,c){const d=[],e=c?.missingFields;c=c?.originalFields;for(const f of a){a=f.toLowerCase();let g=!1;for(const m of b)if(a===m.name.toLowerCase()){d.push(m.name);g=!0;c&&c.push(f);break}!g&&e&&e.push(f)}return d}function za(a,b,c){const d=new Map,e=[];c=c();for(const m of a){var f=m.attributes[b];for(var g=0;g<c.length;g++){a=c[g];const r=a.featureIds.indexOf(f);if(0<=r){f=d.get(a.node);f||(f={node:a.node,indices:[],graphics:[]},e.push(f),d.set(a.node,f));f.indices.push(r);for(f.graphics.push(m);0<
g;g--)c[g]=c[g-1];c[0]=a;break}}}return e}async function Aa(a,b,c,d){b.sort((g,m)=>g.attributes[c]-m.attributes[c]);var e=b.map(g=>g.attributes[c]);const f=[];d=X(d,a.fields,{originalFields:f});a=await Y(a,e,d);for(e=0;e<b.length;e++){const g=b[e],m=a[e],r={};if(g.attributes)for(const q in g.attributes)r[q]=g.attributes[q];for(let q=0;q<f.length;q++)r[f[q]]=m[d[q]];g.attributes=r}return b}function Y(a,b,c){var d=a.capabilities.query.maxRecordCount;if(null!=d&&b.length>d)return d=P.splitIntoChunks(b,
d),Promise.all(d.map(e=>Y(a,e,c))).then(e=>e.flat());d=new va({objectIds:b,outFields:c,orderByFields:[a.objectIdField]});return a.queryFeatures(d).then(e=>{if(e&&e.features&&e.features.length===b.length)return e.features.map(f=>f.attributes);throw new u("scenelayer:feature-not-in-associated-layer","Feature not found in associated feature layer");})}async function Z(a,b,c,d,e){const f=[];for(const g of b)g&&e.includes(g.name)&&f.push({url:`${a}/nodes/${c}/attributes/${g.key}/0`,storageInfo:g});a=await Promise.allSettled(f.map(g=>
ma(g.url,{responseType:"array-buffer"}).then(m=>wa.readBinaryAttribute(g.storageInfo,m.data))));b=[];for(const g of d){d={};for(c=0;c<a.length;c++)e=a[c],"fulfilled"===e.status&&(d[f[c].storageInfo.name]=aa(e.value,g));b.push(d)}return b}function aa(a,b){if(!a)return null;b=a[b];return Q.isInt16Array(a)?-32768===b?null:b:Q.isInt32Array(a)?b===Ba?null:b:b!==b?null:b}function ba(a){var b=a.store,c=b.indexCRS||b.geographicCRS;if(b=void 0===c?b.indexWKT:void 0)if(a.spatialReference){if(b!==a.spatialReference.wkt)throw new u("layerview:store-spatial-reference-wkt-index-incompatible",
"The indeWKT of the scene layer store does not match the WKT of the layer spatial reference",{});}else throw new u("layerview:no-store-spatial-reference-wkt-index-and-no-layer-spatial-reference","Found indeWKT in the scene layer store but no layer spatial reference",{});c=c?new S(M(c)):a.spatialReference;return c.equals(a.spatialReference)?a.spatialReference:c}function ca(a){var b=a.store,c=b.vertexCRS||b.projectedCRS;if(b=void 0===c?b.vertexWKT:void 0)if(a.spatialReference){if(b!==a.spatialReference.wkt)throw new u("layerview:store-spatial-reference-wkt-vertex-incompatible",
"The vertexWKT of the scene layer store does not match the WKT of the layer spatial reference",{});}else throw new u("layerview:no-store-spatial-reference-wkt-vertex-and-no-layer-spatial-reference","Found vertexWKT in the scene layer store but no layer spatial reference",{});c=c?new S(M(c)):a.spatialReference;return c.equals(a.spatialReference)?a.spatialReference:c}function G(a,b,c){if(!ta.canProjectWithoutEngine(a,b))throw new u("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",
{});if("local"===c&&!da(a,b))throw new u("layerview:spatial-reference-incompatible","The spatial reference of this scene layer is incompatible with the spatial reference of the view",{});}function da(a,b){return a.equals(b)||a.isWGS84&&b.isWebMercator||a.isWebMercator&&b.isWGS84}function ea(a,b,c){const d=ba(a);a=ca(a);G(d,b,c);G(a,b,c)}function fa(a,b,c,d,e=0){if(d===A.getSphericalPCPF(d))if(b.isGeographic){var f=sa.getReferenceEllipsoid(b);d=1+Math.max(0,e)/(f.radius+a.center[2]);p.set(c.center,
a.center[0],a.center[1],a.center[2]+e);B.projectBuffer(c.center,b,0,c.center,A.getSphericalPCPF(b),0,1);C.copy(c.quaternion,a.quaternion);C.conjugate(y,a.quaternion);p.set(k,0,0,1);p.transformQuat(k,k,y);p.set(k,a.halfSize[0]*Math.abs(k[0]),a.halfSize[1]*Math.abs(k[1]),a.halfSize[2]*Math.abs(k[2]));p.scale(k,k,f.inverseFlattening);p.add(c.halfSize,a.halfSize,k);p.scale(c.halfSize,c.halfSize,d)}else{D.corners(a,N);p.set(c.center,a.center[0],a.center[1],a.center[2]+e);ua.computeTranslationToOriginAndRotation(b,
c.center,t,A.getSphericalPCPF(b));p.set(c.center,t[12],t[13],t[14]);d=2*Math.sqrt(1+t[0]+t[5]+t[10]);y[0]=(t[6]-t[9])/d;y[1]=(t[8]-t[2])/d;y[2]=(t[1]-t[4])/d;y[3]=.25*d;C.multiply(c.quaternion,y,a.quaternion);C.conjugate(y,c.quaternion);let g=d=a=0;for(f of N)f[2]+=e,B.projectBuffer(f,b,0,f,A.getSphericalPCPF(b),0,1),p.sub(k,f,c.center),p.transformQuat(k,k,y),a=Math.max(a,Math.abs(k[0])),d=Math.max(d,Math.abs(k[1])),g=Math.max(g,Math.abs(k[2]));p.set(c.halfSize,a,d,g)}else b.isWGS84&&(d.isWebMercator||
U.isPlateCarree(d))?(p.copy(v,a.center),v[2]+=e,e=A.getSphericalPCPF(d),B.projectBuffer(v,b,0,v,e,0,1),ha(e,a,v,d,c)):b.isWebMercator&&U.isPlateCarree(d)?(p.copy(v,a.center),v[2]+=e,ha(b,a,v,d,c)):a===c?(c.center[2]+=e,B.projectBuffer(c.center,b,0,c.center,d,0,1)):(p.set(c.center,a.center[0],a.center[1],a.center[2]+e),B.projectBuffer(c.center,b,0,c.center,d,0,1),C.copy(c.quaternion,a.quaternion),p.copy(c.halfSize,a.halfSize))}function ha(a,b,c,d,e){const f=oa.fromQuat(Ca,b.quaternion);for(let m=0;8>
m;++m){for(var g=0;3>g;++g)ia[g]=b.halfSize[g]*(0!==(m&1<<g)?-1:1);for(g=0;3>g;++g){let r=c[g];for(let q=0;3>q;++q)r+=ia[q]*f[3*q+g];H[3*m+g]=r}}B.projectBuffer(H,a,0,H,d,0,8);D.compute(Da,e)}const E=x.create();h.MbsIntersectResult=void 0;(function(a){a[a.OUTSIDE=0]="OUTSIDE";a[a.INTERSECTS_CENTER_OUTSIDE=1]="INTERSECTS_CENTER_OUTSIDE";a[a.INTERSECTS_CENTER_INSIDE=2]="INTERSECTS_CENTER_INSIDE";a[a.INSIDE=3]="INSIDE"})(h.MbsIntersectResult||(h.MbsIntersectResult={}));const Ba=-(2**31),Ea=V.createSolidEdgeMaterial({color:[0,
0,0,0],opacity:0});class ja{constructor(){this.material=this.edgeMaterial=null;this.castShadows=!0}}const H=Array(24),Da=new ya.Vertices(H,3),ia=K.create(),v=K.create(),Ca=pa.create(),t=R.create(),y=ra.create(),N=[[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]],O=x.create(),I=x.create(),ka=D.create(),k=K.create(),la={data:Array(72),size:3,exclusive:!0,stride:3},J=R.create();h.SymbolInfo=ja;h.addWraparound=function(a,b){return(a|0)+(b|0)|0};h.checkPointCloudLayerCompatibleWithView=
function(a,b){G(a.spatialReference,b.spatialReference,b.viewingMode)};h.checkPointCloudLayerValid=function(a){var b;(b=null==a.store?.defaultGeometrySchema)||(a=a.store.defaultGeometrySchema,b=!!(null==a.geometryType||"points"!==a.geometryType||null!=a.topology&&"PerAttributeArray"!==a.topology||null!=a.encoding&&""!==a.encoding&&"lepcc-xyz"!==a.encoding||null==a.vertexAttributes?.position));if(b)throw new u("pointcloud:unsupported-geometry-schema","The geometry schema of this point cloud scene layer is not supported.",
{});};h.checkRecyclable=function(a,b,c){if(a.serviceUpdateTimeStamp?.lastUpdate!==b.serviceUpdateTimeStamp?.lastUpdate||!c.isEmpty||a.associatedLayer?.url!==b.associatedLayer?.url)throw new u("layerview:recycle-failed");};h.checkSceneLayerCompatibleWithView=function(a,b){ea(a,b.spatialReference,b.viewingMode)};h.checkSceneLayerValid=function(a){var b;(b=null==a.store?.defaultGeometrySchema)||(b=a.store.defaultGeometrySchema,b=!!(null!=b.geometryType&&"triangles"!==b.geometryType||null!=b.topology&&
"PerAttributeArray"!==b.topology||null==b.vertexAttributes?.position));if(b)throw new u("scenelayer:unsupported-geometry-schema","The geometry schema of this scene layer is not supported.",{url:a.parsedUrl.path});};h.checkSpatialReference=G;h.checkSpatialReferences=ea;h.computeVisibilityObb=function(a,b,c,d,e,f){if(!f||0===f.length||null==b||!a.mbs)return null;const g=xa.computeGlobalTransformation(a.mbs,e,c,b);qa.invert(J,g);let m=null;const r=()=>{if(!m)if(m=N,x.empty(I),null!=a.serviceObb){fa(a.serviceObb,
c,ka,b,e);D.corners(ka,m);for(var l of m)p.transformMat4(l,l,J),x.expandPointInPlace(I,l)}else{var n=a.mbs;if(n)for(l=n[3],T.projectVectorToVector(n,c,k,b),p.transformMat4(k,k,J),k[2]+=e,n=0;8>n;++n){const w=m[n];p.copy(w,[k[0]+(n&1?l:-l),k[1]+(n&2?l:-l),k[2]+(n&4?l:-l)]);x.expandPointInPlace(I,w)}}};let q=Infinity,z=-Infinity;const F=l=>{if("replace"===l.type&&(l=l.geometry,l?.hasZ)){x.empty(O);var n=l.spatialReference||d;l=l.rings.reduce((w,Fa)=>Fa.reduce((Ga,Ha)=>{T.projectVectorToVector(Ha,n,
k,b);p.transformMat4(k,k,J);x.expandPointInPlace(O,k);return Math.min(k[2],Ga)},w),Infinity);r();x.intersects(I,O)&&(q=Math.min(q,l),z=Math.max(z,l))}};f.forEach(l=>F(l));if(Infinity===q)return null;f=(l,n,w)=>{p.transformMat4(k,w,g);l[n]=k[0];l[n+1]=k[1];l[n+2]=k[2];n+=24;w[2]=q;p.transformMat4(k,w,g);l[n]=k[0];l[n+1]=k[1];l[n+2]=k[2];n+=24;w[2]=z;p.transformMat4(k,w,g);l[n]=k[0];l[n+1]=k[1];l[n+2]=k[2]};for(let l=0;8>l;++l)f(la.data,3*l,m[l]);return D.compute(la)};h.containsDraco=function(a){if(na("disable-feature:i3s-draco")||
!a)return!1;for(const b of a)for(const c of b.geometryBuffers)if("draco"===c.compressedAttributes?.encoding)return!0;return!1};h.extractWkid=M;h.filterInPlace=function(a,b,c){let d=0,e=0;for(let f=0;f<b.length&&d<a.length;f++)a[d]===b[f]&&(c(f)&&(a[e]=a[d],e++),d++);a.length=e};h.findFieldsCaseInsensitive=X;h.findIntersectingNodes=function(a,b,c,d){c.traverse(b,e=>{const f=e.mbs;if((null!=f&&W(a,f))===h.MbsIntersectResult.OUTSIDE)return!1;d(e);return!0})};h.getCacheKeySuffix=function(a,b){return null==
b?"@null":b===A.getSphericalPCPF(b)?"@ECEF":a.equals(b)?"":null!=b.wkid?"@"+b.wkid:null};h.getCachedAttributeValue=aa;h.getClipRect=function(a,b){if(0===b.rotationScale[1]&&0===b.rotationScale[2]&&0===b.rotationScale[3]&&0===b.rotationScale[5]&&0===b.rotationScale[6]&&0===b.rotationScale[7])return E[0]=(a[0]-b.position[0])/b.rotationScale[0],E[1]=(a[1]-b.position[1])/b.rotationScale[4],E[2]=(a[2]-b.position[0])/b.rotationScale[0],E[3]=(a[3]-b.position[1])/b.rotationScale[4],E};h.getIndexCrs=ba;h.getSymbolInfo=
function(a){const b=new ja;var c=!1;let d=!1;for(const f of a.symbolLayers.items)if("fill"===f.type&&f.enabled){var e=f.material;a=f.edges;null==e||c||(c=e.color,e=L.parseColorMixMode(e.colorMixMode),b.material=null!=c?{color:[c.r/255,c.g/255,c.b/255],alpha:c.a,colorMixMode:e}:{color:[1,1,1],alpha:1,colorMixMode:L.ColorMixModeEnum.Multiply},b.castShadows=f.castShadows,c=!0);null==a||d||(b.edgeMaterial=V.createMaterialFromEdges(a,{}),d=!0)}b.material||(b.material={color:[1,1,1],alpha:1,colorMixMode:L.ColorMixModeEnum.Multiply});
return b};h.getVertexCrs=ca;h.intersectBoundingRectWithMbs=W;h.invalidateMbs=function(a){null!=a&&(a[3]=-1)};h.invalidateObb=function(a){null!=a&&(a.halfSize[0]=-1)};h.isSupportedLocalModeProjection=da;h.isValidMbs=function(a){return 0<=a[3]};h.isValidObb=function(a){return null!=a&&0<=a.halfSize[0]};h.objectIdFilter=function(a,b,c){let d=0,e=0;for(;d<c.length;)0<=P.binaryIndexOf(a,c[d])===b&&(c[e]=c[d],e++),d++;c.length=e};h.queryAttributesFromCachedAttributesId=Z;h.rendererNeedsTextures=function(a){if(null==
a||"simple"!==a.type&&"class-breaks"!==a.type&&"unique-value"!==a.type||("unique-value"===a.type||"class-breaks"===a.type)&&null==a.defaultSymbol)return!0;a=a.getSymbols();if(0===a.length)return!0;for(const b of a){if("mesh-3d"!==b.type||0===b.symbolLayers.length)return!0;for(const c of b.symbolLayers.items)if("fill"!==c.type||null==c.material?.color||"replace"!==c.material.colorMixMode)return!0}return!1};h.transformObb=fa;h.transparentEdgeMaterial=Ea;h.whenGraphicAttributes=async function(a,b,c,
d,e){if(0===b.length)return[];const f=a.attributeStorageInfo;if(null!=a.associatedLayer)try{return await Aa(a.associatedLayer,b,c,d)}catch(g){if(a.associatedLayer.loaded)throw g;}if(f){b=za(b,c,e);if(null==b)throw new u("scenelayer:features-not-loaded","Tried to query attributes for unloaded features");const g=a.parsedUrl.path;return(await Promise.all(b.map(m=>Z(g,f,m.node.resources.attributes,m.indices,d).then(r=>{for(let q=0;q<m.graphics.length;q++){const z=m.graphics[q],F=r[q];if(z.attributes)for(const l in z.attributes)l in
F||(F[l]=z.attributes[l]);z.attributes=F}return m.graphics})))).flat()}throw new u("scenelayer:no-attribute-source","This scene layer does not have a source for attributes available");};Object.defineProperty(h,Symbol.toStringTag,{value:"Module"})});